In [1]:
import numpy as np
a = np.array([[1,2],[3,5],[5,3]])
a.ndim

2

In [2]:
a = np.array([[1,2],[3,5],[3,5]], dtype=np.float64)
print(a.itemsize)

8


In [3]:
a.shape

(3, 2)

In [4]:
a.size

6

In [5]:
a = np.array([[1,2],[3,5],[3,5]], dtype=complex)
print(a)

[[1.+0.j 2.+0.j]
 [3.+0.j 5.+0.j]
 [3.+0.j 5.+0.j]]


In [6]:
np.arange(1,5,2)

array([1, 3])

In [7]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [8]:
a = np.array([[1,2],[3,5],[3,5]])
print(a.min())
print(a.max())
print(a.sum())
print(a.sum(axis=1))
print(a.sum(axis=0))

1
5
19
[3 8 8]
[ 7 12]


In [9]:
np.std(a)

1.4624940645653537

In [10]:
a = np.array([[2,3],[3,4]])
b = np.array([[3,4],[3,5]])
print(a,"\n",b)

[[2 3]
 [3 4]] 
 [[3 4]
 [3 5]]


In [11]:
print(a+b)

[[5 7]
 [6 9]]


In [12]:
np.dot(a,b)

array([[15, 23],
       [21, 32]])

In [13]:
import pandas as pd
df = pd.read_csv("sec_bhavdata_full.csv")
print(df)

          SYMBOL  SERIES         DATE1  PREV_CLOSE   OPEN_PRICE   HIGH_PRICE  \
0      20MICRONS      EQ   09-Oct-2020       27.95        27.95        28.35   
1     21STCENMGM      EQ   09-Oct-2020       10.10        10.30        10.30   
2     3IINFOTECH      EQ   09-Oct-2020        3.35         3.35         3.40   
3        3MINDIA      EQ   09-Oct-2020    18896.70     18988.00     19549.95   
4         5PAISA      BE   09-Oct-2020      351.20       368.75       368.75   
...          ...     ...           ...         ...          ...          ...   
1980   ZODJRDMKJ      EQ   09-Oct-2020       24.15        24.15        25.30   
1981        ZOTA      EQ   09-Oct-2020      145.75       145.95       147.90   
1982       ZUARI      EQ   09-Oct-2020       82.70        83.20        83.25   
1983   ZUARIGLOB      EQ   09-Oct-2020       50.30        50.70        51.00   
1984   ZYDUSWELL      EQ   09-Oct-2020     1787.25      1808.00      1852.00   

       LOW_PRICE  LAST_PRICE   CLOSE_PR

In [14]:
df.shape

(1985, 15)

In [15]:
df[[' LOW_PRICE', 'PREV_CLOSE']]

LOW_PRICE  PREV_CLOSE
0          27.30       27.95
1           9.90       10.10
2           3.20        3.35
3       18708.00    18896.70
4         361.20      351.20
...          ...         ...
1980       23.65       24.15
1981      145.30      145.75
1982       81.80       82.70
1983       48.20       50.30
1984     1776.30     1787.25

[1985 rows x 2 columns]

In [16]:
df['PREV_CLOSE'].max()

60175.35

In [17]:
df['PREV_CLOSE'].std()

2186.598103397098

In [18]:
df[df.PREV_CLOSE==df.PREV_CLOSE.max()]

SYMBOL  SERIES         DATE1  PREV_CLOSE   OPEN_PRICE   HIGH_PRICE  \
1154    MRF      EQ   09-Oct-2020    60175.35      60677.9      60677.9   

       LOW_PRICE  LAST_PRICE   CLOSE_PRICE   AVG_PRICE   TTL_TRD_QNTY  \
1154    58542.65       58798       58784.9    59335.48          12645   

       TURNOVER_LACS   NO_OF_TRADES  DELIV_QTY  DELIV_PER  
1154         7502.97           6314       4241      33.54

In [19]:
df[[' SERIES', 'PREV_CLOSE']][df.PREV_CLOSE==df['PREV_CLOSE'].max()]

SERIES  PREV_CLOSE
1154      EQ    60175.35

In [20]:
weather_data = [
    ('1/1/2017',32,6,'Rain'),
    ('i/2/2017',35,7,'Sunny'),
    ('1/3/2017',28,2,'Snow')
]
df=pd.DataFrame(weather_data, columns=['day','Temperature','Windspeed','event'])
print(df)

        day  Temperature  Windspeed  event
0  1/1/2017           32          6   Rain
1  i/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow


In [21]:
df = pd.read_csv('sec_bhavdata_full.csv')
print(df)

          SYMBOL  SERIES         DATE1  PREV_CLOSE   OPEN_PRICE   HIGH_PRICE  \
0      20MICRONS      EQ   09-Oct-2020       27.95        27.95        28.35   
1     21STCENMGM      EQ   09-Oct-2020       10.10        10.30        10.30   
2     3IINFOTECH      EQ   09-Oct-2020        3.35         3.35         3.40   
3        3MINDIA      EQ   09-Oct-2020    18896.70     18988.00     19549.95   
4         5PAISA      BE   09-Oct-2020      351.20       368.75       368.75   
...          ...     ...           ...         ...          ...          ...   
1980   ZODJRDMKJ      EQ   09-Oct-2020       24.15        24.15        25.30   
1981        ZOTA      EQ   09-Oct-2020      145.75       145.95       147.90   
1982       ZUARI      EQ   09-Oct-2020       82.70        83.20        83.25   
1983   ZUARIGLOB      EQ   09-Oct-2020       50.30        50.70        51.00   
1984   ZYDUSWELL      EQ   09-Oct-2020     1787.25      1808.00      1852.00   

       LOW_PRICE  LAST_PRICE   CLOSE_PR

In [22]:
df_stocks=pd.DataFrame({
    'tickers':['GOOGL','WMT','MSFT'],
    'price':[845,65,64],
    'pe':[30.37,14.26,30.97],
    'eps':[27.82,4.61,2.12]
})
df_weather = pd.DataFrame({
    'day':['1/1/2020','1/2/2020','1/3/2020'],
    'temperature':[32,35,28],
    'event':['Rain','Sunny','Snow']
})
with pd.ExcelWriter('stocks_weather.xlsx') as writer:
    df_stocks.to_excel(writer, sheet_name='stocks')
    df_weather.to_excel(writer, sheet_name="weather")

In [23]:
df = pd.read_excel('Book.xlsx')
print(df)

   Unnamed: 0        Day  Temperature  windspeed  event
0           0 2020-01-01         32.0        6.0   Rain
1           1 2020-02-01          NaN        7.0  Sunny
2           2 2020-03-01         28.0        NaN   Snow
3           3 2020-04-01          NaN        7.0    NaN
4           4 2020-05-01         32.0        NaN   Rain
5           5 2020-06-01         31.0        3.0  Sunny
6           6 2020-06-01         34.0        5.0    NaN


In [24]:
df1 = pd.read_excel('stocks_weather.xlsx')
print(df1)

   Unnamed: 0 tickers  price     pe    eps
0           0   GOOGL    845  30.37  27.82
1           1     WMT     65  14.26   4.61
2           2    MSFT     64  30.97   2.12


In [25]:
newdf = df.replace(-9999,np.NaN)
print(newdf)

   Unnamed: 0        Day  Temperature  windspeed  event
0           0 2020-01-01         32.0        6.0   Rain
1           1 2020-02-01          NaN        7.0  Sunny
2           2 2020-03-01         28.0        NaN   Snow
3           3 2020-04-01          NaN        7.0    NaN
4           4 2020-05-01         32.0        NaN   Rain
5           5 2020-06-01         31.0        3.0  Sunny
6           6 2020-06-01         34.0        5.0    NaN


In [26]:
print(newdf)

   Unnamed: 0        Day  Temperature  windspeed  event
0           0 2020-01-01         32.0        6.0   Rain
1           1 2020-02-01          NaN        7.0  Sunny
2           2 2020-03-01         28.0        NaN   Snow
3           3 2020-04-01          NaN        7.0    NaN
4           4 2020-05-01         32.0        NaN   Rain
5           5 2020-06-01         31.0        3.0  Sunny
6           6 2020-06-01         34.0        5.0    NaN


In [27]:
newdf = df.fillna(method='ffill')
print(newdf)

   Unnamed: 0        Day  Temperature  windspeed  event
0           0 2020-01-01         32.0        6.0   Rain
1           1 2020-02-01         32.0        7.0  Sunny
2           2 2020-03-01         28.0        7.0   Snow
3           3 2020-04-01         28.0        7.0   Snow
4           4 2020-05-01         32.0        7.0   Rain
5           5 2020-06-01         31.0        3.0  Sunny
6           6 2020-06-01         34.0        5.0  Sunny


In [28]:
india_weather=pd.DataFrame({
    'city':['Mumai','Delhi','Banglore'],
    'temperature':[17,45,30],
    "humidity":[80,90,30]
})
print(india_weather)

       city  temperature  humidity
0     Mumai           17        80
1     Delhi           45        90
2  Banglore           30        30


In [29]:
usa_weather=pd.DataFrame({
    'city':['new york','chicago','orlando'],
    'temperature':[21,14,40],
    "humidity":[80,60,40]
})
print(usa_weather)

       city  temperature  humidity
0  new york           21        80
1   chicago           14        60
2   orlando           40        40


In [30]:
df= pd.concat([india_weather, usa_weather],ignore_index=True)
print(df)

       city  temperature  humidity
0     Mumai           17        80
1     Delhi           45        90
2  Banglore           30        30
3  new york           21        80
4   chicago           14        60
5   orlando           40        40


In [31]:
df= pd.concat([india_weather, usa_weather],keys=["india", "usa"])
print(df)

             city  temperature  humidity
india 0     Mumai           17        80
      1     Delhi           45        90
      2  Banglore           30        30
usa   0  new york           21        80
      1   chicago           14        60
      2   orlando           40        40


In [32]:
df = pd.Series(['run', 'walk', 'sit', 'stand'])
print(df)

0      run
1     walk
2      sit
3    stand
dtype: object


In [33]:
df = pd.concat([india_weather, usa_weather,df], axis=1)
newdf = df.fillna(method='ffill')
print(newdf)

       city  temperature  humidity      city  temperature  humidity      0
0     Mumai         17.0      80.0  new york         21.0      80.0    run
1     Delhi         45.0      90.0   chicago         14.0      60.0   walk
2  Banglore         30.0      30.0   orlando         40.0      40.0    sit
3  Banglore         30.0      30.0   orlando         40.0      40.0  stand


In [ ]:
from matplotlib import pyplot as plt
x=[1,2,3,4,5,6,7]
y=[58,51,52,48,37,49,45]
plt.xlabel('Day')
plt.ylabel('temperature')
plt.title('weather')
plt.plot(x,y,color='red', linewidth=5,linestyle='dotted')
plt.show()

In [ ]:
plt.plot(x,y,color='red', linewidth=1,marker='+', markersize=34,alpha=0.3)

In [ ]:
days = [1,2,3,4,5,6,7]
max_t = [32,45,33,56,55,43,23]
min_t = [33,22,32,4,44,56,54]
average_t=[33,34,45,44,23,35,32]
plt.xlabel("Days")
plt.ylabel("Temperature")
plt.plot(days,max_t,label="max")
plt.plot(days,min_t,label="min")
plt.plot(days,average_t,label="average")
plt.legend(loc="best", shadow=True, fontsize="large")
plt.grid()
plt.show()

In [ ]:
company = ['Google', 'Amazon', 'MSFT', 'FB']
revenue = [98,45,39,100]
plt.ylabel('revenue')
plt.title('US Tech Stocks')
plt.bar(company,revenue)
plt.show()

In [ ]:
company = ['Google', 'Amazon', 'MSFT', 'FB']
revenue = [98,45,39,100]
plt.xlabel('revenue')
plt.title('US Tech Stocks')
plt.barh(company,revenue)
plt.grid()
plt.show()

In [ ]:
sugar_men=[100,45,67,89,98,76,54,66,88,20]
sugar_women=[20,67,89,66,55,78,79,99,87,67]
plt.xlabel('sugar level')
plt.ylabel('Patient number')
plt.hist([sugar_men, sugar_women], bins=[40,60,80,100],rwidth=0.95,color=['green','yellow'],label=['men', 'women'])
plt.legend()
plt.grid()
plt.show()

In [ ]:
sugar_men=[100,45,67,89,98,76,54,66,88,20]
sugar_women=[20,67,89,66,55,78,79,99,87,67]
plt.ylabel('sugar level')
plt.xlabel('Patient number')
plt.hist([sugar_men, sugar_women], bins=[40,60,80,100],rwidth=0.95,color=['green','yellow'],label=['men', 'women'],orientation='horizontal')
plt.legend()
plt.grid()
plt.show()

In [ ]:
exp_vals = [1400,600,300,410,250]
exp_labels = ["Home Rent","Food","Phone/Internet bill", "car", "other utilities"]
plt.axis("equal")
plt.pie(exp_vals, labels=exp_labels,explode=[0.1,0,0,0,0.8],autopct='%1.2f%%')
plt.show()

In [1]:
from sklearn import linear_model
import numpy as np
import pandas as pd
df = pd.read_csv("homeprice.csv")
reg = linear_model.LinearRegression()
reg.fit(df[['area']],df.price)
reg.predict([[3300]])

array([628715.75342466])

In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
a = sns.load_dataset("sec_bhavdata_full.csv")
sns.replot(x="PREV_CLOSE"," OPEN_PRICE",data = a)

SyntaxError: positional argument follows keyword argument (<ipython-input-6-621c61ead85e>, line 5)

In [2]:
import pandas as pd
df = pd.read_csv("spam.csv",encoding='ISO-8859-1')
df

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]