In [1]:
import numpy as np

In [11]:
myarr = np.array([[3,6,32,7]])
print(myarr)

[[ 3  6 32  7]]


In [12]:
myarr[0,1]=45
print(myarr)

[[ 3 45 32  7]]


In [8]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])
print(listarray)

[[1 2 3]
 [5 8 5]
 [0 3 1]]


In [10]:
print(listarray.size)

9


In [13]:
lspace= np.linspace(1,5,12)
print(lspace)

[1.         1.36363636 1.72727273 2.09090909 2.45454545 2.81818182
 3.18181818 3.54545455 3.90909091 4.27272727 4.63636364 5.        ]


In [15]:
lsspace = np.linspace(1,50,10)
print(lsspace)

[ 1.          6.44444444 11.88888889 17.33333333 22.77777778 28.22222222
 33.66666667 39.11111111 44.55555556 50.        ]


In [18]:
emp = np.empty((4,6))
print(emp)

[[6.23042070e-307 1.86918699e-306 1.69121096e-306 1.78019082e-306
  7.56587585e-307 7.56593017e-307]
 [1.24610383e-306 1.24610723e-306 1.37962320e-306 1.29060871e-306
  2.22522597e-306 1.33511969e-306]
 [1.78022342e-306 1.05700345e-307 1.00132653e-307 8.01097889e-307
  1.78020169e-306 7.56601165e-307]
 [1.02359984e-306 1.15710088e-306 6.23056330e-307 1.33511562e-306
  6.89805151e-307 2.56765117e-312]]


In [19]:
emp_like = np.empty_like(lspace)
print(emp_like)

[1.         1.36363636 1.72727273 2.09090909 2.45454545 2.81818182
 3.18181818 3.54545455 3.90909091 4.27272727 4.63636364 5.        ]


In [20]:
ide = np.identity(45)
print(ide)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [21]:
rang = np.arange(99)
print(rang)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]


In [24]:
re = rang.reshape((3,33))
print(re)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56
  57 58 59 60 61 62 63 64 65]
 [66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89
  90 91 92 93 94 95 96 97 98]]


In [26]:
arr=re.ravel()
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]
(99,)


In [27]:
arr = np.array([[1,2,3],[2,3,4],[4,5,6]])
print(arr)

[[1 2 3]
 [2 3 4]
 [4 5 6]]


In [28]:
print(arr.T)

[[1 2 4]
 [2 3 5]
 [3 4 6]]


In [29]:
print(arr.flat)

In [30]:
print(arr.ndim)

2


In [32]:
print(arr.nbytes)

36


In [33]:
print(arr)

[[1 2 3]
 [2 3 4]
 [4 5 6]]


In [34]:
ar2 = np.array([[1,2,1],[3,1,1],[1,1,2]])
print(arr+ar2)

[[2 4 4]
 [5 4 5]
 [5 6 8]]


In [35]:
print(arr*ar2)

[[ 1  4  3]
 [ 6  3  4]
 [ 4  5 12]]


In [36]:
print(np.sqrt(arr))

[[1.         1.41421356 1.73205081]
 [1.41421356 1.73205081 2.        ]
 [2.         2.23606798 2.44948974]]


In [37]:
print(arr.sum())
print(arr.max())
print(arr.min())

30
6
1


In [40]:
print(np.where(arr>3))

(array([1, 2, 2, 2], dtype=int32), array([2, 0, 1, 2], dtype=int32))
