In [1]:
import numpy as np
np.__version__

'1.19.0'

In [2]:
array = np.array([range(i, i + 3) for i in [2, 4, 6]])
array

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [3]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.ones(10, dtype=float)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [7]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
np.random.random((3, 3))

array([[0.23019804, 0.9456191 , 0.87917691],
       [0.92632394, 0.1445697 , 0.6609151 ],
       [0.88029641, 0.5930561 , 0.93686165]])

In [10]:
np.random.normal(0, 1, (3, 3))

array([[ 0.02863834, -0.87021563, -0.50040606],
       [-0.60780569,  1.61094025,  1.05783017],
       [-0.23509473, -1.13423671,  0.28734952]])

In [11]:
np.random.randint(0, 10, (3, 3))

array([[1, 3, 9],
       [2, 5, 4],
       [0, 9, 6]])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.empty(3)

array([1., 1., 1.])

In [14]:
np.zeros(10, "int16")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [15]:
np.zeros(10, dtype= np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [16]:
import numpy as np
np.random.seed(0)
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [17]:


x3.size

60

In [18]:
x3.shape

(3, 4, 5)

In [19]:
x3.ndim

3

x1 = np.array([[3, 5, 2, 4],
        [7, 6, 8, 8],
        [1, 6, 7, 7]])
x1[0, 0] = 12
x1

In [20]:
x1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x1[2:8:2]

array([2, 4, 6])

In [21]:
x = np.array([
    [12, 5, 2, 4],
    [7, 6, 8, 8],
    [1, 6, 7, 7]
])
x[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [22]:
x2 = x[:2, :2]
x2

array([[12,  5],
       [ 7,  6]])

In [23]:
x2[0, 0] = 99
x2

array([[99,  5],
       [ 7,  6]])

In [24]:
x

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [25]:
x2 = x[:2, :2].copy()
x2[0, 0] = 42
x2

array([[42,  5],
       [ 7,  6]])

In [26]:
x

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [27]:
grid = np.arange(1, 10).reshape((3, 3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
x = np.array([1, 2, 3])
x.reshape((3, 1))


array([[1],
       [2],
       [3]])

In [29]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [30]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = np.concatenate([x, y])
z

array([1, 2, 3, 3, 2, 1])

In [31]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
np.concatenate([a, a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [32]:
x = np.array([1, 2, 3])
grid = np.array([
    [9, 8, 7],
    [6, 5, 4]
])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [33]:
x = np.array([
    [99], 
    [95]
])

In [34]:

np.hstack([grid, x])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 95]])

In [35]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])
x1, x2, x3 = np.split(x, [3, 5])
x1, x2, x3

(array([1, 2, 3]), array([99, 99]), array([3, 2, 1]))

In [36]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
upper, lower = np.vsplit(grid, [2])
lower, upper

(array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[0, 1, 2, 3],
        [4, 5, 6, 7]]))

In [38]:
left, right = np.hsplit(grid,[2])
left, right

(array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]))

In [39]:
grid + 2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [40]:
x = np.array([-2, -1, 0, 1, 2])
np.absolute(x)

array([2, 1, 0, 1, 2])

In [41]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [42]:
x

array([-2, -1,  0,  1,  2])

In [43]:
np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([2, 1, 0, 1, 2])

In [44]:
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [45]:
np.sin(theta)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [46]:
x = [1, 2, 3]
print(x)
print(np.exp(x))
print(np.exp2(x))
print(np.power(3, x))

[1, 2, 3]
[ 2.71828183  7.3890561  20.08553692]
[2. 4. 8.]
[ 3  9 27]


In [47]:
from scipy import special
x = [1, 5, 10]
special.gammaln(x)

array([ 0.        ,  3.17805383, 12.80182748])

In [48]:
print(special.gamma(x))
special.beta(x, 2)

[1.0000e+00 2.4000e+01 3.6288e+05]


array([0.5       , 0.03333333, 0.00909091])

In [49]:
x = np.array([0, 0.3, 0.7, 1.0])
print(special.erf(x))
print(special.erfc(x))
print(special.erfinv(x))

[0.         0.32862676 0.67780119 0.84270079]
[1.         0.67137324 0.32219881 0.15729921]
[0.         0.27246271 0.73286908        inf]


In [50]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out = y)

array([ 0., 10., 20., 30., 40.])

In [51]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [52]:
x = np.arange(1, 6)
print(np.add.reduce(x))
print(np.multiply.reduce(x))
print(np.add.accumulate(x))
print(np.multiply.accumulate(x))

15
120
[ 1  3  6 10 15]
[  1   2   6  24 120]


In [53]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [54]:
l = np.random.random(100)
sum(l)

52.12818058833704

In [55]:
big_array = np.random.random(10000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

4.61 s ± 1.85 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
23.4 ms ± 1.04 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [56]:
np.min(big_array), np.max(big_array)

(1.1260270338375733e-07, 0.9999999965285972)

In [57]:
m = np.random.random((3, 4))
m

array([[0.36619233, 0.67231693, 0.6872    , 0.95682063],
       [0.03624294, 0.47775347, 0.68651265, 0.31162055],
       [0.9196282 , 0.85243476, 0.06305651, 0.93223409]])

In [58]:
print(np.min(m, axis = 0))
print(np.max(m, axis = 1))

[0.03624294 0.47775347 0.06305651 0.31162055]
[0.95682063 0.68651265 0.93223409]


In [59]:
a = np.arange(3).reshape(3, 1)
b = np.arange(3)
a

array([[0],
       [1],
       [2]])

In [60]:
np.shape(a)

(3, 1)

In [61]:
np.shape(b)

(3,)

In [62]:
np.size(a)

3

In [63]:
m = np.ones((3, 2))
a = np.arange(3)
a[:, np.newaxis].shape

(3, 1)

In [64]:
np.logaddexp(m, a[:, np.newaxis])

array([[1.31326169, 1.31326169],
       [1.69314718, 1.69314718],
       [2.31326169, 2.31326169]])

In [65]:
x = np.array([1, 2, 3, 4, 5])
x < 3

array([ True,  True, False, False, False])

In [66]:
x != 3

array([ True,  True, False,  True,  True])

In [67]:
2 * x == x ** 2

array([False,  True, False, False, False])

In [68]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [69]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [71]:
np.count_nonzero(x < 6)

8

In [72]:
np.sum(x < 6, axis = 1)

array([4, 2, 2])

In [73]:
np.all(x > 6)

False

In [74]:
np.any(x > 6)

True

In [76]:
np.all(x < 8, axis=1)

array([ True, False,  True])

In [79]:
np.sum((x > 5) & (x < 9))

3

In [80]:
np.sum (~((x > 5) | (x >9)))

8

In [81]:
x[x < 5]

array([0, 3, 3, 3, 2, 4])

In [82]:
np.median(x)

4.5

In [83]:
np.min(x), np.max(x)

(0, 9)

In [84]:
import numpy as np
rand = np.random.RandomState(42)
x = rand.randint(100, size=10)
x

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [86]:
[x[3], x[7], x[2]]

[71, 86, 14]

In [87]:
ind = np.array([
    [3, 7],
    [4, 5]
])
x[ind]

array([[71, 86],
       [60, 20]])

In [89]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
x[row, col]

array([ 2,  5, 11])

In [92]:
x[row[:, np.newaxis], col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

In [93]:
row[:, np.newaxis] * col

array([[0, 0, 0],
       [2, 1, 3],
       [4, 2, 6]])

In [108]:
x = np.array([1, 2, 3])
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [103]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [104]:
x[2, [2, 0, 1]]

array([10,  8,  9])

In [105]:
x[1:, [2, 0, 1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

In [107]:
mask = np.array([1, 0, 1, 0], dtype=bool)
x[row[:, np.newaxis], mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [114]:
mean = [0, 0]
cov = [[1, 2], [2, 5]]
x = rand.multivariate_normal(mean, cov, 100)
x.shape

(100, 2)

In [115]:
indices = np.random.choice(x.shape[0], 20, replace=False)
indices

array([48, 28, 30, 98, 24, 54, 45, 85, 71, 39, 13, 67, 22, 89, 72, 83, 14,
       88, 59, 68])

In [117]:
selection = x[indices]
selection.shape

(20, 2)

In [118]:
x = np.arange(10)
i = np.array([2, 1, 8, 4])
x[i] = 99
x

array([ 0, 99, 99,  3, 99,  5,  6,  7, 99,  9])

In [119]:
x[i] -= 10
x

array([ 0, 89, 89,  3, 89,  5,  6,  7, 89,  9])

In [121]:
i = [2, 3, 3, 4, 4, 4]
x[i] += 1
x

array([ 0, 89, 91,  5, 91,  5,  6,  7, 89,  9])

In [122]:
x = np.zeros(10)
np.add.at(x, i, 1)
x

array([0., 0., 1., 2., 3., 0., 0., 0., 0., 0.])

In [131]:
bins = np.linspace(-5, 5, 20)
count = np.zeros_like(bins)
count

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [124]:
np.random.seed(42)
x = np.random.randn(100)
x

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
       -0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004,
       -0.46341769, -0.46572975,  0.24196227, -1.91328024, -1.72491783,
       -0.56228753, -1.01283112,  0.31424733, -0.90802408, -1.4123037 ,
        1.46564877, -0.2257763 ,  0.0675282 , -1.42474819, -0.54438272,
        0.11092259, -1.15099358,  0.37569802, -0.60063869, -0.29169375,
       -0.60170661,  1.85227818, -0.01349722, -1.05771093,  0.82254491,
       -1.22084365,  0.2088636 , -1.95967012, -1.32818605,  0.19686124,
        0.73846658,  0.17136828, -0.11564828, -0.3011037 , -1.47852199,
       -0.71984421, -0.46063877,  1.05712223,  0.34361829, -1.76304016,
        0.32408397, -0.38508228, -0.676922  ,  0.61167629,  1.03099952,
        0.93128012, -0.83921752, -0.30921238,  0.33126343,  0.97554513,
       -0.47917424, -0.18565898, -1.10633497, -1.19620662,  0.81252582,
        1.35624003, -0.07201012,  1.0035329 ,  0.36163603, -0.64

In [125]:
i = np.searchsorted(bins, x)
i

array([11, 10, 11, 13, 10, 10, 13, 11,  9, 11,  9,  9, 10,  6,  7,  9,  8,
       11,  8,  7, 13, 10, 10,  7,  9, 10,  8, 11,  9,  9,  9, 14, 10,  8,
       12,  8, 10,  6,  7, 10, 11, 10, 10,  9,  7,  9,  9, 12, 11,  7, 11,
        9,  9, 11, 12, 12,  8,  9, 11, 12,  9, 10,  8,  8, 12, 13, 10, 12,
       11,  9, 11, 13, 10, 13,  5, 12, 10,  9, 10,  6, 10, 11, 13,  9,  8,
        9, 12, 11,  9, 11, 10, 12,  9,  9,  9,  7, 11, 10, 10, 10],
      dtype=int32)

In [130]:
np.add.at(count, i, 1)
count

array([ 0.,  0.,  0.,  0.,  0.,  1.,  3.,  7.,  9., 23., 22., 17., 10.,
        7.,  1.,  0.,  0.,  0.,  0.,  0.])

In [133]:
def selection_sort(x):
    for i in range(len(x)):
        swap = i + np.argmin(x[i:])
        x[i] , x[swap] = x[swap], x[i]
    return x
x = np.array([2, 1, 4, 3, 5])
selection_sort(x)

array([1, 2, 3, 4, 5])

In [135]:
def bogosort(x):
    while np.any(x[:-1] > x[1:]):
        np.random.shuffle(x)
    return x
x = np.array([2, 1, 4, 3, 5])
bogosort(x)

array([1, 2, 3, 4, 5])

In [139]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [140]:
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
i 

array([1, 0, 3, 2, 4], dtype=int32)

In [141]:
rand = np.random.RandomState(42)
x = rand.randint(0, 10, (4, 6))
x

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [142]:
np.sort(x, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [143]:
np.sort(x, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [149]:
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 3)

array([2, 1, 3, 4, 6, 5, 7])

In [150]:
name = ["Alice", "Bob", "Cathy", "Doug"]
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'), 'formats':('U10', 'i4', 'f8')})
data.dtype

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [151]:
data['name'] = name
data['age'] = age
data['weight'] = weight
data

array([('Alice', 25, 55. ), ('Bob', 45, 85.5), ('Cathy', 37, 68. ),
       ('Doug', 19, 61.5)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [152]:
data[data['age'] < 30]['name']

array(['Alice', 'Doug'], dtype='<U10')

In [154]:
np.dtype('S10, i4, f8')

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

In [156]:
np.dtype({'names':('name' , 'age', 'weight'), 'formats':((np.str_, 10), int, np.float32)})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [157]:
tp = np.dtype([('id', 'i8'), ('mat', 'f8', (3, 3))])
x = np.zeros(1, dtype=tp)
print(x[0])
print(x['mat'][0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [158]:
data_rec = data.view(np.recarray)
data_rec.age

array([25, 45, 37, 19])

In [1]:
import numpy as np
a = np.array([[1, 2], [3, 4], [5, 6]])
np.compress([False, True, True], a, axis=0)

array([[3, 4],
       [5, 6]])

In [2]:
np.cumprod(a)

array([  1,   2,   6,  24, 120, 720], dtype=int32)

In [3]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [5]:
a.fill(0)
a

array([[0, 0],
       [0, 0],
       [0, 0]])

In [9]:
a = np.array([1 + 2j, 3 + 7j, 6 + 9j])
a.imag = np.array([1, 2, 3])
a

array([1.+1.j, 3.+2.j, 6.+3.j])

In [11]:
b = np.array([1, 2, 3])
np.put(b, 22, 6, mode="clip")
b

array([1, 2, 6])

In [12]:
a.real = 9
a

array([9.+1.j, 9.+2.j, 9.+3.j])

In [13]:
x = np.array([1, 2, 0])
y = np.array([4, 5, 6])
np.cross(x, y)


array([12, -6, -3])

In [15]:
a = np.array([
    [1, 3, 6],
    [3, 5, 7],
    [7, 8, 9]
])
a.transpose()

array([[1, 3, 7],
       [3, 5, 8],
       [6, 7, 9]])

In [16]:
array = np.array([
    [8, 1, 7],
    [4, 3, 9],
    [5, 2, 6]
])
np.apply_along_axis(sorted, 1, array)

array([[1, 7, 8],
       [3, 4, 9],
       [2, 5, 6]])

In [17]:
array = [np.nan, 4, 2, 3, 1]
np.nanargmin(array)

4

In [4]:
import numpy as np
a = np.arange(12).reshape(3, 4)
for i in np.nditer(a):
    print(i, end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 

In [5]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
b = a.T
b

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [9]:
for i in np.nditer(b):
    print(i, end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 

In [12]:
for i in np.nditer(a, order="F"):
    print(i, end=" ")

0 4 8 1 5 9 2 6 10 3 7 11 

In [14]:
for x in np.nditer(a, op_flags = ['readwrite']):
    x[...] = 5 * x
a

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [17]:
a = np.arange(12).reshape((3, 4))
print(a)
for x in np.nditer(a, flags = ['external_loop'], order = 'C'):
    print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [18]:
it = np.nditer(a, flags=['f_index'])
while not it.finished:
    print("%d <%d>"%(it[0], it.index), end=" ")
    it.iternext()

0 <0> 1 <3> 2 <6> 3 <9> 4 <1> 5 <4> 6 <7> 7 <10> 8 <2> 9 <5> 10 <8> 11 <11> 

In [20]:
b = np.array([5, 6, 7, 8])
for x, y in np.nditer([a, b]):
    print(x, ":", y, end=", ")

0 : 5, 1 : 6, 2 : 7, 3 : 8, 4 : 5, 5 : 6, 6 : 7, 7 : 8, 8 : 5, 9 : 6, 10 : 7, 11 : 8, 

In [21]:
y = 10
x = 11
print(np.bitwise_and(y, x))

10


In [22]:
a = np.array([2, 8, 125])
b = np.array([3, 3, 115])
a & b

array([  2,   0, 113], dtype=int32)

In [23]:
print(np.bitwise_or(a, b))

[  3  11 127]


In [24]:
np.bitwise_xor(a, b)

array([ 1, 11, 14], dtype=int32)

In [25]:
a >> 5

array([0, 0, 3], dtype=int32)

In [26]:
number = 10
np.binary_repr(number)

'1010'

In [32]:
z = np.array([
    [
        [1, 0, 1],
        [0, 1, 0]
    ],
    [
        [1, 1, 0],
        [0, 0, 1]
    ]
])
b = np.packbits(z, axis=-1)
b

array([[[160],
        [ 64]],

       [[192],
        [ 32]]], dtype=uint8)

In [34]:
a = np.array([[2], [7], [23]], dtype=np.uint8)
b = np.unpackbits(a, axis = 1)
b

array([[0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 0, 1, 1, 1]], dtype=uint8)

In [35]:
a = np.array([
    [6, 1, 1],
    [4, -2, 5],
    [2, 8, 7]
])
print(np.linalg.matrix_rank(a))
print(np.linalg.det(a))
print(np.trace(a))
print(np.linalg.inv(a))
print(np.linalg.matrix_power(a, 3))

3
-306.0
11
[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]
[[336 162 228]
 [406 162 469]
 [698 702 905]]


In [39]:
a = np.array([[1, -2j], [2j, 5]])
c, d = np.linalg.eigh(a)
c, d

(array([0.17157288, 5.82842712]),
 array([[-0.92387953+0.j        , -0.38268343+0.j        ],
        [ 0.        +0.38268343j,  0.        -0.92387953j]]))

In [40]:
product = np.dot(5, 4)
print(product)
vector_a = 2 + 3j
vector_b = 4 + 5j
product = np.dot(vector_a, vector_b)
print(product)

20
(-7+22j)


In [41]:
a = np.array([[1, 2], [3, 4]])
b = np.array([8, 18])
np.linalg.solve(a, b)

array([2., 3.])

In [44]:
a = [[1, 2, 3], [5, 6, 7], [3, 4, 6]]
np.linalg.eigh(a)

(array([-2.12426885,  2.36041703, 12.76385182]),
 array([[ 0.86539685,  0.24293108,  0.43826109],
        [-0.49533933,  0.54683177,  0.67499183],
        [-0.07567859, -0.80122375,  0.59355981]]))

In [46]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [48]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
arr

array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [50]:
arr = np.array([1, 2, 3, 4, 5])
np.random.permutation(arr)

array([1, 3, 4, 5, 2])

In [51]:
x = np.random.binomial(n=10, p=0.5, size=10)
x

array([6, 4, 8, 3, 3, 4, 5, 5, 6, 8])

In [53]:
x = np.random.poisson(lam=2, size=10)
x

array([2, 0, 1, 2, 2, 4, 1, 6, 3, 3])

In [55]:
x = np.random.uniform(size=(2, 3))
x

array([[0.85868476, 0.20277725, 0.64614688],
       [0.34905998, 0.47387122, 0.73019416]])

In [56]:
x = np.random.logistic(loc=1, scale=2, size=(2, 3))
x

array([[ -2.00818449,   8.18910793,  -0.05709885],
       [ -3.37705643,   2.14789735, -10.73230048]])

In [58]:
x = np.random.multinomial(n = 6, pvals=[1/6, 1/6, 1/6, 1/6, 1/6, 1/6])
x

array([1, 1, 3, 1, 0, 0])

In [59]:
x = np.random.exponential(scale = 2, size=(2, 3))
x

array([[0.26935993, 2.08878825, 0.0339677 ],
       [4.04522899, 6.55005885, 1.24386364]])

In [60]:
x = np.random.chisquare(df=2, size=(2, 3))
x

array([[0.51569469, 2.43271269, 0.50008027],
       [2.65280898, 4.66482667, 2.05707929]])

In [62]:
x = np.random.rayleigh(scale=2, size=(2, 3))
x

array([[3.03209206, 3.13661055, 3.61489742],
       [5.0375054 , 1.01326802, 0.74405268]])

In [63]:
x = np.random.pareto(a = 2, size=(2, 3))
x

array([[1.04265149, 1.60751848, 3.12345355],
       [0.16172414, 0.02505317, 0.01242165]])

In [64]:
x = np.random.zipf(a=2, size=(2, 3))
x

array([[1, 3, 2],
       [1, 1, 5]])

In [66]:
x = np.array([3, 6, 9])
x = np.lcm.reduce(x)
x

18

In [68]:
x = np.array([20, 8, 32, 36, 16])
x = np.gcd.reduce(x)
x

4

In [69]:
arr = np.array([1, 1, 1, 2, 2, 3, 3, 4, 6, 7])
np.unique(arr)

array([1, 2, 3, 4, 6, 7])

In [76]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
np.setxor1d(arr1, arr2)

array([1, 2, 5, 6])

In [22]:
df = pd.read_csv("https://raw.githubusercontent.com/PacktPublishing/Hands-on-Exploratory-Data-Analysis-with-Python/master/Chapter%207/automobile.csv")
df.head()

symboling normalized-losses         make fuel-type aspiration num-of-doors  \
0          3                 ?  alfa-romero       gas        std          two   
1          3                 ?  alfa-romero       gas        std          two   
2          1                 ?  alfa-romero       gas        std          two   
3          2               164         audi       gas        std         four   
4          2               164         audi       gas        std         four   

    body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
0  convertible          rwd           front        88.6  ...          130   
1  convertible          rwd           front        88.6  ...          130   
2    hatchback          rwd           front        94.5  ...          152   
3        sedan          fwd           front        99.8  ...          109   
4        sedan          4wd           front        99.4  ...          136   

   fuel-system  bore  stroke compression-ratio horsepower  peak-rpm city-mpg  \
0         mpfi  3.47    2.68               9.0        111      5000       21   
1         mpfi  3.47    2.68               9.0        111      5000       21   
2         mpfi  2.68    3.47               9.0        154      5000       19   
3         mpfi  3.19     3.4              10.0        102      5500       24   
4         mpfi  3.19     3.4               8.0        115      5500       18   

  highway-mpg  price  
0          27  13495  
1          27  16500  
2          26  16500  
3          30  13950  
4          22  17450  

[5 rows x 26 columns]

In [23]:
df.shape

(205, 26)

In [24]:
df.to_csv("automobile.csv", index=False)

In [3]:
import numpy as np

In [5]:
z = np.random.rand(25, 25)
z.shape

(25, 25)

In [6]:
z.std()

0.28438070426028705

In [7]:
z.mean()

0.49037260429786056