In [75]:
import torch
import numpy as np

In [4]:
tensor = torch.ones((2,))
data = [[0, 1], [2, 3]]
tensor.new_tensor(data)

tensor([[0., 1.],
        [2., 3.]])

In [5]:
tensor.new_full((3, 4), 3.141592)

tensor([[3.1416, 3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416, 3.1416]])

In [6]:
tensor.new_empty(2, 3)

tensor([[8.1763e-19, 4.5914e-41, 8.1763e-19],
        [4.5914e-41, 8.1763e-19, 4.5914e-41]])

In [7]:
tensor.new_ones((2, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
tensor.new_zeros((2, 3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
x = torch.randn(4, dtype=torch.cfloat)
x.real

tensor([-1.7403,  1.3484,  0.4774,  0.0943])

In [10]:
x.imag

tensor([-0.2667, -0.5747, -0.2328,  0.3867])

In [12]:
a = torch.zeros(3, 3)
a.fill_diagonal_(5)

tensor([[5., 0., 0.],
        [0., 5., 0.],
        [0., 0., 5.]])

In [13]:
x = torch.tensor([[1], [2], [3]])
print(x.size())
x.expand(3, 4)

torch.Size([3, 1])


tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])

In [14]:
a = torch.randn(3)
torch.mul(a, 100)

tensor([-13.8011,  69.9816, -77.2708])

In [16]:
x = torch.tensor([float('nan'), float('nan'), -float('nan'), 3.14])
torch.nan_to_num(x)

tensor([0.0000, 0.0000, 0.0000, 3.1400])

In [17]:
x = torch.ones(5, 3)
t = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float)
index = torch.tensor([0, 4, 2])
x.index_add_(0, index, t)

tensor([[ 2.,  3.,  4.],
        [ 1.,  1.,  1.],
        [ 8.,  9., 10.],
        [ 1.,  1.,  1.],
        [ 5.,  6.,  7.]])

In [18]:
x = torch.zeros(5, 3)
t = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float)
index = torch.tensor([0, 4, 2])
x.index_copy_(0, index, t)

tensor([[1., 2., 3.],
        [0., 0., 0.],
        [7., 8., 9.],
        [0., 0., 0.],
        [4., 5., 6.]])

In [19]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
index = torch.tensor([0, 2])
x.index_fill_(1, index, -1)

tensor([[-1,  2, -1],
        [-1,  5, -1],
        [-1,  8, -1]])

In [20]:
a = torch.rand(10, requires_grad=True)
a.is_leaf

True

In [21]:
x = torch.tensor([1.0])
x.item()

1.0

In [22]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x.narrow(0, 0, 2))
print(x.narrow(1, 1, 2))

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[2, 3],
        [5, 6],
        [8, 9]])


In [23]:
src = torch.tensor([[4, 3, 5], [6, 7, 8]])
src.put_(torch.tensor([1, 3]), torch.tensor([9, 10]))

tensor([[ 4,  9,  5],
        [10,  7,  8]])

In [24]:
v = torch.tensor([0., 0., 0.], requires_grad=True)
h = v.register_hook(lambda grad: grad * 2)
v.backward(torch.tensor([1, 2, 3]))
print(v.grad)
h.remove()

tensor([2., 4., 6.])


In [25]:
x = torch.tensor([1, 2, 3])
print(x.repeat(4, 2))
print(x.repeat(4, 2, 1).size())

tensor([[1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3]])
torch.Size([4, 2, 3])


In [27]:
x = torch.tensor([[1, 2], [3, 4], [5, 6]])
x.resize_(2, 2)

tensor([[1, 2],
        [3, 4]])

In [28]:
src = torch.arange(1, 11).reshape((2, 5))
index = torch.tensor([[0, 1, 2, 0]])
torch.zeros(3, 5, dtype=src.dtype).scatter_(0, index, src)

tensor([[1, 0, 0, 4, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0]])

In [29]:
src = torch.ones((2, 5))
index = torch.tensor([[0, 1, 2, 0, 0]])
torch.zeros(3, 5, dtype=src.dtype).scatter_add_(0, index, src)

tensor([[1., 0., 0., 1., 1.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])

In [30]:
nse = 5
dims = (5, 5, 2, 2)
I = torch.cat([torch.randint(0, dims[0], size=(nse, )), torch.randint(0, dims[1], size=(nse,))], 0).reshape(2, nse)
V = torch.randn(nse, dims[2], dims[3])
S = torch.sparse_coo_tensor(I, V, dims).coalesce()
D = torch.randn(dims)
D.sparse_mask(S)

tensor(indices=tensor([[0, 1, 2, 3, 3],
                       [3, 3, 4, 3, 4]]),
       values=tensor([[[ 0.9443, -1.4943],
                       [ 1.0882,  0.2455]],

                      [[ 0.9695, -0.9975],
                       [-1.4436, -0.0160]],

                      [[ 0.5771,  1.6187],
                       [-1.4719,  0.8282]],

                      [[ 0.6463, -0.1666],
                       [-1.2128, -1.1834]],

                      [[ 1.0901,  0.1475],
                       [ 0.2947,  0.5526]]]),
       size=(5, 5, 2, 2), nnz=5, layout=torch.sparse_coo)

In [31]:
x = torch.tensor([1, 2, 3, 4, 5])
print(x.storage_offset())
x[3:].storage_offset()

0


3

In [32]:
x.storage()

 1
 2
 3
 4
 5
[torch.LongStorage of size 5]

In [33]:
x.storage_type()

torch.LongStorage

In [34]:
x = torch.tensor([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(x.stride())
print(x.stride(0))
print(x.stride(-1))

(5, 1)
5
1


In [35]:
x.stride(-2)

5

In [36]:
a = torch.randn(2, 2)
a.tolist()

[[0.9553726315498352, 0.8489100933074951],
 [0.33561378717422485, -0.7141163945198059]]

In [37]:
d = torch.tensor([[0, 0, 0], [9, 0, 10], [0, 0, 0]])
d.to_sparse()

tensor(indices=tensor([[1, 1],
                       [0, 2]]),
       values=tensor([ 9, 10]),
       size=(3, 3), nnz=2, layout=torch.sparse_coo)

In [38]:
torch.tensor([3, 4])

tensor([3, 4])

In [39]:
def exp_reducer(x):
    return x.exp().sum(dim=1)
inputs = torch.rand(2, 2)
torch.autograd.functional.jacobian(exp_reducer, inputs)

tensor([[[2.6912, 1.8653],
         [0.0000, 0.0000]],

        [[0.0000, 0.0000],
         [1.3365, 2.5620]]])

In [41]:
torch.autograd.functional.jacobian(exp_reducer, inputs, create_graph=True)

tensor([[[2.6912, 1.8653],
         [0.0000, 0.0000]],

        [[0.0000, 0.0000],
         [1.3365, 2.5620]]], grad_fn=<ViewBackward>)

In [42]:
def exp_adder(x, y):
    return 2 * x.exp() + 3 * y
inputs = (torch.rand(2), torch.rand(2))
torch.autograd.functional.jacobian(exp_adder, inputs)

(tensor([[5.0745, 0.0000],
         [0.0000, 4.9248]]),
 tensor([[3., 0.],
         [0., 3.]]))

In [44]:
def pow_reducer(x):
    return x.pow(3).sum()
inputs = torch.rand(2, 2)
torch.autograd.functional.hessian(pow_reducer, inputs)

tensor([[[[3.9163, 0.0000],
          [0.0000, 0.0000]],

         [[0.0000, 0.4943],
          [0.0000, 0.0000]]],


        [[[0.0000, 0.0000],
          [1.6688, 0.0000]],

         [[0.0000, 0.0000],
          [0.0000, 0.7788]]]])

In [46]:
torch.autograd.functional.hessian(pow_reducer, inputs, create_graph=True)

tensor([[[[3.9163, 0.0000],
          [0.0000, 0.0000]],

         [[0.0000, 0.4943],
          [0.0000, 0.0000]]],


        [[[0.0000, 0.0000],
          [1.6688, 0.0000]],

         [[0.0000, 0.0000],
          [0.0000, 0.7788]]]], grad_fn=<ViewBackward>)

In [47]:
def pow_adder_reducer(x, y):
    return (2 * x.pow(2) + 3 * y.pow(2)).sum()
inputs = (torch.rand(2), torch.rand(2))
torch.autograd.functional.hessian(pow_adder_reducer, inputs)

((tensor([[4., 0.],
          [0., 4.]]),
  tensor([[0., 0.],
          [0., 0.]])),
 (tensor([[0., 0.],
          [0., 0.]]),
  tensor([[6., 0.],
          [0., 6.]])))

In [49]:
def exp_reducer(x):
    return x.exp().sum(dim=1)
inputs = torch.rand(4, 4)
v = torch.ones(4)
torch.autograd.functional.vjp(exp_reducer, inputs, v)

(tensor([7.2699, 8.5261, 5.8531, 7.1571]),
 tensor([[2.1665, 1.8535, 1.6767, 1.5733],
         [1.7948, 2.1881, 1.9738, 2.5695],
         [1.6397, 1.5715, 1.4887, 1.1532],
         [2.1108, 1.6465, 1.3661, 2.0338]]))

In [50]:
torch.autograd.functional.vjp(exp_reducer, inputs, v, create_graph=True)

(tensor([7.2699, 8.5261, 5.8531, 7.1571], grad_fn=<SumBackward1>),
 tensor([[2.1665, 1.8535, 1.6767, 1.5733],
         [1.7948, 2.1881, 1.9738, 2.5695],
         [1.6397, 1.5715, 1.4887, 1.1532],
         [2.1108, 1.6465, 1.3661, 2.0338]], grad_fn=<MulBackward0>))

In [51]:
def adder(x, y):
    return 2 * x + 3 * y
inputs = (torch.rand(2), torch.rand(2))
v = torch.ones(2)
torch.autograd.functional.vjp(adder, inputs, v)

(tensor([1.1497, 1.2683]), (tensor([2., 2.]), tensor([3., 3.])))

In [52]:
def exp_reducer(x):
    return x.exp().sum(dim=1)
inputs = torch.rand(4, 4)
v = torch.ones(4, 4)
torch.autograd.functional.jvp(exp_reducer, inputs, v)

(tensor([7.2048, 8.7471, 7.7856, 7.4696]),
 tensor([7.2048, 8.7471, 7.7856, 7.4696]))

In [53]:
torch.autograd.functional.jvp(exp_reducer, inputs, v, create_graph=True)

(tensor([7.2048, 8.7471, 7.7856, 7.4696], grad_fn=<SumBackward1>),
 tensor([7.2048, 8.7471, 7.7856, 7.4696], grad_fn=<SqueezeBackward1>))

In [55]:
def adder(x, y):
    return 2 * x + 3 * y
inputs = (torch.rand(2), torch.rand(2))
v = (torch.ones(2), torch.ones(2))
torch.autograd.functional.jvp(adder, inputs, v)

(tensor([2.6025, 1.6639]), tensor([5., 5.]))

In [56]:
def pow_reducer(x):
    return x.pow(3).sum()
inputs = torch.rand(2, 2)
v = torch.ones(2, 2)
torch.autograd.functional.vhp(pow_reducer, inputs, v)

(tensor(1.0028),
 tensor([[1.8340, 0.5826],
         [5.9434, 0.6685]]))

In [57]:
torch.autograd.functional.vhp(pow_reducer, inputs, v, create_graph=True)

(tensor(1.0028, grad_fn=<SumBackward0>),
 tensor([[1.8340, 0.5826],
         [5.9434, 0.6685]], grad_fn=<MulBackward0>))

In [58]:
def pow_adder_reducer(x, y):
    return (2 * x.pow(2) + 3 * y.pow(2)).sum()
inputs = (torch.rand(2), torch.rand(2))
v = (torch.zeros(2), torch.ones(2))
torch.autograd.functional.vhp(pow_adder_reducer, inputs, v)

(tensor(3.2046), (tensor([0., 0.]), tensor([6., 6.])))

In [60]:
def pow_reducer(x):
    return x.pow(3).sum()
inputs = torch.rand(2, 2)
v = torch.ones(2, 2)
torch.autograd.functional.hvp(pow_reducer, inputs, v)

(tensor(1.4239),
 tensor([[2.9254, 5.6006],
         [1.0837, 4.7264]]))

In [61]:
torch.autograd.functional.hvp(pow_reducer, inputs, v, create_graph=True)

(tensor(1.4239, grad_fn=<SumBackward0>),
 tensor([[2.9254, 5.6006],
         [1.0837, 4.7264]], grad_fn=<MulBackward0>))

In [62]:
def pow_adder_reducer(x, y):
    return (2 * x.pow(2) + 3 * y.pow(2)).sum()
inputs = (torch.rand(2), torch.rand(2))
v = (torch.zeros(2), torch.ones(2))
torch.autograd.functional.hvp(pow_adder_reducer, inputs, v)

(tensor(5.5389), (tensor([0., 0.]), tensor([6., 6.])))

In [66]:
x = torch.tensor([1.], requires_grad=True)
with torch.no_grad():
    y = x * 2
print(y.requires_grad)


False


In [67]:
x = torch.tensor([1.], requires_grad=True)
with torch.no_grad():
    with torch.enable_grad():
        y = x * 2
print(y.requires_grad)
y.backward()
x.grad
@torch.enable_grad()
def doubler(x):
    return x * 2
with torch.no_grad():
    z = doubler(x)
z.requires_grad

True


True

In [68]:
x = torch.tensor([1.], requires_grad=True)
is_train = False
with torch.set_grad_enabled(is_train):
    y = x * 2
print(y.requires_grad)
torch.set_grad_enabled(True)
y = x * 2
print(y.requires_grad)
torch.set_grad_enabled(False)
y = x * 2
y.requires_grad

False
True


False

In [69]:
x = torch.ones(1, 2, 3, requires_grad=True)
with torch.inference_mode():
    y = x * x
print(y.requires_grad)
@torch.inference_mode()
def func(x):
    return x * x
out = func(x)
out.requires_grad

False


False

In [72]:
x = torch.randn((1, 1), requires_grad=True)
with torch.autograd.profiler.profile() as prof:
    for _ in range(100):
        y = x ** 2
print(prof.key_averages().table(sort_by="self_cpu_time_total"))

---------------------  ------------  ------------  ------------  ------------  ------------  ------------  
                 Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg    # of Calls  
---------------------  ------------  ------------  ------------  ------------  ------------  ------------  
            aten::pow        74.50%       1.625ms       100.00%       2.181ms      21.813us           100  
    aten::result_type        15.10%     329.300us        15.10%     329.300us       1.646us           200  
             aten::to        10.40%     226.900us        10.40%     226.900us       2.269us           100  
---------------------  ------------  ------------  ------------  ------------  ------------  ------------  
Self CPU time total: 2.181ms



In [2]:
import torch.distributed as dist
from datetime import timedelta
store = dist.TCPStore("127.0.0.1", 0, 1, True, timedelta(seconds=30))
store.add("first_key", 1)
store.add("first_key", 6)
store.get("first_key")

b'7'

In [3]:
store = dist.TCPStore("127.0.0.1", 0, 1, True, timedelta(seconds=30))
store.set("key", "first_value")
store.compare_set("key", "first_value", "second_value")
store.get("key")

b'second_value'

In [8]:
stores = dist.TCPStore("127.0.0.1", 0, 1, True, timedelta(seconds=30))
stores.set("first_key", "first_value")
stores.num_keys()

2

In [11]:
store = dist.TCPStore("127.0.0.1", 0, 1, True, timedelta(seconds=30))
store.set("first_key", "first_value")
store.delete_key("first_key")
store.delete_key("bad_key")

False

In [2]:
m = torch.distributions.bernoulli.Bernoulli(torch.tensor([0.3]))
m.sample()

tensor([0.])

In [4]:
m = torch.distributions.beta.Beta(torch.tensor([0.5]), torch.tensor([0.5]))
m.sample()

tensor([0.6360])

In [5]:
m = torch.distributions.Binomial(torch.tensor([[5.], [10.]]), torch.tensor([0.5, 0.8]))
m.sample()

tensor([[2., 4.],
        [2., 8.]])

In [6]:
m = torch.distributions.categorical.Categorical(torch.tensor([0.25, 0.25, 0.25, 0.25]))
m.sample()

tensor(0)

In [10]:
m = torch.distributions.cauchy.Cauchy(torch.tensor([0.0]), torch.tensor([1.0]))
m.sample(torch.tensor([5]))

tensor([[ 2.7839],
        [-8.1600],
        [-3.3887],
        [-0.4450],
        [ 0.2681]])

In [11]:
m = torch.distributions.chi2.Chi2(torch.tensor([1.0]))
m.sample()

tensor([0.6199])

In [12]:
m = torch.distributions.continuous_bernoulli.ContinuousBernoulli(torch.tensor([0.3]))
m.sample()

tensor([0.5926])

In [13]:
m = torch.distributions.dirichlet.Dirichlet(torch.tensor([0.5, 0.5]))
m.sample()

tensor([0.8366, 0.1634])

In [14]:
m = torch.distributions.exponential.Exponential(torch.tensor([1.0]))
m.sample()

tensor([0.3474])

In [15]:
m = torch.distributions.fishersnedecor.FisherSnedecor(torch.tensor([2.0]), torch.tensor([2.0]))
m.sample()

tensor([0.0596])

In [16]:
m = torch.distributions.gamma.Gamma(torch.tensor([1.0]), torch.tensor([1.0]))
m.sample()

tensor([1.6926])

In [17]:
m = torch.distributions.geometric.Geometric(torch.tensor([0.3]))
m.sample()

tensor([4.])

In [18]:
m = torch.distributions.gumbel.Gumbel(torch.tensor([1.0]), torch.tensor([2.0]))
m.sample()

tensor([-2.5936])

In [19]:
m = torch.distributions.half_cauchy.HalfCauchy(torch.tensor([1.0]))
m.sample()

tensor([2.3153])

In [20]:
m = torch.distributions.half_normal.HalfNormal(torch.tensor([1.0]))
m.sample()

tensor([1.4291])

In [21]:
loc = torch.zeros(3)
scale = torch.ones(3)
normal = torch.distributions.normal.Normal(loc, scale)
print([normal.batch_shape, normal.event_shape])
diagn = torch.distributions.independent.Independent(normal, 1)
[diagn.batch_shape, diagn.event_shape]

[torch.Size([3]), torch.Size([])]


[torch.Size([]), torch.Size([3])]

In [23]:
m = torch.distributions.kumaraswamy.Kumaraswamy(torch.tensor([1.0]), torch.tensor([1.0]))
m.sample()

tensor([0.2266])

In [26]:
m = torch.distributions.lkj_cholesky.LKJCholesky(3, 0.5)
m.sample()

tensor([[ 1.0000,  0.0000,  0.0000],
        [ 0.8650,  0.5017,  0.0000],
        [-0.3346, -0.8003,  0.4976]])

In [27]:
m = torch.distributions.laplace.Laplace(torch.tensor([0.0]), torch.tensor([1.0]))
m.sample()

tensor([5.0860])

In [29]:
m = torch.distributions.log_normal.LogNormal(torch.tensor([0.0]), torch.tensor([1.0]))
m.sample()

tensor([0.2379])

In [34]:
m = torch.distributions.lowrank_multivariate_normal.LowRankMultivariateNormal(torch.zeros(2), 
                                                                              torch.tensor([[1.], [0.]]), torch.ones(2))
m.sample()

tensor([ 0.4133, -0.6794])

In [38]:
mix = torch.distributions.categorical.Categorical(torch.ones(5, ))
comp = torch.distributions.normal.Normal(torch.randn(5, ), torch.rand(5,))
gmm = torch.distributions.mixture_same_family.MixtureSameFamily(mix, comp)

In [39]:
m = torch.distributions.multinomial.Multinomial(100, torch.tensor([1., 1., 1., 1.]))
m.sample()

tensor([23., 24., 24., 29.])

In [40]:
m = torch.distributions.multivariate_normal.MultivariateNormal(torch.zeros(2), torch.eye(2))
m.sample()

tensor([ 0.3467, -0.1596])

In [41]:
m = torch.distributions.normal.Normal(torch.tensor([0.0]), torch.tensor([1.0]))
m.sample()

tensor([1.5626])

In [42]:
m = torch.distributions.one_hot_categorical.OneHotCategorical(torch.tensor([0.25, 0.25, 0.25, 0.25]))
m.sample()

tensor([0., 0., 0., 1.])

In [45]:
m = torch.distributions.pareto.Pareto(torch.tensor([1.0]), torch.tensor([1.0]))
m.sample()

tensor([3.5552])

In [47]:
m = torch.distributions.poisson.Poisson(torch.tensor([4.]))
m.sample()

tensor([2.])

In [55]:
m = torch.distributions.studentT.StudentT(torch.tensor([2.0]))
m.sample()

tensor([-1.4547])

In [57]:
m = torch.distributions.uniform.Uniform(torch.tensor([0.0]), torch.tensor([5.0]))
m.sample()

tensor([4.1212])

In [58]:
m = torch.distributions.von_mises.VonMises(torch.tensor([1.0]), torch.tensor([1.0]))
m.sample()

tensor([1.1578])

In [60]:
m = torch.distributions.weibull.Weibull(torch.tensor([1.0]), torch.tensor([1.0]))
m.sample()

tensor([0.7256])

In [62]:
t = torch.arange(4)
torch.fft.fft(t)

tensor([ 6.+0.j, -2.+2.j, -2.+0.j, -2.-2.j])

In [64]:
t = torch.tensor([6. + 0.j, -2.+2.j, -2 + 0.j, -2.-2.j])
torch.fft.ifft(t)

tensor([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j])

In [66]:
x = torch.rand(10, 10, dtype=torch.complex64)
fft2 = torch.fft.fft2(x)
two_ffts = torch.fft.fft(torch.fft.fft(x, dim=0), dim=1)
torch.testing.assert_close(fft2, two_ffts, check_stride=False)

In [67]:
x = torch.rand(10, 10, dtype=torch.complex64)
fft2 = torch.fft.ifft2(x)
two_ffts = torch.fft.ifft(torch.fft.ifft(x, dim=0), dim=1)
torch.testing.assert_close(fft2, two_ffts, check_stride=False)

In [68]:
x = torch.rand(10, 10, dtype=torch.complex64)
fft2 = torch.fft.fftn(x)
two_ffts = torch.fft.fft(torch.fft.fft(x, dim=0), dim=1)
torch.testing.assert_close(fft2, two_ffts, check_stride=False)

In [69]:
x = torch.rand(10, 10, dtype=torch.complex64)
fft2 = torch.fft.ifftn(x)
two_ffts = torch.fft.ifft(torch.fft.ifft(x, dim=0), dim=1)
torch.testing.assert_close(fft2, two_ffts, check_stride=False)

In [70]:
t = torch.arange(4)
torch.fft.rfft(t)

tensor([ 6.+0.j, -2.+2.j, -2.+0.j])

In [71]:
t = torch.linspace(0, 1, 5)
T = torch.fft.rfft(t)
torch.fft.irfft(T)

tensor([0.1562, 0.3511, 0.7812, 1.2114])

In [72]:
t = torch.rand(10, 10)
rfft2 = torch.fft.rfft2(t)
rfft2.size()

torch.Size([10, 6])

In [73]:
t = torch.rand(10, 9)
T = torch.fft.rfft2(t)
roundtrip = torch.fft.irfft2(T, t.size())
torch.testing.assert_close(roundtrip, t, check_stride=False)

In [74]:
t = torch.rand(10, 10)
rfftn = torch.fft.rfftn(t)
rfftn.size()

torch.Size([10, 6])

In [75]:
t = torch.rand(10, 9)
T = torch.fft.rfft(t)
torch.fft.irfftn(T).size()

torch.Size([10, 8])

In [76]:
t = torch.linspace(0, 1, 5)
T = torch.fft.ifft(t)
torch.fft.hfft(T[:3], n=5)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

In [77]:
t = torch.arange(5)
torch.fft.ihfft(t)

tensor([ 2.0000+-0.0000j, -0.5000-0.6882j, -0.5000-0.1625j])

In [82]:
torch.fft.fftfreq(5)

tensor([ 0.0000,  0.2000,  0.4000, -0.4000, -0.2000])

In [83]:
torch.fft.rfftfreq(5)

tensor([0.0000, 0.2000, 0.4000])

In [84]:
f = torch.fft.fftfreq(4)
f

tensor([ 0.0000,  0.2500, -0.5000, -0.2500])

In [88]:
shift = torch.fft.fftshift(f)
shift

tensor([-0.5000, -0.2500,  0.0000,  0.2500])

In [90]:
torch.fft.ifftshift(shift)

tensor([ 0.0000,  0.2500, -0.5000, -0.2500])

In [92]:
def callback(fut):
    print(f"This will run after the future has finished.")
    print(fut.wait())
fut = torch.futures.Future()
fut.add_done_callback(callback)
fut.set_result(5)

This will run after the future has finished.
5


In [2]:
fut = torch.futures.Future()
fut.set_exception(ValueError("foo"))
fut.wait()

ValueError: foo

In [3]:
import threading
import time
def slow_set_future(fut, value):
    time.sleep(0.5)
    fut.set_result(value)
fut = torch.futures.Future()
t = threading.Thread(target=slow_set_future, args=(fut, torch.ones(2) * 3))
t.start()
print(fut.wait())
t.join()

tensor([3., 3.])


In [4]:
def callback(fut):
    print(f"RPC return value is {fut.wait()}")
fut = torch.futures.Future()
cb_fut = fut.then(callback)
chain_cb_fut = cb_fut.then(lambda x: print(f"Chained cb done. {x.wait()}"))
fut.set_result(5)

RPC return value is 5
Chained cb done. None


In [6]:
fut0 = torch.futures.Future()
fut1 = torch.futures.Future()
fut = torch.futures.collect_all([fut0, fut1])
fut0.set_result(0)
fut1.set_result(1)
fut_list = fut.wait()
print(f"fut0 result = {fut_list[0].wait()}")
print(f"fut1 result = {fut_list[1].wait()}")

fut0 result = 0
fut1 result = 1


In [8]:
import torch
class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.param = torch.nn.Parameter(torch.rand(3, 4))
        self.linear = torch.nn.Linear(4, 5)
    def forward(self, x):
        return self.linear(x + self.param).clamp(min=0, max=1.0)
module = MyModule()
from torch.fx import symbolic_trace
symbolic_traced : torch.fx.GraphModule = symbolic_trace(module)
print(symbolic_traced.graph)
print(symbolic_traced.code)

graph():
    %x : [#users=1] = placeholder[target=x]
    %param : [#users=1] = get_attr[target=param]
    %add : [#users=1] = call_function[target=operator.add](args = (%x, %param), kwargs = {})
    %linear : [#users=1] = call_module[target=linear](args = (%add,), kwargs = {})
    %clamp : [#users=1] = call_method[target=clamp](args = (%linear,), kwargs = {min: 0, max: 1.0})
    return clamp

def forward(self, x):
    param = self.param
    add = x + param;  x = param = None
    linear = self.linear(add);  add = None
    clamp = linear.clamp(min = 0, max = 1.0);  linear = None
    return clamp
    


In [9]:
import torch
import torch.fx
class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.param = torch.nn.Parameter(torch.rand(3, 4))
        self.linear = torch.nn.Linear(4, 5)
    def forward(self, x):
        return torch.topk(torch.sum(self.linear(x + self.linear.weight).relu(), dim=-1), 3)
m = MyModule()
gm = torch.fx.symbolic_trace(m)
gm.graph.print_tabular()

opcode         name           target                                                       args                kwargs
-------------  -------------  -----------------------------------------------------------  ------------------  -----------
placeholder    x              x                                                            ()                  {}
get_attr       linear_weight  linear.weight                                                ()                  {}
call_function  add            <built-in function add>                                      (x, linear_weight)  {}
call_module    linear         linear                                                       (add,)              {}
call_method    relu           relu                                                         (linear,)           {}
call_function  sum_1          <built-in method sum of type object at 0x00007FFCC77455E0>   (relu,)             {'dim': -1}
call_function  topk           <built-in method topk of type object

In [2]:
torch.tensor([3])

tensor([3])

In [5]:
import torch
from typing import Tuple
from typing import Any
@torch.jit.export
def inc_first_element(x: Tuple[int, Any]):
    return (x[0] + 1, x[1])
m = torch.jit.script(inc_first_element)
print(m((1, 2.0)))
print(m((1, (100, 200))))

(2, 2.0)
(2, (100, 200))


In [8]:
import torch
from typing import Any
def s(a:Any):
    print(a)
    return (isinstance(a, torch.Tensor))
ones = torch.ones([2])
m = torch.jit.script(s)
print(m(ones))

 1
 1
[ CPUFloatType{2} ]
True


In [10]:
from typing import NamedTuple
from typing import Tuple
class MyTuple(NamedTuple):
    first: int
    second: int
def inc(x: MyTuple)->Tuple[int, int]:
    return (x.first+1, x.second+1)
t = MyTuple(first=1, second=2)
script_inc = torch.jit.script(inc)
print("TorchScript", script_inc(t))

TorchScript (2, 3)


In [11]:
from typing import NamedTuple
from typing import Tuple
from collections import namedtuple
_AnnotatedNamedTuple = NamedTuple('_NamedTupleAnnotated', [("first", int), ("second", int)])
_UnannotatedNamedTuple = namedtuple('_NamedTupleAnnotated', ['first', 'second'])
def inc(x:_AnnotatedNamedTuple)->Tuple[int, int]:
    return (x.first + 1, x.second + 1)
m = torch.jit.script(inc)
print(inc(_UnannotatedNamedTuple(1, 2)))

(2, 3)


In [16]:
class TestModule(torch.nn.Module):
    def __init__(self, v):
        super().__init__()
        self.x = v
    def forward(self, inc: int):
        return self.x + inc
m = torch.jit.script(TestModule(1))
print("First instance:", m(3))
m = torch.jit.script(TestModule(torch.ones([5])))
print(f"Second instance: {m(3)}")

First instance: 4
Second instance: tensor([4., 4., 4., 4., 4.])


In [29]:
class MyModule(torch.nn.Module):
    def __init__(self, N, M):
        super(MyModule, self).__init__()
        self.weight = torch.nn.Parameter(torch.rand(N, M))
        self.linear = torch.nn.Linear(N, M)
    def forward(self, input):
        output = self.weight.mv(input)
        output = self.linear(output)
        return output
scripted_module = torch.jit.script(MyModule(2, 3))

In [31]:
import torch
import torch.nn as nn
import torch.nn.functional as F
class MyModule(nn.Module):
    def __init__(self):
        super(MyModule, self).__init__()
        self.conv1 = torch.jit.trace(nn.Conv2d(1, 20, 5), torch.rand(1, 1, 16, 16))
        self.conv2 = torch.jit.trace(nn.Conv2d(20, 20, 5), torch.rand(1, 20, 16, 16))
    def forward(self, input):
        input = F.relu(self.conv1(input))
        input = F.relu(self.conv2(input))
        return input
scripted_module = torch.jit.script(MyModule())

In [32]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv = nn.Conv2d(1, 1, 3)
    def forward(self, x):
        return self.conv(x)
n = Net()
example_weight = torch.rand(1, 1, 3, 3)
example_forward_input = torch.rand(1, 1, 3, 3)
module = torch.jit.trace(n.forward, example_forward_input)
module = torch.jit.trace(n, example_forward_input)

In [34]:
import torch
from torch import Tensor
def foo(a: Tensor, b: int)-> Tensor:
    return a + b
def bar(a):
    fut: torch.jit.Future[Tensor] = torch.jit.fork(foo, a, b = 2)
    return torch.jit.wait(fut)
script_bar = torch.jit.script(bar)
input = torch.tensor(2)
assert script_bar(input) == bar(input)
graph = torch.jit.trace(bar, (input, )).graph
assert "fork" in str(graph)

In [36]:
import torch
in_channels, out_channels = 3, 32
conv = torch.nn.Conv2d(in_channels, out_channels, kernel_size=3, stride=2, bias=True)
bn = torch.nn.BatchNorm2d(out_channels, eps=.001)
mod = torch.nn.Sequential(conv, bn)
frozen_mod = torch.jit.optimize_for_inference(torch.jit.script(mod.eval()))
assert "batch_norm" not in str(frozen_mod.graph)
assert "MKLDNN" in str(frozen_mod.graph)

In [41]:
import torch
from typing import Dict
@torch.jit.script
def fn():
    d = torch.jit.annotate(Dict[str, int], {})
    d["name"] = 20
    return d
print(fn())

{'name': 20}


In [43]:
import torch
def foo(x, y):
    return 2 * x + y
traced_foo = torch.jit.trace(foo, (torch.rand(3), torch.rand(3)))
@torch.jit.script
def bar(x):
    return traced_foo(x, x)

In [44]:
@torch.jit.script
def foo(x, y):
    if x.max() > y.max():
        r = x
    else:
        r = y
    return r
def bar(x, y, z):
    return foo(x, y) + z
traced_bar = torch.jit.trace(bar, (torch.rand(3), torch.rand(3), torch.rand(3)))

In [5]:
def loop_in_traced_fn(x):
    result = x[0]
    for i in range(x.size(0)):
        result = result * x[i]
    return result
inputs = (torch.rand(3, 4, 5),)
check_inputs = [(torch.rand(4, 5, 6), ), (torch.rand(2, 3, 4), )]
traced = torch.jit.trace(loop_in_traced_fn, inputs, check_inputs=check_inputs)

C:\Users\jatin\anaconda3\lib\site-packages\torch\jit\_trace.py:793: TracerWarning: Output nr 1. of the traced function does not match the corresponding output of the Python function. Detailed error:
With rtol=1e-05 and atol=1e-05, found 28 element(s) (out of 30) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 0.28691689670085907 (0.4184271991252899 vs. 0.13151030242443085), which occurred at index (0, 2).
  _check_trace(


TracingCheckError: Tracing failed sanity checks!
ERROR: Graphs differed across invocations!
	Graph diff:
		  graph(%x : Tensor):
		    %1 : int = prim::Constant[value=0]() # <ipython-input-5-1464e2c963d2>:2:0
		    %2 : int = prim::Constant[value=0]() # <ipython-input-5-1464e2c963d2>:2:0
		    %result.1 : Tensor = aten::select(%x, %1, %2) # <ipython-input-5-1464e2c963d2>:2:0
		    %4 : int = prim::Constant[value=0]() # <ipython-input-5-1464e2c963d2>:4:0
		    %5 : int = prim::Constant[value=0]() # <ipython-input-5-1464e2c963d2>:4:0
		    %6 : Tensor = aten::select(%x, %4, %5) # <ipython-input-5-1464e2c963d2>:4:0
		    %result.3 : Tensor = aten::mul(%result.1, %6) # <ipython-input-5-1464e2c963d2>:4:0
		    %8 : int = prim::Constant[value=0]() # <ipython-input-5-1464e2c963d2>:4:0
		    %9 : int = prim::Constant[value=1]() # <ipython-input-5-1464e2c963d2>:4:0
		    %10 : Tensor = aten::select(%x, %8, %9) # <ipython-input-5-1464e2c963d2>:4:0
		-   %result : Tensor = aten::mul(%result.3, %10) # <ipython-input-5-1464e2c963d2>:4:0
		+   %result.5 : Tensor = aten::mul(%result.3, %10) # <ipython-input-5-1464e2c963d2>:4:0
		?          ++
		    %12 : int = prim::Constant[value=0]() # <ipython-input-5-1464e2c963d2>:4:0
		    %13 : int = prim::Constant[value=2]() # <ipython-input-5-1464e2c963d2>:4:0
		    %14 : Tensor = aten::select(%x, %12, %13) # <ipython-input-5-1464e2c963d2>:4:0
		+   %result : Tensor = aten::mul(%result.5, %14) # <ipython-input-5-1464e2c963d2>:4:0
		+   %16 : int = prim::Constant[value=0]() # <ipython-input-5-1464e2c963d2>:4:0
		+   %17 : int = prim::Constant[value=3]() # <ipython-input-5-1464e2c963d2>:4:0
		+   %18 : Tensor = aten::select(%x, %16, %17) # <ipython-input-5-1464e2c963d2>:4:0
		-   %15 : Tensor = aten::mul(%result, %14) # <ipython-input-5-1464e2c963d2>:4:0
		?     ^                                 ^
		+   %19 : Tensor = aten::mul(%result, %18) # <ipython-input-5-1464e2c963d2>:4:0
		?     ^                                 ^
		-   return (%15)
		?             ^
		+   return (%19)
		?             ^
	First diverging operator:
	Node diff:
		- %result : Tensor = aten::mul(%result.3, %10) # <ipython-input-5-1464e2c963d2>:4:0
		+ %result.5 : Tensor = aten::mul(%result.3, %10) # <ipython-input-5-1464e2c963d2>:4:0
		?        ++
	Trace source location:
		<ipython-input-5-1464e2c963d2>(4): loop_in_traced_fn
		C:\Users\jatin\anaconda3\lib\site-packages\torch\jit\_trace.py(780): trace
		<ipython-input-5-1464e2c963d2>(8): <module>
		C:\Users\jatin\anaconda3\lib\site-packages\IPython\core\interactiveshell.py(3437): run_code
		C:\Users\jatin\anaconda3\lib\site-packages\IPython\core\interactiveshell.py(3357): run_ast_nodes
		C:\Users\jatin\anaconda3\lib\site-packages\IPython\core\interactiveshell.py(3165): run_cell_async
		C:\Users\jatin\anaconda3\lib\site-packages\IPython\core\async_helpers.py(68): _pseudo_sync_runner
		C:\Users\jatin\anaconda3\lib\site-packages\IPython\core\interactiveshell.py(2940): _run_cell
		C:\Users\jatin\anaconda3\lib\site-packages\IPython\core\interactiveshell.py(2894): run_cell
		C:\Users\jatin\anaconda3\lib\site-packages\ipykernel\zmqshell.py(536): run_cell
		C:\Users\jatin\anaconda3\lib\site-packages\ipykernel\ipkernel.py(306): do_execute
		C:\Users\jatin\anaconda3\lib\site-packages\tornado\gen.py(234): wrapper
		C:\Users\jatin\anaconda3\lib\site-packages\ipykernel\kernelbase.py(543): execute_request
		C:\Users\jatin\anaconda3\lib\site-packages\tornado\gen.py(234): wrapper
		C:\Users\jatin\anaconda3\lib\site-packages\ipykernel\kernelbase.py(268): dispatch_shell
		C:\Users\jatin\anaconda3\lib\site-packages\tornado\gen.py(234): wrapper
		C:\Users\jatin\anaconda3\lib\site-packages\ipykernel\kernelbase.py(365): process_one
		C:\Users\jatin\anaconda3\lib\site-packages\tornado\gen.py(775): run
		C:\Users\jatin\anaconda3\lib\site-packages\tornado\gen.py(814): inner
		C:\Users\jatin\anaconda3\lib\site-packages\tornado\ioloop.py(741): _run_callback
		C:\Users\jatin\anaconda3\lib\site-packages\tornado\ioloop.py(688): <lambda>
		C:\Users\jatin\anaconda3\lib\asyncio\events.py(81): _run
		C:\Users\jatin\anaconda3\lib\asyncio\base_events.py(1859): _run_once
		C:\Users\jatin\anaconda3\lib\asyncio\base_events.py(570): run_forever
		C:\Users\jatin\anaconda3\lib\site-packages\tornado\platform\asyncio.py(199): start
		C:\Users\jatin\anaconda3\lib\site-packages\ipykernel\kernelapp.py(612): start
		C:\Users\jatin\anaconda3\lib\site-packages\traitlets\config\application.py(845): launch_instance
		C:\Users\jatin\anaconda3\lib\site-packages\ipykernel_launcher.py(16): <module>
		C:\Users\jatin\anaconda3\lib\runpy.py(87): _run_code
		C:\Users\jatin\anaconda3\lib\runpy.py(194): _run_module_as_main
	Check source location:
		<ipython-input-5-1464e2c963d2>(4): loop_in_traced_fn
		C:\Users\jatin\anaconda3\lib\site-packages\torch\jit\_trace.py(780): trace
		C:\Users\jatin\anaconda3\lib\site-packages\torch\jit\_trace.py(344): _check_trace
		C:\Users\jatin\anaconda3\lib\site-packages\torch\autograd\grad_mode.py(28): decorate_context
		C:\Users\jatin\anaconda3\lib\site-packages\torch\jit\_trace.py(793): trace
		<ipython-input-5-1464e2c963d2>(8): <module>
		C:\Users\jatin\anaconda3\lib\site-packages\IPython\core\interactiveshell.py(3437): run_code
		C:\Users\jatin\anaconda3\lib\site-packages\IPython\core\interactiveshell.py(3357): run_ast_nodes
		C:\Users\jatin\anaconda3\lib\site-packages\IPython\core\interactiveshell.py(3165): run_cell_async
		C:\Users\jatin\anaconda3\lib\site-packages\IPython\core\async_helpers.py(68): _pseudo_sync_runner
		C:\Users\jatin\anaconda3\lib\site-packages\IPython\core\interactiveshell.py(2940): _run_cell
		C:\Users\jatin\anaconda3\lib\site-packages\IPython\core\interactiveshell.py(2894): run_cell
		C:\Users\jatin\anaconda3\lib\site-packages\ipykernel\zmqshell.py(536): run_cell
		C:\Users\jatin\anaconda3\lib\site-packages\ipykernel\ipkernel.py(306): do_execute
		C:\Users\jatin\anaconda3\lib\site-packages\tornado\gen.py(234): wrapper
		C:\Users\jatin\anaconda3\lib\site-packages\ipykernel\kernelbase.py(543): execute_request
		C:\Users\jatin\anaconda3\lib\site-packages\tornado\gen.py(234): wrapper
		C:\Users\jatin\anaconda3\lib\site-packages\ipykernel\kernelbase.py(268): dispatch_shell
		C:\Users\jatin\anaconda3\lib\site-packages\tornado\gen.py(234): wrapper
		C:\Users\jatin\anaconda3\lib\site-packages\ipykernel\kernelbase.py(365): process_one
		C:\Users\jatin\anaconda3\lib\site-packages\tornado\gen.py(775): run
		C:\Users\jatin\anaconda3\lib\site-packages\tornado\gen.py(814): inner
		C:\Users\jatin\anaconda3\lib\site-packages\tornado\ioloop.py(741): _run_callback
		C:\Users\jatin\anaconda3\lib\site-packages\tornado\ioloop.py(688): <lambda>
		C:\Users\jatin\anaconda3\lib\asyncio\events.py(81): _run
		C:\Users\jatin\anaconda3\lib\asyncio\base_events.py(1859): _run_once
		C:\Users\jatin\anaconda3\lib\asyncio\base_events.py(570): run_forever
		C:\Users\jatin\anaconda3\lib\site-packages\tornado\platform\asyncio.py(199): start
		C:\Users\jatin\anaconda3\lib\site-packages\ipykernel\kernelapp.py(612): start
		C:\Users\jatin\anaconda3\lib\site-packages\traitlets\config\application.py(845): launch_instance
		C:\Users\jatin\anaconda3\lib\site-packages\ipykernel_launcher.py(16): <module>
		C:\Users\jatin\anaconda3\lib\runpy.py(87): _run_code
		C:\Users\jatin\anaconda3\lib\runpy.py(194): _run_module_as_main


In [6]:
def fn(x):
    result = x[0]
    for i in range(x.size(0)):
        result = result * x[i]
    return result
inputs = (torch.rand(3, 4, 5), )
check_inputs = [(torch.rand(4, 5, 6), ), (torch.rand(2, 3, 4), )]
scripted_fn = torch.jit.script(fn)
print(scripted_fn.graph)
for input_tuple in [inputs] + check_inputs:
    torch.testing.assert_close(fn(*input_tuple), scripted_fn(*input_tuple))

graph(%x.1 : Tensor):
  %9 : bool = prim::Constant[value=1]() # <ipython-input-6-d27985927d3e>:3:4
  %2 : int = prim::Constant[value=0]() # <ipython-input-6-d27985927d3e>:2:15
  %result.1 : Tensor = aten::select(%x.1, %2, %2) # <ipython-input-6-d27985927d3e>:2:13
  %6 : int = aten::size(%x.1, %2) # <ipython-input-6-d27985927d3e>:3:19
  %result : Tensor = prim::Loop(%6, %9, %result.1) # <ipython-input-6-d27985927d3e>:3:4
    block0(%i.1 : int, %result.11 : Tensor):
      %17 : Tensor = aten::select(%x.1, %2, %i.1) # <ipython-input-6-d27985927d3e>:4:26
      %result.5 : Tensor = aten::mul(%result.11, %17) # <ipython-input-6-d27985927d3e>:4:17
      -> (%9, %result.5)
  return (%result)



In [7]:
def fill_row_zero(x):
    x[0] = torch.rand(*x.shape[1:2])
    return x
traced = torch.jit.trace(fill_row_zero, (torch.rand(3, 4), ))
print(traced.graph)

graph(%x : Float(3, 4, strides=[4, 1], requires_grad=0, device=cpu)):
  %4 : int = prim::Constant[value=1]() # <ipython-input-7-7b26c3e7e27a>:2:0
  %5 : int = aten::size(%x, %4) # <ipython-input-7-7b26c3e7e27a>:2:0
  %6 : Long(device=cpu) = prim::NumToTensor(%5)
  %7 : int = aten::Int(%6)
  %8 : int[] = prim::ListConstruct(%7)
  %9 : int = prim::Constant[value=6]() # <ipython-input-7-7b26c3e7e27a>:2:0
  %10 : NoneType = prim::Constant()
  %11 : Device = prim::Constant[value="cpu"]() # <ipython-input-7-7b26c3e7e27a>:2:0
  %12 : bool = prim::Constant[value=0]() # <ipython-input-7-7b26c3e7e27a>:2:0
  %13 : Float(4, strides=[1], requires_grad=0, device=cpu) = aten::rand(%8, %9, %10, %11, %12) # <ipython-input-7-7b26c3e7e27a>:2:0
  %14 : int = prim::Constant[value=0]() # <ipython-input-7-7b26c3e7e27a>:2:0
  %15 : int = prim::Constant[value=0]() # <ipython-input-7-7b26c3e7e27a>:2:0
  %16 : Float(4, strides=[1], requires_grad=0, device=cpu) = aten::select(%x, %14, %15) # <ipython-input-7-7b26

C:\Users\jatin\anaconda3\lib\site-packages\torch\jit\_trace.py:804: TracerWarning: Trace had nondeterministic nodes. Did you forget call .eval() on your model? Nodes:
	%13 : Float(4, strides=[1], requires_grad=0, device=cpu) = aten::rand(%8, %9, %10, %11, %12) # <ipython-input-7-7b26c3e7e27a>:2:0
This may cause errors in trace checking. To disable trace checking, pass check_trace=False to torch.jit.trace()
  _check_trace(
C:\Users\jatin\anaconda3\lib\site-packages\torch\jit\_trace.py:804: TracerWarning: Output nr 1. of the traced function does not match the corresponding output of the Python function. Detailed error:
With rtol=1e-05 and atol=1e-05, found 4 element(s) (out of 12) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 0.5748920440673828 (0.7993494272232056 vs. 0.22445738315582275), which occurred at index (0, 0).
  _check_trace(


In [8]:
import torch
class Model(torch.nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.x = 2
    def forward(self):
        return self.x
m = torch.jit.script(Model())

In [10]:
import torch
import torch.nn as nn
import torch.nn.functional as F
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.conv1 = nn.Conv2d(1, 20, 5)
        self.conv2 = nn.Conv2d(20, 20, 5)
    def forward(self, x):
        x = F.relu(self.conv1(x))
        return F.relu(self.conv2(x))
my_model = Model()
my_scripted_model = torch.jit.script(my_model)

In [2]:
import torch.nn as nn
class MyModule(nn.Module):
    def implicitly_compiled_method(self, x):
        return x + 99
    def forward(self, x):
        return x + 10
    @torch.jit.export
    def another_forward(self, x):
        return self.implicitly_compiled_method(x)
    def unused_method(self, x):
        return x - 20
m = torch.jit.script(MyModule())

In [3]:
@torch.jit.script
def some_fn():
    return 2
@torch.jit.ignore
def some_fn2():
    return 2
@torch.jit.unused
def some_fn3():
    import pdb; pdb.set_trace()
    return 4
@torch.jit.export
def some_fn4():
    return 2

In [5]:
from typing import Dict
class MyModule(torch.jit.ScriptModule):
    def __init__(self):
        super(MyModule, self).__init__()
        self.my_dict = torch.jit.Attribute({}, Dict[str, int])
        self.my_int = torch.jit.Attribute(20, int)
m = MyModule()
m.my_int

20

In [6]:
from torch import linalg as LA
a = torch.arange(9, dtype=torch.float) - 4
B = a.reshape((3, 3))
LA.norm(B)

tensor(7.7460)

In [7]:
LA.norm(a, -float("inf"))

tensor(0.)

In [9]:
print(LA.vector_norm(a, ord=3.5))
print(LA.vector_norm(B, ord=3.5))

tensor(5.4345)
tensor(5.4345)


In [10]:
LA.matrix_norm(B)

tensor(7.7460)

In [12]:
c = B.expand(2, -1, -1)
LA.matrix_norm(c)

tensor([7.7460, 7.7460])

In [14]:
A = torch.randn(3, 3)
torch.linalg.det(A)

tensor(-1.3261)

In [16]:
# print(torch.linalg.logdet(A))
print(torch.linalg.slogdet(A))

torch.return_types.linalg_slogdet(
sign=tensor(-1.),
logabsdet=tensor(0.2823))


In [17]:
A = torch.randn(3, 4, 4, dtype=torch.complex64)
torch.linalg.cond(A)

tensor([4.5793, 4.5844, 8.1285])

In [19]:
A = torch.tensor([[1, 0, -1], [0, 1, 0], [1, 0, 1]], dtype=float)
torch.linalg.cond(A)

tensor(1.4142, dtype=torch.float64)

In [21]:
A = torch.eye(10)
A[0, 0] = 0
torch.linalg.matrix_rank(A)

tensor(9)

In [26]:
A = torch.randn(2, 4, 3, 3, dtype=torch.complex64)
torch.linalg.matrix_rank(A)

tensor([[3, 3, 3, 3],
        [3, 3, 3, 3]])

In [27]:
A = torch.randn(2, 2, dtype=torch.complex128)
A = A @ A.T.conj() + torch.eye(2)
A

tensor([[ 3.2332+2.6967e-18j, -0.7550-4.8069e-01j],
        [-0.7550+4.8069e-01j,  2.0208+1.2575e-17j]], dtype=torch.complex128)

In [28]:
torch.linalg.cholesky(A)

tensor([[ 1.7981+0.0000j,  0.0000+0.0000j],
        [-0.4199+0.2673j,  1.3315+0.0000j]], dtype=torch.complex128)

In [29]:
A = torch.tensor([[12., -51, 4], [6, 167, -68], [-4, 24, -41]])
Q, R = torch.linalg.qr(A)
print(Q)
print(R)

tensor([[-0.8571,  0.3943,  0.3314],
        [-0.4286, -0.9029, -0.0343],
        [ 0.2857, -0.1714,  0.9429]])
tensor([[ -14.0000,  -21.0000,   14.0000],
        [   0.0000, -175.0000,   70.0000],
        [   0.0000,    0.0000,  -35.0000]])


In [32]:
torch.dist(Q @ R, torch.eye(3))

tensor(193.1580)

In [35]:
A = torch.randn(3, 2, 2, dtype=torch.float64)
L, V = torch.linalg.eig(A)
torch.dist(V @ torch.diag_embed(L) @ torch.linalg.inv(V), A)

tensor(5.4672e-16, dtype=torch.float64)

In [36]:
A = torch.randn(2, 2, dtype=torch.complex128)
L = torch.linalg.eigvals(A)
L

tensor([0.9201-1.8736j, 0.7970+1.9244j], dtype=torch.complex128)

In [37]:
A = torch.randn(2, 2, dtype=torch.complex128)
A = A + A.T.conj()
L, Q = torch.linalg.eigh(A)
print(L)
Q

tensor([-2.1710,  0.8325], dtype=torch.float64)


tensor([[ 0.5527+0.0000j, -0.8334+0.0000j],
        [-0.5276-0.6451j, -0.3499-0.4278j]], dtype=torch.complex128)

In [38]:
torch.linalg.eigvalsh(A)

tensor([-2.1710,  0.8325], dtype=torch.float64)

In [39]:
A = torch.randn(5, 3)
U, S, Vh = torch.linalg.svd(A, full_matrices=False)
U.shape, S.shape, Vh.shape

(torch.Size([5, 3]), torch.Size([3]), torch.Size([3, 3]))

In [40]:
A = torch.randn(5, 3)
S = torch.linalg.svdvals(A)
S

tensor([3.2635, 1.5888, 1.0854])

In [41]:
A = torch.randn(3, 3)
b = torch.randn(3)
x = torch.linalg.solve(A, b)
torch.allclose(A @ x, b)

True

In [43]:
A = torch.tensor([[[10, 2, 3], [3, 10, 5], [5, 6, 12]]], dtype=torch.float)
B = torch.tensor([[[2, 5, 1], [3, 2, 1], [5, 1, 9]], [[4, 2, 9], [2, 0, 3], [2, 5, 3]]], dtype=torch.float)
X = torch.linalg.lstsq(A, B).solution
torch.dist(X, torch.linalg.pinv(A) @ B)

tensor(4.4329e-07)

In [44]:
A = torch.randn(4, 4)
Ainv = torch.linalg.inv(A)
torch.dist(A @ Ainv, torch.eye(4))

tensor(3.3247e-07)

In [45]:
A = torch.randn(2, 6, 3)
Apinv = torch.linalg.pinv(A)
torch.dist(Apinv @ A, torch.eye(3))

tensor(4.4053e-07)

In [48]:
A = torch.randn(3, 3)
torch.linalg.matrix_power(A, 0)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [50]:
from torch.linalg import multi_dot
A = torch.arange(2 * 3).view(2, 3)
B = torch.arange(3 * 2).view(3, 2)
C = torch.arange(2 * 2).view(2, 2)
multi_dot((A, B, C))

tensor([[ 26,  49],
        [ 80, 148]])

In [52]:
A = torch.randn(2, 2)
h, tau = torch.geqrf(A)
Q = torch.linalg.householder_product(h, tau)
torch.dist(Q, torch.linalg.qr(A).Q)

tensor(0.)

In [53]:
A = torch.eye(4 * 6).reshape(4, 6, 8, 3)
Ainv = torch.linalg.tensorinv(A, ind=2)
print(Ainv.shape)
B = torch.randn(4, 6)
torch.allclose(torch.tensordot(Ainv, B), torch.linalg.tensorsolve(A, B))

torch.Size([8, 3, 4, 6])


True

In [55]:
A = torch.eye(2 * 3* 4).reshape((2 * 3, 4, 2, 3, 4))
B = torch.randn(2 * 3, 4)
X = torch.linalg.tensorsolve(A, B)
X.shape

torch.Size([2, 3, 4])

In [56]:
A = torch.randn(2, 2, dtype=torch.complex128)
A = A @ A.t().conj()
L, info = torch.linalg.cholesky_ex(A)
print(A)
print(L)
print(info)

tensor([[ 1.6014-3.9002e-17j, -0.8521+3.6165e-01j],
        [-0.8521-3.6165e-01j,  1.7246-2.3920e-17j]], dtype=torch.complex128)
tensor([[ 1.2655+0.0000j,  0.0000+0.0000j],
        [-0.6733-0.2858j,  1.0907+0.0000j]], dtype=torch.complex128)
tensor(0, dtype=torch.int32)


In [57]:
A = torch.randn(3, 3)
Ainv, info = torch.linalg.inv_ex(A)
print(torch.dist(torch.linalg.inv(A), Ainv))
info

tensor(0.)


tensor(0, dtype=torch.int32)

In [58]:
a = torch.arange(-0.5, 1, 0.5)
torch.special.entr(a)

tensor([  -inf, 0.0000, 0.3466])

In [59]:
torch.special.erf(torch.tensor([0, -1., 10.]))

tensor([ 0.0000, -0.8427,  1.0000])

In [60]:
torch.special.erfc(torch.tensor([0, -1., 10.]))

tensor([1.0000e+00, 1.8427e+00, 1.4013e-45])

In [62]:
torch.special.erfinv(torch.tensor([0, 0.5, -1.]))

tensor([0.0000, 0.4769,   -inf])

In [63]:
t = torch.randn(4)
torch.special.expit(t)

tensor([0.1224, 0.5349, 0.1172, 0.2745])

In [66]:
import math
torch.special.expm1(torch.tensor([0, math.log(2.)]))

tensor([0., 1.])

In [67]:
torch.special.exp2(torch.tensor([0, math.log2(2.), 3, 4]))

tensor([ 1.,  2.,  8., 16.])

In [69]:
a = torch.arange(0.5, 2, 0.5)
torch.special.gammaln(a)

tensor([ 0.5724,  0.0000, -0.1208])

In [75]:
torch.i0(torch.arange(5, dtype=torch.float32))

tensor([ 1.0000,  1.2661,  2.2796,  4.8808, 11.3019])

In [77]:
torch.special.i0e(torch.arange(5, dtype=torch.float32))

tensor([1.0000, 0.4658, 0.3085, 0.2430, 0.2070])

In [80]:
a = torch.rand(5)
torch.special.logit(a, eps=1e-6)

tensor([-0.7958,  3.1312, -3.3644,  1.2448, -1.1219])

In [85]:
x = torch.zeros(5,)
y = torch.tensor([-1, 0, 1, float('inf'), float('nan')])
torch.special.xlog1py(x, y)

tensor([0., 0., 0., 0., nan])

In [89]:
torch.Tensor.as_subclass in torch.overrides.get_ignored_functions()

True

In [90]:
torch.add in torch.overrides.get_overridable_functions()

False

In [93]:
import inspect
my_add = torch.overrides.get_testing_overrides()[torch.add]
inspect.signature(my_add)

<Signature (input, other, out=None)>

In [95]:
def func(a):
    if type(a) is not torch.Tensor:
        return torch.overrides.handle_torch_function(func, (a, ), a)
    return a + 0

In [96]:
class SubTensor(torch.Tensor):
    ...
torch.overrides.is_tensor_like(SubTensor([0]))

True

In [97]:
def dispatcher(a):
    return a
@torch.overrides.wrap_torch_function(dispatcher)
def func(a):
    return a + 0

In [107]:
from torch.package import PackageExporter

In [111]:
with PackageExporter("package.pt") as exporter:
    exporter.save_pickle("my_resources", "tensor.pkl", torch.randn(4))
    exporter.save_text("config_stuff", "words.txt", "a sample")

tensor.pkl depends on:
  torch._utils
  torch
  collections


implicitly adding torch._utils to external modules since it is part of the standard library and is a dependency.
implicitly adding torch to external modules since it is part of the standard library and is a dependency.
implicitly adding collections to external modules since it is part of the standard library and is a dependency.
Dependency graph for exported package: 
https://dreampuf.github.io/GraphvizOnline/#digraph%20G%20%7B%0Arankdir%20%3D%20LR%3B%0Anode%20%5Bshape%3Dbox%5D%3B%0A%0A%22%3Cmy_resources.tensor.pkl%3E%22%20-%3E%20%22torch._utils%22%3B%0A%22%3Cmy_resources.tensor.pkl%3E%22%20-%3E%20%22torch%22%3B%0A%22%3Cmy_resources.tensor.pkl%3E%22%20-%3E%20%22collections%22%3B%0A%7D%0A


In [112]:
importer = torch.package.PackageImporter("package.pt")
my_tensor = importer.load_pickle("my_resources", "tensor.pkl")
text = importer.load_text("config_stuff", "words.txt")

In [2]:
gain = torch.nn.init.calculate_gain("leaky_relu", 0.2)

In [3]:
gain

1.3867504905630728

In [5]:
m = torch.empty(3, 5)
torch.nn.init.uniform_(m)

tensor([[0.9584, 0.2190, 0.9279, 0.5354, 0.6853],
        [0.3684, 0.6573, 0.3949, 0.7952, 0.1049],
        [0.8523, 0.4098, 0.1074, 0.8224, 0.2985]])

In [7]:
torch.nn.init.normal_(m)

tensor([[ 1.3249,  1.6248, -0.3909,  0.3470, -0.0066],
        [ 0.1708, -0.4501, -0.0108,  0.0491,  0.0286],
        [ 0.8473, -0.3848, -0.8905, -0.2987,  0.5127]])

In [8]:
torch.nn.init.constant_(m, 0.3)

tensor([[0.3000, 0.3000, 0.3000, 0.3000, 0.3000],
        [0.3000, 0.3000, 0.3000, 0.3000, 0.3000],
        [0.3000, 0.3000, 0.3000, 0.3000, 0.3000]])

In [10]:
torch.nn.init.ones_(m)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [11]:
torch.nn.init.zeros_(m)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [12]:
torch.nn.init.eye_(m)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])

In [13]:
w = torch.empty(3, 16, 5, 5)
torch.nn.init.dirac_(w)

tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 1., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         ...,

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[

In [16]:
torch.nn.init.xavier_uniform_(m, gain=torch.nn.init.calculate_gain("relu"))

tensor([[ 0.7319,  0.0070,  0.5564, -0.4534, -0.0692],
        [-0.7767,  0.5756, -0.2745, -0.8639,  0.8891],
        [ 0.1480,  1.0976,  0.6112, -0.4536, -0.6664]])

In [18]:
torch.nn.init.xavier_normal_(m)

tensor([[ 0.1172, -0.3119,  0.3522, -0.4159, -0.5255],
        [ 0.2012, -0.0141,  0.4407,  0.5820,  0.1637],
        [-0.0733,  0.1447,  0.2937,  0.4981,  0.0221]])

In [19]:
torch.nn.init.kaiming_uniform_(m, mode="fan_in", nonlinearity="relu")

tensor([[-0.3418, -0.6898,  0.9060, -0.3055, -0.2486],
        [-0.3696, -1.0236,  1.0224,  0.4461, -0.4644],
        [-0.3318,  0.8218,  1.0911,  1.0146,  1.0218]])

In [20]:
torch.nn.init.kaiming_normal_(m, mode="fan_out", nonlinearity="relu")

tensor([[-0.1079, -1.4880, -0.1063,  0.9117,  0.4729],
        [-0.8723, -0.3095, -0.6424, -1.1043, -0.2977],
        [ 0.3701, -0.4191,  0.3964, -0.7231, -1.1504]])

In [21]:
torch.nn.init.orthogonal_(m)

tensor([[-0.0433, -0.2573,  0.7338,  0.0483,  0.6254],
        [-0.0905,  0.1988, -0.5955,  0.0159,  0.7729],
        [-0.6144,  0.0308,  0.0487, -0.7864, -0.0262]])

In [24]:
torch.nn.init.sparse_(m, sparsity=0.1)

tensor([[ 0.0000, -0.0023,  0.0000, -0.0005,  0.0000],
        [ 0.0109,  0.0030, -0.0195,  0.0067,  0.0071],
        [-0.0093,  0.0000, -0.0060,  0.0000,  0.0047]])

In [25]:
x = torch.randn(2, 2, dtype=torch.cfloat)
x

tensor([[-0.1879-0.5462j, -0.3580+0.0752j],
        [-0.3668+0.6411j, -1.0295+0.5774j]])

In [26]:
a = torch.randn(3, 2)
a

tensor([[ 0.1824,  0.5618],
        [-0.4795, -0.0286],
        [-0.3625,  0.5554]])

In [27]:
y = torch.view_as_complex(a)
y

tensor([ 0.1824+0.5618j, -0.4795-0.0286j, -0.3625+0.5554j])

In [28]:
torch.view_as_real(y)

tensor([[ 0.1824,  0.5618],
        [-0.4795, -0.0286],
        [-0.3625,  0.5554]])

In [29]:
print(y.real)
print(y.imag)
print(y.real.mul_(2))
y.real.stride()

tensor([ 0.1824, -0.4795, -0.3625])
tensor([ 0.5618, -0.0286,  0.5554])
tensor([ 0.3647, -0.9591, -0.7250])


(2,)

In [30]:
x1 = torch.tensor([3j, 4 + 4j])
print(x1.abs())
print(x1.angle())

tensor([3.0000, 5.6569])
tensor([1.5708, 0.7854])


In [40]:
import os
os.environ["MASTER_ADDR"] = "localhost"
os.environ["MASTER_PORT"] = "29500"
# torch.distributed.rpc.init_rpc('worker', rank=0, world_size=1)
fc1 = torch.nn.Linear(16, 8).cpu()
fc2 = torch.nn.Linear(8, 4).cpu()
model = torch.nn.Sequential(fc1, fc2)
input = torch.rand(16, 16).cpu()
output_rref = model(input)

In [47]:
class M(torch.nn.Module):
    def __init__(self):
        super(M, self).__init__()
        self.fc = torch.nn.Linear(4, 4)
    def forward(self, x):
        x = self.fc(x)
        return x
model_fp32 = M()
model_int8 = torch.quantization.quantize_dynamic(model_fp32, {torch.nn.Linear}, dtype=torch.qint8)
input_fp32 = torch.randn(4, 4, 4, 4)
res = model_int8(input_fp32)

In [49]:
class M(torch.nn.Module):
    def __init__(self):
        super(M, self).__init__()
        self.quant = torch.quantization.QuantStub()
        self.conv = torch.nn.Conv2d(1, 1, 1)
        self.relu = torch.nn.ReLU()
        self.dequant = torch.quantization.DeQuantStub()
    def forward(self, x):
        x = self.quant(x)
        x = self.conv(x)
        x = self.relu(x)
        x = self.dequant(x)
        return x
model_fp32 = M()
model_fp32.eval()
model_fp32.qconfig = torch.quantization.get_default_qconfig('fbgemm')
model_fp32_fused = torch.quantization.fuse_modules(model_fp32, [['conv', 'relu']])
model_fp32_prepared = torch.quantization.prepare(model_fp32_fused)
input_fp32 = torch.randn(4, 1, 4, 4)
model_fp32_prepared(input_fp32)
model_int8 = torch.quantization.convert(model_fp32_prepared)
res = model_int8(input_fp32)

In [52]:
class M(torch.nn.Module):
    def __init__(self):
        super(M, self).__init__()
        self.quant = torch.quantization.QuantStub()
        self.conv = torch.nn.Conv2d(1, 1, 1)
        self.bn = torch.nn.BatchNorm2d(1)
        self.relu = torch.nn.ReLU()
        self.dequant = torch.quantization.DeQuantStub()
    def forward(self, x):
        x = self.quant(x)
        x = self.conv(x)
        x = self.bn(x)
        x = self.relu(x)
        x = self.dequant(x)
        return x
model_fp32 = M()
model_fp32.train()
model_fp32.qconfig = torch.quantization.get_default_qat_qconfig("fbgemm")
model_fp32_fused = torch.quantization.fuse_modules(model_fp32, [["conv", "bn", "relu"]])
model_fp32_prepared = torch.quantization.prepare_qat(model_fp32_fused)
# training_loop(model_fp32_prepared)
model_fp32_prepared.eval()
model_int8 = torch.quantization.convert(model_fp32_prepared)
res = model_int8(input_fp32)

C:\Users\jatin\anaconda3\lib\site-packages\torch\quantization\observer.py:244: UserWarning: must run observer before calling calculate_qparams.                                        Returning default scale and zero point 
  warnings.warn(


In [55]:
import copy
import torch.quantization.quantize_fx as quantize_fx
model_fp = M()
model_to_quantize = copy.deepcopy(model_fp)
model_to_quantize.eval()
qconfig_dict = {"":torch.quantization.default_dynamic_qconfig}
model_prepared = quantize_fx.prepare_fx(model_to_quantize, qconfig_dict)
model_quantize = quantize_fx.convert_fx(model_prepared)

C:\Users\jatin\anaconda3\lib\site-packages\torch\quantization\fx\quantization_patterns.py:441: UserWarning: dtype combination: (torch.float32, torch.qint8, torch.quint8) is not supported by Conv supported dtype combinations are: [(torch.quint8, torch.qint8, None)]
  warnings.warn(


In [60]:
model_to_quantize = copy.deepcopy(model_fp)
qconfig_dict = {"":torch.quantization.get_default_qconfig('qnnpack')}
model_to_quantize.eval()
model_prepared = quantize_fx.prepare_fx(model_to_quantize, qconfig_dict)
model_quantized = quantize_fx.convert_fx(model_prepared)

model_to_quantize = copy.deepcopy(model_fp)
qconfig_dict = {"": torch.quantization.get_default_qat_qconfig('qnnpack')}
model_to_quantize.train()
model_prepared = quantize_fx.prepare_qat_fx(model_to_quantize, qconfig_dict)
model_quantized = quantize_fx.convert_fx(model_prepared)

In [61]:
qconfig = torch.quantization.get_default_qconfig('fbgemm')
qconfig = torch.quantization.get_default_qat_qconfig("fbgemm")
torch.backends.quantized.engine = "fbgemm"

In [1]:
import torch

In [2]:
import torch.nn.quantized as nnq
import torch.quantization.quantize_fx
class CustomModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = torch.nn.Linear(3, 3)
    def forward(self, x):
        return self.linear(x)
    
class ObservedCustomModule(torch.nn.Module):
    def __init__(self, linear):
        super().__init__()
        self.linear = linear
    def forward(self, x):
        return self.linear(x)
    @classmethod
    def from_float(cls, float_module):
        assert hasattr(float_module, "qconfig")
        observed = cls(float_module.linear)
        observed.qconfig = float_module.qconfig
        return observed

class StaticQuantizedCustomModule(torch.nn.Module):
    def __init__(self, linear):
        super().__init__()
        self.linear = linear
    def forward(self, x):
        return self.linear(x)
    @classmethod
    def from_observed(cls, observed_module):
        assert hasattr(observed_module, 'qconfig')
        assert hasattr(observed_module, 'activation_post_process')
        observed_module.linear.activation_post_process = observed_module.activation_post_process
        quantized = cls(nnq.Linear.from_float(observed_module.linear))
        return quantized

In [7]:
m = torch.nn.Sequential(CustomModule()).eval()
prepare_custom_config_dict = {
    "float_to_observed_custom_module_class":{
        CustomModule: ObservedCustomModule
    }
}
convert_custom_config_dict = {
    "observed_to_quantized_custom_module_class":{
        ObservedCustomModule: StaticQuantizedCustomModule
    }
}
m.qconfig = torch.quantization.default_qconfig
mp = torch.quantization.prepare(m, prepare_custom_config_dict=prepare_custom_config_dict)
mq = torch.quantization.convert(mp, convert_custom_config_dict=convert_custom_config_dict)
m = torch.nn.Sequential(CustomModule()).eval()
qconfig_dict = {'':torch.quantization.default_qconfig}
prepare_custom_config_dict = {
    "float_to_observed_custom_module_class": {
        "static":{
            CustomModule: ObservedCustomModule,
        }
    }
}
convert_custom_config_dict = {
    "observed_to_quatization_custom_module_class": {
        "static":{
            ObservedCustomModule: StaticQuantizedCustomModule,
        }
    }
}
mp = torch.quantization.quantize_fx.prepare_fx(m, qconfig_dict, prepare_custom_config_dict=prepare_custom_config_dict)
mq = torch.quantization.quantize_fx.convert_fx(mp, convert_custom_config_dict=convert_custom_config_dict)

In [5]:
i = [[0, 1, 1], 
    [2, 0, 2]]
v = [3, 4, 5]
s = torch.sparse_coo_tensor(i, v, (2, 3))
print(s)
s.to_dense()

tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 2]]),
       values=tensor([3, 4, 5]),
       size=(2, 3), nnz=3, layout=torch.sparse_coo)


tensor([[0, 0, 3],
        [4, 0, 5]])

In [12]:
i = [[0, 2], [1, 0], [1, 2]]
v = [3, 4, 5]
s = torch.sparse_coo_tensor(list(zip(*i)), v, (2, 3))
s = torch.sparse_coo_tensor(torch.tensor(i).t(), v, torch.Size([2, 3])).to_dense()
s

tensor([[0, 0, 3],
        [4, 0, 5]])

In [15]:
mat = torch.randn(2, 3)
vec = torch.randn(3)
torch.mv(mat, vec)

tensor([-0.0989,  1.0555])

In [16]:
v1 = torch.arange(1., 5.)
v2 = torch.arange(1., 4.)
torch.outer(v1, v2)

tensor([[ 1.,  2.,  3.],
        [ 2.,  4.,  6.],
        [ 3.,  6.,  9.],
        [ 4.,  8., 12.]])

In [19]:
a = torch.tensor([[12., -51, 4], [6, 167, -68], [-4, 24, -41]])
q, r = torch.qr(a)
print(q)
print(r)

tensor([[-0.8571,  0.3943,  0.3314],
        [-0.4286, -0.9029, -0.0343],
        [ 0.2857, -0.1714,  0.9429]])
tensor([[ -14.0000,  -21.0000,   14.0000],
        [   0.0000, -175.0000,   70.0000],
        [   0.0000,    0.0000,  -35.0000]])


In [20]:
A = torch.randn(2, 3, 1, 4, 4)
B = torch.randn(2, 3, 1, 4, 6)
X, LU = torch.solve(B, A)
torch.dist(B, A.matmul(X))

<ipython-input-20-2dc47a92198c>:3: UserWarning: torch.solve is deprecated in favor of torch.linalg.solveand will be removed in a future PyTorch release.
torch.linalg.solve has its arguments reversed and does not return the LU factorization.
To get the LU factorization see torch.lu, which can be used with torch.lu_solve or torch.lu_unpack.
X = torch.solve(B, A).solution
should be replaced with
X = torch.linalg.solve(A, B) (Triggered internally at  ..\aten\src\ATen\native\BatchLinearAlgebra.cpp:760.)
  X, LU = torch.solve(B, A)


tensor(6.5206e-06)

In [21]:
a = torch.randn(5, 3)
u, s, v = torch.svd(a)
print(u)
print(s)
print(v)

tensor([[ 0.3117, -0.4150, -0.0856],
        [ 0.2220, -0.8414,  0.1032],
        [-0.1134, -0.0046,  0.4629],
        [-0.6920, -0.2841, -0.6198],
        [ 0.6016,  0.1979, -0.6194]])
tensor([2.2635, 2.1693, 1.5099])
tensor([[ 0.0397, -0.9673, -0.2505],
        [ 0.7683, -0.1308,  0.6266],
        [ 0.6388,  0.2173, -0.7380]])


In [22]:
a = torch.randn(5, 5)
e, v = torch.symeig(a, eigenvectors=True)

<ipython-input-22-b475e1e86a61>:2: UserWarning: torch.symeig is deprecated in favor of torch.linalg.eigh and will be removed in a future PyTorch release.
The default behavior has changed from using the upper triangular portion of the matrix by default to using the lower triangular portion.
L, _ = torch.symeig(A, upper=upper)
should be replaced with
L = torch.linalg.eigvalsh(A, UPLO='U' if upper else 'L')
and
L, V = torch.symeig(A, eigenvectors=True)
should be replaced with
L, V = torch.linalg.eigh(A, UPLO='U' if upper else 'L') (Triggered internally at  ..\aten\src\ATen\native\BatchLinearAlgebra.cpp:2500.)
  e, v = torch.symeig(a, eigenvectors=True)


In [23]:
d = torch.tensor([[0, 0, 0], [9, 0, 10], [0, 0, 0]])
d.to_sparse()

tensor(indices=tensor([[1, 1],
                       [0, 2]]),
       values=tensor([ 9, 10]),
       size=(3, 3), nnz=2, layout=torch.sparse_coo)

In [24]:
a = torch.randn(2, 3).to_sparse().requires_grad_(True)
b = torch.randn(3, 2, requires_grad=True)
y = torch.sparse.mm(a, b)
y

tensor([[0.1699, 0.1815],
        [0.3992, 0.9767]], grad_fn=<SparseAddmmBackward>)

In [25]:
expected = np.array([1e0, 1e-1, 1e-2])
actual = np.arccos(np.cos(expected))
torch.testing.assert_close(actual, expected)

In [30]:
class SimpleCustomBatch:
    def __init__(self, data):
        transposed_data = list(zip(*data))
        self.inp = torch.stack(transposed_data[0], 0)
        self.tgt = torch.stack(transposed_data[1], 0)
    def pin_memory(self):
        self.inp = self.inp.pin_memory()
        self.tgt = self.tgt.pin_memory()
def collate_wrapper(batch):
    return SimpleCustomBatch(batch)

inps = torch.arange(10 * 5, dtype=torch.float32).view(10, 5)
thts = torch.arange(10 * 5, dtype=torch.float32).view(10, 5)
dataset = (inps, thts)
loader = torch.utils.data.DataLoader(dataset, batch_size=2, collate_fn=collate_wrapper, pin_memory=True)
for batch_ndx, sample in enumerate(loader):
    print(sample.inp.is_pinned())
    print(sample.tgt.is_pinned())

False
False


In [35]:
class MyIteratorDataset(torch.utils.data.IterableDataset):
    def __init__(self, start, end):
        super(MyIteratorDataset).__init__()
        assert end > start, "this example will workd with end >= start"
        self.start = start
        self.end = end
    def __iter__(self):
        worker_info = torch.utils.data.get_worker_info()
        if worker_info is None:
            iter_start = self.start
            iter_end = self.end
        else:
            per_worker = int(math.ceil((self.end - self.start)/float(worker_info_num_workers)))
            worker_id = worker_info.id
            iter_start = self.start + worker_id * per_worker
            iter_end = min(iter_start + per_worker, self.end)
        return iter(range(iter_start, iter_end))
ds = MyIteratorDataset(start=3, end=7)
print(list(torch.utils.data.DataLoader(ds, num_workers=0)))

[tensor([3]), tensor([4]), tensor([5]), tensor([6])]


In [40]:
class MyIterableDataset(torch.utils.data.IterableDataset):
    def __init__(self, start, end):
        super(MyIterableDataset).__init__()
        assert end > start, "This example code only works wityh end >= start"
        self.start = start
        self.end = end
    def __iter__(self):
        return iter(range(self.start, self.end))
ds = MyIterableDataset(start=3, end = 7)
print(list(torch.utils.data.DataLoader(ds, num_workers=0)))

[tensor([3]), tensor([4]), tensor([5]), tensor([6])]


In [46]:
t = torch.arange(4)
capsule = torch.utils.dlpack.to_dlpack(t)
capsule

<capsule object "dltensor" at 0x0000019802016F00>

In [48]:
t3 = torch.utils.dlpack.from_dlpack(capsule)

In [49]:
print(t3)
t3[0] = -9
print(t3)
print(t)

tensor([0, 1, 2, 3])
tensor([-9,  1,  2,  3])
tensor([-9,  1,  2,  3])


In [50]:
import torch.utils.mobile_optimizer

In [ ]:
state_dict = torch.hub.load_state_dict_from_url("https://s3.amazonaws.com/pytorch/models/resnet18-5c106cde.pth")

Downloading: "https://s3.amazonaws.com/pytorch/models/resnet18-5c106cde.pth" to C:\Users\jatin/.cache\torch\hub\checkpoints\resnet18-5c106cde.pth


  0%|          | 0.00/44.7M [00:00<?, ?B/s]

In [54]:
import torch.utils.model_zoo

In [55]:
from torch.utils.tensorboard import SummaryWriter

In [58]:
import numpy as np
writer = SummaryWriter()
for n_iter in range(100):
    writer.add_scalar('Loss/train', np.random.random(), n_iter)
    writer.add_scalar("Loss/test", np.random.random(), n_iter)
    writer.add_scalar("Accuracy/train", np.random.random(), n_iter)
    writer.add_scalar('Accuracy/test', np.random.random(), n_iter)
writer.close()

In [59]:
writer = SummaryWriter()
x = range(100)
for i in x:
    writer.add_scalar('y=2x', i * 2, i)
writer.close()

In [60]:
writer = SummaryWriter()
for i in range(10):
    x = np.random.random(1000)
writer.add_histogram("distribution centers", x + i, i)
writer.close()

In [62]:
torch.zeros(2, 3, names=('N', 'C'))

<ipython-input-62-eb74a8e0f1fd>:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  torch.zeros(2, 3, names=('N', 'C'))


tensor([[0., 0., 0.],
        [0., 0., 0.]], names=('N', 'C'))

In [63]:
imgs = torch.randn(1 ,2, 2, 3, names=('N', 'C', 'H', 'W'))
renamed_imgs = imgs.rename(H='height', W="width")
renamed_imgs.names

('N', 'C', 'height', 'width')

In [64]:
imgs = torch.randn(32, 3, 128, 128)
named_imgs = imgs.refine_names('N', 'C', "H", 'W')
named_imgs.names

('N', 'C', 'H', 'W')

In [65]:
imgs = torch.randn(32, 3, 128, 128, names=('N', 'C', 'H', 'W'))
flat_imgs = imgs.flatten(['C', 'H', 'W'], 'features')
flat_imgs.names, flat_imgs.shape

(('N', 'features'), torch.Size([32, 49152]))

In [66]:
torch.randn(2, names=('A',)).unflatten('A', (('B1', -1), ('B2', 1)))

tensor([[ 0.2717],
        [-0.6989]], names=('B1', 'B2'))

In [69]:
tensor = torch.randn(2, 2, 2, 2, 2, 2)
named_tensor = tensor.refine_names('A', 'B', 'C', 'D', 'E', 'F')
named_tensor.align_to('F', 'E', ...).names

('F', 'E', 'A', 'B', 'C', 'D')

In [71]:
mask = torch.randint(2, [127, 128], dtype=torch.bool).refine_names('W', 'H')
imgs = torch.randn(32, 128, 127, 3, names=('N', 'H', 'W', 'C'))
imgs.masked_fill_(mask.align_as(imgs), 0).names

('N', 'H', 'W', 'C')

In [74]:
import torchaudio

In [77]:
import math
freq, hop_length = 1025, 512
complex_specgrams = torch.randn(2, freq, 300, dtype=torch.cfloat)
rate = 1.3
phase_advance = torch.linspace(0, math.pi * hop_length, freq)[..., None]
x = torchaudio.functional.phase_vocoder(complex_specgrams, rate, phase_advance)
x.shape

torch.Size([2, 1025, 231])

In [78]:
specgram = torch.randn(1, 40, 1000)
delta = torchaudio.functional.compute_deltas(specgram)

In [80]:
delta.shape

torch.Size([1, 40, 1000])

# Audio I/O

In [4]:
import torch
import torchaudio
print(torch.__version__)
print(torchaudio.__version__)
import os
import requests
import matplotlib.pyplot as plt

1.9.1+cpu
0.9.1


In [5]:
_SAMPLE_DIR = "_assets"
SAMPLE_WAV_URL = "https://pytorch-tutorial-assets.s3.amazonaws.com/steam-train-whistle-daniel_simon.wav"
SAMPLE_WAV_PATH = os.path.join(_SAMPLE_DIR, "steam.wav")

SAMPLE_MP3_URL = "https://pytorch-tutorial-assets.s3.amazonaws.com/steam-train-whistle-daniel_simon.mp3"
SAMPLE_MP3_PATH = os.path.join(_SAMPLE_DIR, "steam.mp3")

SAMPLE_GSM_URL = "https://pytorch-tutorial-assets.s3.amazonaws.com/steam-train-whistle-daniel_simon.gsm"
SAMPLE_GSM_PATH = os.path.join(_SAMPLE_DIR, "steam.gsm")

SAMPLE_WAV_SPEECH_URL = "https://pytorch-tutorial-assets.s3.amazonaws.com/VOiCES_devkit/source-16k/train/sp0307/Lab41-SRI-VOiCES-src-sp0307-ch127535-sg0042.wav"  # noqa: E501
SAMPLE_WAV_SPEECH_PATH = os.path.join(_SAMPLE_DIR, "speech.wav")

SAMPLE_TAR_URL = "https://pytorch-tutorial-assets.s3.amazonaws.com/VOiCES_devkit.tar.gz"
SAMPLE_TAR_PATH = os.path.join(_SAMPLE_DIR, "sample.tar.gz")
SAMPLE_TAR_ITEM = "VOiCES_devkit/source-16k/train/sp0307/Lab41-SRI-VOiCES-src-sp0307-ch127535-sg0042.wav"

S3_BUCKET = "pytorch-tutorial-assets"
S3_KEY = "VOiCES_devkit/source-16k/train/sp0307/Lab41-SRI-VOiCES-src-sp0307-ch127535-sg0042.wav"

In [6]:
def _fetch_data():
    os.makedirs(_SAMPLE_DIR, exist_ok=True)
    uri = [(SAMPLE_WAV_URL, SAMPLE_WAV_PATH), (SAMPLE_MP3_URL, SAMPLE_MP3_PATH), 
          (SAMPLE_GSM_URL, SAMPLE_GSM_PATH), (SAMPLE_WAV_SPEECH_URL, SAMPLE_WAV_SPEECH_PATH), 
          (SAMPLE_TAR_URL, SAMPLE_TAR_PATH)]
    for url, path in uri:
        with open(path, "wb") as file_:
            file_.write(requests.get(url).content)
_fetch_data()

In [7]:
def print_stats(waveform, sample_rate=None, src=None):
    if src:
        print("-" * 10)
        print("Source:", src)
        print("-" * 10)
    if sample_rate:
        print("Sample Rate:", sample_rate)
    print("shape: ", tuple(waveform.shape))
    print("Dtype:", waveform.dtype)
    print(f"- Max: {waveform.max().item():6.3f}")
    print(f"- Min: {waveform.min().item():6.3f}")
    print(f"- Mean: {waveform.mean().item():6.3f}")
    print(f"- Std Dev: {waveform.std().item():6.3f}")
    print()
    print(waveform)
    print()
    

In [8]:
def plot_waveform(waveform, sample_rate, titles="waveform", xlim=None, ylim=None):
    waveform = waveform.numpy()
    num_channels, num_frames = waveform.shape
    time_axis = torch.arange(0, num_frames) / sample_rate
    figure, axes = plt.subplots(num_channels, 1)
    if num_channels == 1:
        axes = [axes]
    for c in range(num_channels):
        axes[c].plot(time_axis, waveform[c], linewidth=1)
        axes[c].grid(True)
        if num_channels> 1:
            axes[c].set_ylabel(f"Channel {c + 1}")
        if xlim:
            axes[c].set_xlim(xlim)
        if ylim:
            axes[c].set_ylim(ylim)
    figure.suptitle(title)
    plt.show(block=False)

In [9]:
def plot_specgram(waveform, sample_rate, title="Spectrogram", xlim=None):
    waveform = waveform.numpy()
    num_channels, num_frames = waveform.shape
    figure, axes = plt.subplots(num_channels, 1)
    if num_channels == 1:
        axes = [axes]
    for c in range(num_channels):
        axes[c].specgram(waveform[c], Fs=sample_rate)
        if num_channels > 1:
            axes[c].set_ylabel(f"Channel {c + 1}")
        if xlim:
            axes[c].set_xlim(xlim)
    figure.suptitle(title)
    plt.show(block=False)

In [10]:
def play_audio(waveform, sample_rate):
    waveform=waveform.numpy()
    num_channels, num_frames = waveform.shape
    if num_channels == 1:
        display(Audio(waveform[0], rate=sample_rate))
    elif num_channels == 2:
        display(Audio((waveform[0], waveform[1]), rate=sample_rate))
    else:
        raise ValueError("Waveform with more than 2 channels are not supported")
        

In [11]:
def _get_sample(path, resample=None):
    effects = [["remix", "1"]]
    if resample:
        effects.extend([
            ["lowpass", f"{resample//2}"],
            ["rate", f"{resample}"]
        ])
    return torchaudio.sox_effects.apply_effects_file(path, effects=effects)

def get_sample(*, resample=None):
    return _get_sample(SAMPLE_WAV_PATH, resample=resample)

def inspect_file(path):
    print("-" * 10)
    print("Source:", path)
    print("-"*10)
    print(f"- File size: {os.path.getsize(path)} bytes")
    print(f"- {torchaudio.info(path)}")

In [12]:
metadata = torchaudio.info(SAMPLE_WAV_PATH)
print(metadata)

AudioMetaData(sample_rate=44100, num_frames=109368, num_channels=2, bits_per_sample=16, encoding=PCM_S)


In [13]:
str(torchaudio.get_audio_backend())

'soundfile'

In [14]:
# metadata = torchaudio.info(SAMPLE_MP3_PATH, format="mp3")
# print(metadata)
# metadata = torchaudio.info(SAMPLE_GSM_PATH, format="gsm")
# print(metadata)

In [15]:
# print("Source:", SAMPLE_WAV_URL)
# with requests.get(SAMPLE_WAV_URL, stream=True) as response:
#     metadata = torchaudio.info(response.raw)
# print(metadata)

In [16]:
# print("Source", SAMPLE_MP3_URL)
# with requests.get(SAMPLE_MP3_URL, stream=True) as response:
#     metadata = torchaudio.info(response.raw, format="mp3")
#     print(f"Fetched {response.raw.tell()} bytes")
# print(metadata)

In [ ]:
waveform, sample_rate = torchaudio.load(SAMPLE_WAV_SPEECH_PATH)
print_stats(waveform, sample_rate=sample_rate)
plot_waveform(waveform, sample_rate)
plot_specgram(waveform, sample_rate)
play_audio(waveform, sample_rate)

Sample Rate: 16000
shape:  (1, 54400)
Dtype: torch.float32
- Max:  0.668
- Min: -1.000
- Mean:  0.000
- Std Dev:  0.122

tensor([[0.0183, 0.0180, 0.0180,  ..., 0.0018, 0.0019, 0.0032]])



# Audio Resampling

In [2]:
import torch
import torchaudio
import torchaudio.functional as F
import torchaudio.transforms as T
print(torch.__version__)
print(torchaudio.__version__)

1.9.1+cpu
0.9.1


In [3]:
import math
import time
# import librosa
import matplotlib.pyplot as plt
import pandas as pd
from IPython.display import Audio, display
DEFAULT_OFFSET = 201
SWEEP_MAX_SAMPLE_RATE = 48000
DEFAULT_LOWPASS_FILTER_WIDTH = 6
DEFAULT_ROLLOFF = 0.99
DEFAULT_RESAMPLING_METHOD = "sinc_interpolation"

In [4]:
def _get_log_freq(sample_rate, max_sweep_rate, offset):
    start, stop = math.log(offset), math.log(offset + max_sweep_rate // 2)
    return torch.exp(torch.linspace(start, stop, sample_rate, dtype=torch.double)) - offset

In [5]:
def _get_inverse_log_freq(freq, sample_rate, offset):
    half = sample_rate // 2
    return sample_rate * (math.log(1 + freq / offset) / math.log(1 + half / offset))

In [6]:
def _get_freq_ticks(sample_rate, offset, f_max):
    time, freq = [], []
    for exp in range(2, 5):
        for v in range(1, 10):
            f = v * 10 ** exp
            if f < sample_rate // 2:
                t = _get_inverse_log_freq(f, sample_rate, offset) / sample_rate
                time.append(t)
                freq.append(f)
    t_max = _get_inverse_log_freq(f_max, sample_rate, offset) / sample_rate
    time.append(t_max)
    freq.append(f_max)
    return time, freq

In [7]:
def get_sine_sweep(sample_rate, offset=DEFAULT_OFFSET):
    max_sweep_rate = sample_rate
    freq = _get_log_freq(sample_rate, max_sweep_rate, offset)
    delta = 2 * math.pi * freq / sample_rate
    cummulative = torch.cumsum(delta, dim=0)
    signal = torch.sin(cummulative).unsqueeze(dim=0)
    return signal

In [8]:
def plot_sweep(waveform, sample_rate, title, max_sweep_rate=SWEEP_MAX_SAMPLE_RATE, offset=DEFAULT_OFFSET):
    x_ticks = [100, 500, 1000, 5000, 10000, 20000, max_sweep_rate // 2]
    y_ticks = [1000, 5000, 10000, 20000, sample_rate // 2]
    time, freq = _get_freq_ticks(max_sweep_rate, offset, sample_rate // 2)
    freq_x = [f if f in x_ticks and f <= max_sweep_rate // 2 else None for f in freq]
    freq_y = [f for f in freq if f >= 1000 and f in y_ticks and f <= sample_rate // 2]
    figure, axis = plt.subplots(1, 1)
    axis.specgram(waveform[0].numpy(), Fs=sample_rate)
    plt.yticks(freq_y, freq_y)
    plt.xticks(time, freq_x)
    axis.set_xlabel("Original Signal Frequence (Hz, log scale)")
    axis.set_ylabel("Waveform Frequency (HZ)")
    axis.xaxis.grid(True, alpha=0.67)
    axis.yaxis.grid(True, alpha=0.67)
    figure.suptitle(f"{title} (sample rate: {sample_rate} HZ)")
    plt.show(block=True)

In [9]:
def play_audio(waveform, sample_rate):
    waveform = waveform.numpy()
    num_channels, num_frames = waveform.shape
    if num_channels == 1:
        display(Audio(waveform[0], rate=sample_rate))
    elif num_chanels == 2:
        display(Audio(waveform[0], waveform[1]), rate=sample_rate)
    else:
        raise ValueError("Waveform with more than 2 channels are not supported")
    

In [10]:
def plot_specgram(waveform, sample_rate, title="Spectrogram", xlim=None):
    waveform = waveform.numpy()
    num_channels, num_frames = waveform.shape
    figure, axes = plt.subplot(num_channels, 1)
    if num_channels == 1:
        axes = [axes]
    for c in range(num_channels):
        axes[c].specgram(waveform[c], Fs=sample_rate)
        if num_channels > 1:
            axes[c].set_ylabel(f"Channels {c + 1}")
        if xlim:
            axes[c].set_xlim(xlim)
    figure.suptitle(title)
    plt.show(block=False)

In [28]:
def benchmark_resample(method, waveform, sample_rate, resample_rate, lowpass_filter_width=DEFAULT_LOWPASS_FILTER_WIDTH,
                      rolloff=DEFAULT_ROLLOFF, resampling_method=DEFAULT_RESAMPLING_METHOD, beta=None, 
                       librosa_type=None, iters=5):
    if method == "functional":
        begin = time.time()
        for _ in range(iters):
            F.resample(waveform, sample_rate, resample_rate, lowpass_filter_width=lowpass_filter_width, rolloff=rolloff, 
                    resampling_method=resampling_method)
        elapsed = time.time() - begin
        return elapsed / iters
    elif method == "transforms":
        resampler = T.Resample(sample_rate, resample_rate, lowpass_filter_width=lowpass_filter_width, rolloff=rolloff, 
                              resampling_method=resampling_method, dtype=waveform.dtype)
        begin = time.time()
        for _ in range(iters):
            resampler(waveform)
        elapsed = time.time() - begin
        return elapsed / iters
    elif method == "librosa":
        waveform_np = waveform.squeeze().numpy()
        begin = time.time()
        for _ in range(iters):
            librosa.resample(waveform_np, orig_sr=sample_rate, target_sr=resample_rate, res_type=librosa_type)
        elapsed = time.time() - begin
        return elapsed / iters
    

In [12]:
sample_rate = 48000
resample_rate = 32000
waveform = get_sine_sweep(sample_rate)


In [13]:
play_audio(waveform, sample_rate)

In [14]:
sample_rate = 48000
resample_rate = 32000
resampled_waveform = F.resample(waveform, sample_rate, resample_rate, resampling_method="sinc_interpolation")

In [36]:
configs = {
    "downsample (48 -> 44.1 kHz)": [48000, 44100],
    "downsample (16 -> 8kHz)": [16000, 8000],
    "upsample (44.1 -> 48kHz)": [44100, 48000],
    "upsample (8 -> 16 kHz)": [8000, 16000],
}
for label in configs:
    times, rows = [], []
    sample_rate = configs[label][0]
    resample_rate = configs[label][1]
    waveform = get_sine_sweep(sample_rate)
    
    f_time = benchmark_resample("functional", waveform, sample_rate, resample_rate, lowpass_filter_width=64)
    t_time = benchmark_resample("transforms", waveform, sample_rate, resample_rate, lowpass_filter_width=64)
    times.append([None, 1000 * f_time, 1000 * t_time])
    rows.append("sinc (width 64)")
    
    f_time = benchmark_resample("functional", waveform, sample_rate, resample_rate, lowpass_filter_width=64)
    t_time = benchmark_resample("transforms", waveform, sample_rate, resample_rate, lowpass_filter_width=64)
    times.append([None, 1000 * f_time, 1000 * t_time])
    rows.append("sinc (width 64)")
    
    t_time = benchmark_resample("transforms", waveform, sample_rate, resample_rate, lowpass_filter_width=64, 
                                rolloff=0.85
                               , resampling_method="kaiser_window", beta=8.555504641634386)
    times.append([1000 * f_time * t_time])

# Audio Data Augmentation

In [37]:
import torch
import torchaudio
import torchaudio.functional as F
print(torch.__version__)
print(torchaudio.__version__)

1.9.1+cpu
0.9.1


In [38]:
import math
import os

import matplotlib.pyplot as plt
import requests
from IPython.display import Audio, display


_SAMPLE_DIR = "_assets"

SAMPLE_WAV_URL = "https://pytorch-tutorial-assets.s3.amazonaws.com/steam-train-whistle-daniel_simon.wav"
SAMPLE_WAV_PATH = os.path.join(_SAMPLE_DIR, "steam.wav")

SAMPLE_RIR_URL = "https://pytorch-tutorial-assets.s3.amazonaws.com/VOiCES_devkit/distant-16k/room-response/rm1/impulse/Lab41-SRI-VOiCES-rm1-impulse-mc01-stu-clo.wav"  # noqa: E501
SAMPLE_RIR_PATH = os.path.join(_SAMPLE_DIR, "rir.wav")

SAMPLE_WAV_SPEECH_URL = "https://pytorch-tutorial-assets.s3.amazonaws.com/VOiCES_devkit/source-16k/train/sp0307/Lab41-SRI-VOiCES-src-sp0307-ch127535-sg0042.wav"  # noqa: E501
SAMPLE_WAV_SPEECH_PATH = os.path.join(_SAMPLE_DIR, "speech.wav")

SAMPLE_NOISE_URL = "https://pytorch-tutorial-assets.s3.amazonaws.com/VOiCES_devkit/distant-16k/distractors/rm1/babb/Lab41-SRI-VOiCES-rm1-babb-mc01-stu-clo.wav"  # noqa: E501
SAMPLE_NOISE_PATH = os.path.join(_SAMPLE_DIR, "bg.wav")

os.makedirs(_SAMPLE_DIR, exist_ok=True)

In [40]:
def _fetch_data():
    uri = [
        (SAMPLE_WAV_URL, SAMPLE_WAV_PATH),
        (SAMPLE_RIR_URL, SAMPLE_RIR_PATH),
        (SAMPLE_WAV_SPEECH_URL, SAMPLE_WAV_SPEECH_PATH),
        (SAMPLE_NOISE_URL, SAMPLE_NOISE_PATH)
    ]
    for url, path in uri:
        with open(path, "wb") as file_:
            file_.write(requests.get(url).content)
_fetch_data()

In [47]:
def _get_sample(path, resample=None):
    effects = [["remix", "1"]]
    if resample:
        effects.extend([
            ["lowpass", f"{resample // 2}"],
            ["rate", f"{resample}"]
        ])
    return torchaudio.sox_effects.apply_effects_file(path, effects=effects)

In [42]:
def get_sample(*, resample=None):
    return _get_sample(SAMPLE_WAV_PATH, resample=resample)

def get_speech_sample(*, resample=None):
    return _get_sample(SAMPLE_WAV_SPEECH_PATH, resample=resample)

def plot_waveform(waveform, sample_rate, title="Waveform", xlim=None, ylim=None):
    waveform = waveform.numpy()
    num_channels, num_frames = waveform.shape
    time_axis = torch.arange(0, num_frames) / sample_rate
    
    figure, axes = plt.subplot(num_channels, 1)
    if num_channels == 1:
        axes = [axes]
    for c in range(num_channels):
        axes[c].plot(time_axis, waveform[c], linewidth=1)
        axes[c].grid(True)
        if num_channels > 1:
            axes[c].set_ylabel(f"Channel {c + 1}")
        if xlim:
            axes[c].set_xlim(xlim)
        if ylim:
            axes[c].set_ylim(ylim)
    figure.suptitle(title)
    plt.show(block=False)

In [43]:
def print_stats(waveform, sample_rate=None, src=None):
    if src:
        print("-" * 10)
        print("Source", src)
        print("-" * 10)
    if sample_rate:
        print("Sample Rate:", sample_rate)
    print("Shape", tuple(waveform.shape))
    print("Dtype", waveform.dtype)
    print(f" - Max: {waveform.max().item():6.3f}")
    print(f" - Min: {waveform.min().item():6.3f}")
    print(f" - Mean: {waveform.mean().item():6.3f}")
    print(f" - Std Dev: {waveform.std().item():6.3f}")
    print()
    print(waveform)
    print()

In [44]:
def play_audio(waveform, sample_rate):
    waveform = waveform.numpy()
    num_channels, num_frames = waveform.shape
    if num_channels == 1:
        return Audio(waveform[0], rate=sample_rate)
    elif num_channels == 2:
        return Audio(waveform[0], waveform[1], rate=sample_rate)
    else:
        raise ValueError("Waveform width more than 2 channels are not supported")

In [45]:
def get_rir_sample(*, resample=None, processed=False):
    rir_raw, sample_rate = _get_sample(SAMPLE_RIR_PATH, resample=resample)
    if not processed:
        return rir_raw, sample_rate
    rir = rir_raw[:, int(sample_rate * 1.01) : int(sample_rate * 1.3)]
    rir = rir / torch.norm(rir, p = 2)
    rir = torch.flip(rir, [1])
    return rir, sample_rate
def get_noise_sample(*, resample=None):
    return _get_sample(SAMPLE_NOISE_PATH, resample=resample)

# Torch Model

In [53]:
import os
import IPython
import matplotlib
import matplotlib.pyplot as plt
import requests
import torch
import torchaudio
matplotlib.rcParams["figure.figsize"] = [16.0, 4.8]
torch.random.manual_seed(0)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(torch.__version__)
print(torchaudio.__version__)
print(device)

1.9.1+cpu
0.9.1
cpu


In [54]:
SPEECH_URL = "https://pytorch-tutorial-assets.s3.amazonaws.com/VOiCES_devkit/source-16k/train/sp0307/Lab41-SRI-VOiCES-src-sp0307-ch127535-sg0042.wav"  # noqa: E501
SPEECH_FILE = "_assets/speech.wav"

if not os.path.exists(SPEECH_FILE):
    os.makedirs("_assets", exist_ok=True)
    with open(SPEECH_FILE, "wb") as file:
        file.write(requests.get(SPEECH_URL).content)

# torch vision

In [6]:
import torchvision.transforms as transforms
import torch

In [8]:
transform = torch.nn.Sequential(transforms.CenterCrop(10), transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225)))
script_transforms = torch.jit.script(transform)

In [10]:
transforms.Compose([
    transforms.CenterCrop(10),
    transforms.PILToTensor(),
    transforms.ConvertImageDtype(torch.float),
])

Compose(
    CenterCrop(size=(10, 10))
    PILToTensor()
    ConvertImageDtype()
)

In [11]:
transforms.Grayscale(5)

Grayscale(num_output_channels=5)

In [14]:
transform = transforms.RandomApply(torch.nn.ModuleList([
    transforms.ColorJitter()
]), p=0.3)

In [16]:
transfrom = transforms.Compose([
    transforms.RandomHorizontalFlip(),
    transforms.PILToTensor(),
    transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225)),
    transforms.RandomErasing()
])

In [18]:
import torchvision.transforms.functional as TF
import random
class MyRotationTransform:
    def __init__(self, angles):
        self.angles = angles
    def __call__(self, x):
        angle = random.choice(self.angles)
        return TF.rotate(x, angles)
rotation_transform = MyRotationTransform(angles=[-30, -15, 0, 15, 30])

In [19]:
import torchvision

In [20]:
inputs = torch.rand(4, 3, 10, 10)
kh, kw = 3, 3
weight = torch.rand(5, 3, kh, kw)
offset = torch.rand(4, 2 * kh * kw, 8, 8)
mask = torch.rand(4, kh * kw, 8, 8)
out = torchvision.ops.deform_conv2d(inputs, offset, weight, mask=mask)
print(out.shape)

torch.Size([4, 5, 8, 8])


In [22]:
m = torchvision.ops.MultiScaleRoIAlign(['feat1', 'feat2'], 3, 2)
i = {}
i["feat1"] = torch.rand(1, 5, 64, 64)
i["feat2"] = torch.rand(1, 5, 32, 32)
i["feat3"] = torch.rand(1, 5, 16, 16)
boxes = torch.rand(6, 4) * 256
boxes[:, 2:] += boxes[:, :2]
image_sizes = [(512, 512)]
output = m(i, [boxes], image_sizes)
print(output.shape)

torch.Size([6, 5, 3, 3])


In [23]:
m = torchvision.ops.FeaturePyramidNetwork([10, 20, 30], 5)
x = {}
x["feat0"] = torch.rand(1, 10, 64, 64)
x["feat2"] = torch.rand(1, 20, 16, 16)
x["feat3"] = torch.rand(1, 30, 8, 8)
output = m(x)
print([(k, v.shape) for k, v in output.items()])

[('feat0', torch.Size([1, 5, 64, 64])), ('feat2', torch.Size([1, 5, 16, 16])), ('feat3', torch.Size([1, 5, 8, 8]))]


# Torch Text

In [1]:
import torchtext

In [4]:
import torch
SDP = torchtext.nn.ScaledDotProduct(dropout=0.1)
q = torch.randn(21, 256, 3)
k = v = torch.randn(21, 256, 3)
attn_output, attn_weights = SDP(q, k, v)
print(attn_output.shape)

torch.Size([21, 256, 3])


In [5]:
from torchtext.nn import MultiheadAttentionContainer, InProjContainer, ScaledDotProduct
embed_dim, num_heads, bsz = 10, 5, 64
in_prj_ontainer=InProjContainer(torch.nn.Linear(embed_dim, embed_dim), 
                torch.nn.Linear(embed_dim, embed_dim),
                torch.nn.Linear(embed_dim, embed_dim))
MHA = MultiheadAttentionContainer(num_heads, in_prj_ontainer, ScaledDotProduct(), torch.nn.Linear(embed_dim, 
                                                                                                    embed_dim))
query = torch.rand((21, bsz, embed_dim))
key = value = torch.rand((16, bsz, embed_dim))
attn_output, attn_weights = MHA(query, key, value)
print(attn_output.shape)

torch.Size([21, 64, 10])


In [6]:
from torchtext.data.metrics import bleu_score
candidate_corpus = [['My', "full", "pytorch", "test"], ["Another", "Sentence"]]
references_corpus = [[["My", "full", "pytorch", "test"], ["Completely", "Different"]], [["No", "Match"]]]
bleu_score(candidate_corpus, references_corpus)

0.8408964276313782

In [2]:
import torchtext
from torchtext.data import get_tokenizer
tokenizer = get_tokenizer("basic_english")
tokens = tokenizer("You can now install torchtext uning pip!")
tokens

['you', 'can', 'now', 'install', 'torchtext', 'uning', 'pip', '!']

In [4]:
from torchtext.data.utils import ngrams_iterator

In [9]:
list(ngrams_iterator(tokens, 2))

['you',
 'can',
 'now',
 'install',
 'torchtext',
 'uning',
 'pip',
 '!',
 'you can',
 'can now',
 'now install',
 'install torchtext',
 'torchtext uning',
 'uning pip',
 'pip !']

In [13]:
from torchtext.vocab import vocab
from collections import Counter, OrderedDict
counter = Counter(["a", "a", "b", "b"])
sorted_by_freq_tuples = sorted(counter.items(), key=lambda x: x[1], reverse=True)
ordered_dict = OrderedDict(sorted_by_freq_tuples)
v1 = vocab(ordered_dict)
print(v1['a'])
tokens = ['e', 'd', 'c', 'b', 'a']
unk_token = '<unk>'
default_index = -1
v2 = vocab(OrderedDict([(token, 1) for token in tokens]), specials=[unk_token])
v2.set_default_index(default_index)
print(v2["<unk>"])
print(v2['out of vocab'])
v2.set_default_index(v2[unk_token])
v2["out of vocab"] is v2[unk_token]

0
0
-1


True