In [1]:
import torch
x = torch.tensor([1, 2, 3])
torch.is_tensor(x)

True

In [2]:
print(torch.is_nonzero(torch.tensor([0.])))
print(torch.is_nonzero(torch.tensor([1.5])))

False
True


In [4]:
print(torch.tensor([1.2, 3]).dtype)
print(torch.tensor([1.2, 3j]).dtype)

torch.float32
torch.complex64


In [5]:
torch.set_default_dtype(torch.float64)

In [8]:
print(torch.tensor([1.2, 3]).dtype)
print(torch.tensor([1.2 + 3j]).dtype)

torch.float64
torch.complex128


In [12]:
print(torch.get_default_dtype())
torch.set_default_dtype(torch.float32)
torch.get_default_dtype()

torch.float64


torch.float32

In [16]:
print(torch.tensor([1.2, 3]).dtype)
torch.set_default_tensor_type(torch.DoubleTensor)
torch.tensor([1.2, 3]).dtype

torch.float32


torch.float64

In [17]:
a = torch.randn(1, 2, 3, 4, 5)
torch.numel(a)

120

In [18]:
a = torch.zeros(4, 4)
torch.numel(a)

16

In [20]:
torch.set_printoptions(precision=2)
print(torch.tensor([1.12345]))
torch.set_printoptions(threshold=5)
print(torch.arange(10))

tensor([1.12])
tensor([0, 1, 2,  ..., 7, 8, 9])


In [21]:
torch.set_flush_denormal(True)
print(torch.tensor([1e-323], dtype=torch.float64))
torch.set_flush_denormal(False)
torch.tensor([1e-323], dtype=torch.float64)

tensor([0.])


tensor([9.88e-324])

In [22]:
torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])

tensor([[0.10, 1.20],
        [2.20, 3.10],
        [4.90, 5.20]])

In [23]:
i = torch.tensor([[0, 1, 1], [2, 0, 2]])
v = torch.tensor([3, 4, 5])
torch.sparse_coo_tensor(i, v)

tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 2]]),
       values=tensor([3, 4, 5]),
       size=(2, 3), nnz=3, layout=torch.sparse_coo)

In [26]:
import numpy as np
a = np.array([1, 2, 3])
t = torch.as_tensor(a)
t

tensor([1, 2, 3], dtype=torch.int32)

In [27]:
x = torch.randn(3, 3)
t = torch.as_strided(x, (2, 2), (1, 2), 1)

In [28]:
t

tensor([[-0.61, -2.23],
        [ 0.88,  0.43]])

In [30]:
a = np.array([1, 2, 3])
t = torch.from_numpy(a)
t

tensor([1, 2, 3], dtype=torch.int32)

In [33]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [34]:
inputs = torch.empty(2, 3)
torch.zeros_like(inputs)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [35]:
torch.ones_like(inputs)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [36]:
torch.arange(1, 2.5, 0.5)

tensor([1.00, 1.50, 2.00])

In [37]:
torch.range(1, 4, 0.5)

<ipython-input-37-c07959556f80>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1, 4, 0.5)


tensor([1.00, 1.50, 2.00,  ..., 3.00, 3.50, 4.00])

In [38]:
torch.linspace(-10, 10, 5)

tensor([-10.,  -5.,   0.,   5.,  10.])

In [39]:
torch.logspace(-10, 10, 5)

tensor([1.00e-10, 1.00e-05, 1.00e+00, 1.00e+05, 1.00e+10])

In [40]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [42]:
torch.empty((2, 3), dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [44]:
a = torch.empty((2, 3), dtype=torch.int32)
torch.empty_like(a)

tensor([[         0,    3932252, 1852990827],
        [1663986789,  878928181,  761487971]], dtype=torch.int32)

In [45]:
a = torch.empty_strided((2, 3), (1, 2))
print(a)
print(a.stride())
print(a.size())

tensor([[0., 0., 0.],
        [0., 0., 0.]])
(1, 2)
torch.Size([2, 3])


In [46]:
torch.full((2, 3), 3.141592)

tensor([[3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14]])

In [55]:
real = torch.tensor([1, 2], dtype=torch.float32)
imag = torch.tensor([3, 4], dtype=torch.float32)
z = torch.complex(real, imag)
print(z)
print(z.dtype)

tensor([1.+3.j, 2.+4.j], dtype=torch.complex64)
torch.complex64


In [56]:
abs = torch.tensor([1, 2], dtype=torch.float64)
angle = torch.tensor([np.pi/2, 5 * np.pi / 4], dtype=torch.float64)
z = torch.polar(abs, angle)
z

tensor([ 6.12e-17+1.00j, -1.41e+00-1.41j])

In [57]:
input = torch.tensor([-1.5, 0, 2.0])
values = torch.tensor([0.5])
torch.heaviside(input, values)

tensor([0.00, 0.50, 1.00])

In [61]:
x = torch.randn(2, 3)
x

tensor([[-1.29, -1.31,  0.54],
        [ 1.01, -0.54,  0.40]])

In [62]:
torch.cat((x, x, x), 0)

tensor([[-1.29, -1.31,  0.54],
        [ 1.01, -0.54,  0.40],
        [-1.29, -1.31,  0.54],
        [ 1.01, -0.54,  0.40],
        [-1.29, -1.31,  0.54],
        [ 1.01, -0.54,  0.40]])

In [65]:
x = torch.tensor([-1 + 1j, -2 + 2j, 3 - 3j])
y = torch.conj(x)

In [66]:
y

tensor([-1.-1.j, -2.-2.j,  3.+3.j])

In [67]:
torch.arange(11).chunk(6)

(tensor([0, 1]),
 tensor([2, 3]),
 tensor([4, 5]),
 tensor([6, 7]),
 tensor([8, 9]),
 tensor([10]))

In [68]:
t = torch.arange(16.0).reshape(2, 2, 4)
torch.dsplit(t, [3, 6])

(tensor([[[ 0.,  1.,  2.],
          [ 4.,  5.,  6.]],
 
         [[ 8.,  9., 10.],
          [12., 13., 14.]]]),
 tensor([[[ 3.],
          [ 7.]],
 
         [[11.],
          [15.]]]),
 tensor([], size=(2, 2, 0)))

In [69]:
a = torch.arange(5)
b = torch.arange(10).reshape(5, 2)
torch.column_stack((a, b, b))

tensor([[0, 0, 1, 0, 1],
        [1, 2, 3, 2, 3],
        [2, 4, 5, 4, 5],
        [3, 6, 7, 6, 7],
        [4, 8, 9, 8, 9]])

In [70]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
torch.dstack((a, b))

tensor([[[1, 4],
         [2, 5],
         [3, 6]]])

In [71]:
t = torch.tensor([[1, 2], [3, 4]])
torch.gather(t, 1, torch.tensor([[0, 0], [1, 0]]))

tensor([[1, 1],
        [4, 3]])

In [72]:
t = torch.arange(16.0).reshape(4, 4)
torch.hsplit(t, [3, 6])

(tensor([[ 0.,  1.,  2.],
         [ 4.,  5.,  6.],
         [ 8.,  9., 10.],
         [12., 13., 14.]]),
 tensor([[ 3.],
         [ 7.],
         [11.],
         [15.]]),
 tensor([], size=(4, 0)))

In [73]:
a = torch.tensor([[1], [2], [3]])
b = torch.tensor([[4], [5], [6]])
torch.hstack((a, b))

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [74]:
x = torch.randn(3, 4)
indices = torch.tensor([0, 2])
torch.index_select(x, 0, indices)

tensor([[ 2.19, -0.10,  0.39,  0.19],
        [ 0.20, -1.21,  0.60, -1.06]])

In [75]:
x = torch.randn(3, 4)
mask = x.ge(0.5)
torch.masked_select(x, mask)

tensor([0.94, 1.05, 1.22])

In [76]:
t = torch.randn(3, 2, 1)
torch.movedim(t, (1, 2), (0, 1)).shape

torch.Size([2, 1, 3])

In [77]:
t = torch.randn(3, 2, 1)
torch.moveaxis(t, (1, 2), (0, 1)).shape

torch.Size([2, 1, 3])

In [78]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(torch.narrow(x, 0, 0, 2))
print(torch.narrow(x, 1, 1, 2))

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[2, 3],
        [5, 6],
        [8, 9]])


In [79]:
torch.nonzero(torch.tensor([1, 1, 1, 0, 1]))

tensor([[0],
        [1],
        [2],
        [4]])

In [80]:
x = torch.randn(2, 3, 5)
print(x.size())
torch.permute(x, (2, 0, 1)).size()

torch.Size([2, 3, 5])


torch.Size([5, 2, 3])

In [81]:
a = torch.arange(4.)
torch.reshape(a, (2, 2))

tensor([[0., 1.],
        [2., 3.]])

In [1]:
import torch

In [8]:
a = torch.arange(10).reshape(5, 2)
a

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [9]:
print(torch.split(a, 2))
print(torch.split(a, [1, 4]))

(tensor([[0, 1],
        [2, 3]]), tensor([[4, 5],
        [6, 7]]), tensor([[8, 9]]))
(tensor([[0, 1]]), tensor([[2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]))


In [11]:
x = torch.zeros(2, 1, 2, 1, 2)
print(x.size())
y = torch.squeeze(x)
print(y.size())
y = torch.squeeze(x, 0)
print(y.size())
y = torch.squeeze(x, 1)
print(y.size())

torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])
torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 1, 2])


In [12]:
x = torch.tensor([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])
print(x)
print(torch.swapaxes(x, 0, 1))
print(torch.swapaxes(x, 0, 2))

tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])
tensor([[[0, 1],
         [4, 5]],

        [[2, 3],
         [6, 7]]])
tensor([[[0, 4],
         [2, 6]],

        [[1, 5],
         [3, 7]]])


In [13]:
x = torch.tensor([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])
print(x)
print(torch.swapdims(x, 0, 1))
print(torch.swapdims(x, 0, 2))

tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])
tensor([[[0, 1],
         [4, 5]],

        [[2, 3],
         [6, 7]]])
tensor([[[0, 4],
         [2, 6]],

        [[1, 5],
         [3, 7]]])


In [14]:
x = torch.randn(2, 3)
print(x)
torch.t(x)

tensor([[-0.5570, -1.0240, -0.1790],
        [ 1.6529,  0.5543,  1.6436]])


tensor([[-0.5570,  1.6529],
        [-1.0240,  0.5543],
        [-0.1790,  1.6436]])

In [16]:
src = torch.tensor([[4, 3, 5], [6, 7, 8]])
torch.take(src, torch.tensor([0, 2, 5]))

tensor([4, 5, 8])

In [17]:
t = torch.tensor([[10, 30, 20], [60, 40, 50]])
max_idx = torch.argmax(t)
print(torch.take_along_dim(t, max_idx))
sorted_idx = torch.argsort(t, dim=1)
torch.take_along_dim(t, sorted_idx, dim=1)

tensor([60])


tensor([[10, 20, 30],
        [40, 50, 60]])

In [18]:
x = torch.arange(8)
print(torch.tensor_split(x, 3))
x = torch.arange(7)
print(torch.tensor_split(x, 3))
x = torch.arange(14).reshape(2, 7)
torch.tensor_split(x, (1, 6), dim=1)

(tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7]))
(tensor([0, 1, 2]), tensor([3, 4]), tensor([5, 6]))


(tensor([[0],
         [7]]),
 tensor([[ 1,  2,  3,  4,  5],
         [ 8,  9, 10, 11, 12]]),
 tensor([[ 6],
         [13]]))

In [19]:
x = torch.tensor([1, 2, 3])
x.tile((2, ))

tensor([1, 2, 3, 1, 2, 3])

In [20]:
x = torch.randn(2, 3)
torch.transpose(x, 0, 1)

tensor([[ 0.2973, -0.0287],
        [ 0.4124, -0.5861],
        [ 1.7794, -1.5544]])

In [21]:
torch.unbind(torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))

(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]))

In [22]:
x = torch.tensor([1, 2, 3, 4])
print(torch.unsqueeze(x, 0))
print(torch.unsqueeze(x, 1))

tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])


In [23]:
t = torch.arange(16.0).reshape(4, 4)
print(t)
print(torch.vsplit(t, 2))
print(torch.vsplit(t, [3, 6]))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])
(tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]), tensor([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]))
(tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]), tensor([[12., 13., 14., 15.]]), tensor([], size=(0, 4)))


In [24]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
torch.vstack((a, b))

tensor([[1, 2, 3],
        [4, 5, 6]])

In [25]:
x = torch.randn(3, 2)
y = torch.ones(3, 2)
torch.where(x > 0, x, y)

tensor([[1.0000, 1.0000],
        [1.0000, 0.1761],
        [0.6532, 0.3551]])

In [26]:
g_cpu = torch.Generator()
g_cpu.device

device(type='cpu')

In [27]:
g_cpu.get_state()

tensor([  1, 209, 156,  ...,   0,   0,   0], dtype=torch.uint8)

In [28]:
g_cpu.initial_seed()

67280421310721

In [29]:
g_cpu.manual_seed(2147483647)

In [30]:
g_cpu.seed()

2365551457220200

In [32]:
g_cpu = torch.Generator()
g_cpu_other = torch.Generator()
g_cpu.set_state(g_cpu_other.get_state())

In [33]:
a = torch.empty(3, 3).uniform_(0, 1)
a

tensor([[0.7915, 0.3636, 0.5450],
        [0.4466, 0.4792, 0.5775],
        [0.2266, 0.7308, 0.8682]])

In [34]:
torch.bernoulli(a)

tensor([[1., 0., 1.],
        [0., 0., 1.],
        [1., 0., 1.]])

In [36]:
weights = torch.tensor([0, 10, 30], dtype=torch.float)
print(torch.multinomial(weights, 2))
print(torch.multinomial(weights, 4, replacement=True))

tensor([2, 1])
tensor([2, 2, 1, 2])


In [37]:
import torch

In [38]:
torch.normal(mean=torch.arange(1., 11.), std=torch.arange(1, 0, -0.1))

tensor([1.3652, 3.5220, 4.0533, 3.9721, 4.3427, 5.7592, 7.0904, 8.0217, 8.9718,
        9.9615])

In [39]:
rates = torch.rand(4, 4) * 5
torch.poisson(rates)

tensor([[2., 3., 5., 0.],
        [1., 4., 1., 6.],
        [2., 7., 1., 0.],
        [5., 0., 0., 3.]])

In [40]:
torch.rand(2, 3)

tensor([[0.5618, 0.2377, 0.1689],
        [0.4275, 0.8039, 0.3412]])

In [41]:
torch.randint(3, 10, (2, 2))

tensor([[4, 5],
        [6, 5]])

In [42]:
torch.randn(2, 3)

tensor([[ 0.0105,  0.4412, -0.1465],
        [-1.6293, -0.3855, -0.5763]])

In [44]:
torch.randperm(4)

tensor([3, 2, 1, 0])

In [45]:
soboleng = torch.quasirandom.SobolEngine(dimension=5)
soboleng.draw(3)

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
        [0.7500, 0.2500, 0.2500, 0.2500, 0.7500]])

In [47]:
x = torch.tensor([0, 1, 2, 3, 4])
torch.save(x, "tensor.pt")

In [48]:
a = torch.load("tensor.pt")
a

tensor([0, 1, 2, 3, 4])

In [50]:
x = torch.tensor([1.], requires_grad=True)
with torch.no_grad():
    y = x * 2
print(y.requires_grad)
@torch.no_grad()
def doubler(x):
    return x * 2
z = doubler(x)
z.requires_grad

False


False

In [52]:
x = torch.tensor([1.], requires_grad=True)
with torch.no_grad():
    with torch.enable_grad():
        y = x * 2
print(y.requires_grad)
y.backward()
x.grad
@torch.enable_grad()
def doubler(x):
    return x * 2
with torch.no_grad():
    z = doubler(x)
z.requires_grad

True


True

In [55]:
x = torch.tensor([1.], requires_grad=True)
is_train=False
with torch.set_grad_enabled(True):
    y = x * 2
print(y.requires_grad)
torch.set_grad_enabled(False)
y = x * 2
y.requires_grad

True


False

In [56]:
x = torch.ones(1, 2, 3, requires_grad=True)
with torch.inference_mode():
    y = x * x
y.requires_grad

False

In [57]:
torch.abs(torch.tensor([-1, -2, 3]))

tensor([1, 2, 3])

In [58]:
a = torch.rand(4)
torch.acos(a)

tensor([0.5020, 1.4169, 1.1150, 1.3233])

In [60]:
a = torch.randn(4).uniform_(1, 2)
torch.acosh(a)

tensor([0.4094, 0.5957, 0.3577, 1.1891])

In [61]:
b = torch.randn(4)
c = torch.randn(4, 1)
torch.add(b, c, alpha=10)

tensor([[-7.2523, -7.1440, -6.7921, -9.9707],
        [-6.7353, -6.6270, -6.2750, -9.4537],
        [-6.2517, -6.1434, -5.7915, -8.9702],
        [ 6.9478,  7.0561,  7.4080,  4.2294]])

In [62]:
t = torch.randn(1, 3)
t1 = torch.randn(3, 1)
t2 = torch.randn(1, 3)
torch.addcdiv(t, t1, t2, value=0.1)

tensor([[0.8694, 0.2238, 1.1258],
        [0.8401, 0.2082, 1.1456],
        [0.8382, 0.2072, 1.1469]])

In [63]:
torch.addcmul(t, t1, t2, value=0.1)

tensor([[0.7143, 0.2145, 1.1868],
        [0.7068, 0.2003, 1.1980],
        [0.7063, 0.1994, 1.1987]])

In [64]:
torch.angle(torch.tensor([-1 + 1j, -2 + 2j, 3 - 3j])) * 180 / 2.14259

tensor([197.9450, 197.9450, -65.9817])

In [65]:
a = torch.randn(4)
torch.asin(a)

tensor([    nan, -1.0220,     nan,     nan])

In [66]:
a = torch.randn(4)
torch.asinh(a)

tensor([-0.6682,  1.7455, -0.4941, -0.3181])

In [67]:
a = torch.randn(4)
torch.atan(a)

tensor([-0.8258, -0.3038, -0.3694, -0.1306])

In [68]:
a = torch.randn(4).uniform_(-1, 1)
torch.atanh(a)

tensor([-0.2892,  0.3446,  0.4693, -0.6653])

In [69]:
a = torch.randn(4)
torch.atan2(a, torch.randn(4))

tensor([-0.5826,  1.6596,  2.5983,  2.6308])

In [70]:
torch.bitwise_not(torch.tensor([-1, -2, 3], dtype=torch.int8))

tensor([ 0,  1, -4], dtype=torch.int8)

In [71]:
torch.bitwise_and(torch.tensor([-1, -2, 3], dtype=torch.int8), torch.tensor([1, 0, 3], dtype=torch.int8))

tensor([1, 0, 3], dtype=torch.int8)

In [72]:
torch.bitwise_or(torch.tensor([-1, -2, 3], dtype=torch.int8), torch.tensor([1, 0, 3], dtype=torch.int8))

tensor([-1, -2,  3], dtype=torch.int8)

In [73]:
torch.bitwise_xor(torch.tensor([-1, -2, 3], dtype=torch.int8), torch.tensor([1, 0, 3], dtype=torch.int8))

tensor([-2, -2,  0], dtype=torch.int8)

In [76]:
a = torch.randn(4)
torch.ceil(a)

tensor([ 1., -1.,  1., -0.])

In [77]:
a = torch.randn(4)
print(torch.clamp(a, min=-0.5, max=0.5))
min = torch.linspace(-1, 1, steps=4)
torch.clamp(a, min=min)

tensor([-0.5000, -0.4520,  0.2169,  0.5000])


tensor([-0.8002, -0.3333,  0.3333,  1.0000])

In [80]:
a = torch.randn(5)
b = torch.randn(5)
torch.copysign(a, b)

tensor([ 1.2092, -0.0938, -1.0777,  0.3974, -0.9586])

In [81]:
a = torch.randn(4)
torch.cos(a)

tensor([ 8.6193e-01, -7.7053e-05, -6.3428e-01,  5.2931e-01])

In [82]:
torch.cosh(a)

tensor([1.1447, 2.5094, 4.8337, 1.5585])

In [83]:
a = torch.tensor([[180.0, -180.0], [360.0, -360.0], [90.0, -90.0]])
torch.deg2rad(a)

tensor([[ 3.1416, -3.1416],
        [ 6.2832, -6.2832],
        [ 1.5708, -1.5708]])

In [84]:
a = torch.tensor([0.3810, 1.2774, -0.2972, -0.3719, -.4637])
print(torch.div(x, 0.5, rounding_mode="trunc"))
torch.div(a, 0.5, rounding_mode="floor")

tensor([[[2., 2., 2.],
         [2., 2., 2.]]])


tensor([ 0.,  2., -1., -1., -1.])

In [86]:
import math
torch.exp(torch.tensor([0, math.log(2.)]))

tensor([1., 2.])

In [90]:
x = torch.randn(2, 2, 2)
scales = (torch.randn(2) + 1) * 0.5
zero_points = torch.zeros(2).to(torch.long)
torch.fake_quantize_per_channel_affine(x, scales, zero_points, 1, 0, 255)

tensor([[[0.5961, 0.0000],
         [0.0000, 0.0000]],

        [[0.5961, 0.0000],
         [1.2624, 1.5780]]])

In [91]:
x = torch.randn(4)
torch.fake_quantize_per_tensor_affine(x, 0.1, 0, 0, 255)

tensor([0.0000, 0.7000, 0.9000, 0.0000])

In [92]:
a = torch.randint(10, (4,))
torch.float_power(a, 2)

tensor([ 4.,  4., 36.,  9.], dtype=torch.float64)

In [93]:
a = torch.randn(4)
torch.floor(a)

tensor([-2., -1., -2.,  0.])

In [94]:
a = torch.tensor([4.0, 3.0])
b = torch.tensor([2.0, 2.0])
torch.floor_divide(a, b)

<ipython-input-94-f6566fcb9dac>:3: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  ..\aten\src\ATen\native\BinaryOps.cpp:467.)
  torch.floor_divide(a, b)


tensor([2., 1.])

In [96]:
print(torch.fmod(torch.tensor([-3., -2., -1, 1, 2, 3]), 2))
torch.fmod(torch.tensor([1, 2, 3, 4, 5]), -1.5)

tensor([-1., -0., -1.,  1.,  0.,  1.])


tensor([1.0000, 0.5000, 0.0000, 1.0000, 0.5000])

In [98]:
torch.frac(torch.tensor([1, 2.5, -3.2]))

tensor([ 0.0000,  0.5000, -0.2000])

In [99]:
x = torch.arange(9.)
mantissa, exponent = torch.frexp(x)
print(mantissa)
print(exponent)
torch.ldexp(mantissa, exponent)

tensor([0.0000, 0.5000, 0.5000, 0.7500, 0.5000, 0.6250, 0.7500, 0.8750, 0.5000])
tensor([0, 1, 2, 2, 3, 3, 3, 3, 4], dtype=torch.int32)


tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [101]:
t = torch.tensor([[1, 2, 4, 8], [10, 20, 40, 80]])
torch.gradient(t)

(tensor([[ 9., 18., 36., 72.],
         [ 9., 18., 36., 72.]]),
 tensor([[ 1.0000,  1.5000,  3.0000,  4.0000],
         [10.0000, 15.0000, 30.0000, 40.0000]]))

In [102]:
torch.gradient(t, spacing=2.0)

(tensor([[ 4.5000,  9.0000, 18.0000, 36.0000],
         [ 4.5000,  9.0000, 18.0000, 36.0000]]),
 tensor([[ 0.5000,  0.7500,  1.5000,  2.0000],
         [ 5.0000,  7.5000, 15.0000, 20.0000]]))

In [103]:
x = torch.randn(4, dtype=torch.cfloat)
print(x)
print(x.imag)

tensor([-1.0486-0.2106j, -0.5064-0.0517j, -0.4652+0.0577j,  0.8217+0.8086j])
tensor([-0.2106, -0.0517,  0.0577,  0.8086])


In [104]:
torch.ldexp(torch.tensor([1.]), torch.tensor([1]))

tensor([2.])

In [105]:
torch.ldexp(torch.tensor([1.0]), torch.tensor([1, 2, 3, 4]))

tensor([ 2.,  4.,  8., 16.])

In [106]:
start = torch.arange(1., 5.)
end = torch.empty(4).fill_(10)
torch.lerp(start, end, 0.5)

tensor([5.5000, 6.0000, 6.5000, 7.0000])

In [107]:
a = torch.arange(0.5, 2, 0.5)
torch.lgamma(a)

tensor([ 0.5724,  0.0000, -0.1208])

In [108]:
a = torch.randn(5)
torch.log(a)

tensor([nan, nan, nan, nan, nan])

In [109]:
torch.log10(a)

tensor([nan, nan, nan, nan, nan])

In [110]:
torch.log1p(a)

tensor([-2.3796,     nan, -0.2393, -0.5352, -0.5747])

In [111]:
torch.log2(a)

tensor([nan, nan, nan, nan, nan])

In [117]:
torch.logaddexp(torch.tensor([1.0, 2000, 30000]), torch.tensor([-1.0, -2, -3]))

tensor([1.1269e+00, 2.0000e+03, 3.0000e+04])

In [118]:
torch.logical_and(torch.tensor([True, False, True]), torch.tensor([True, False, False]))

tensor([ True, False, False])

In [119]:
torch.logical_not(torch.tensor([True, False]))

tensor([False,  True])

In [120]:
torch.logical_or(torch.tensor([True, False, True]), torch.tensor([True, False, False]))

tensor([ True, False,  True])

In [121]:
torch.logical_xor(torch.tensor([True, False, True]), torch.tensor([True, False, False]))

tensor([False, False,  True])

In [122]:
a = torch.hypot(torch.tensor([4.0]), torch.tensor([3.0, 4.0, 5.0]))

In [123]:
a

tensor([5.0000, 5.6569, 6.4031])

In [124]:
b = torch.randn(4, 1)
c = torch.randn(1, 4)
torch.mul(b, c)

tensor([[-1.1341,  0.5047, -0.4101,  0.4644],
        [ 1.0406, -0.4631,  0.3763, -0.4261],
        [ 0.7618, -0.3391,  0.2755, -0.3119],
        [ 1.3362, -0.5947,  0.4832, -0.5471]])

In [125]:
x = torch.tensor([float('nan'), float('inf'), -float('inf'), 3.14])
torch.nan_to_num(x)

tensor([ 0.0000e+00,  3.4028e+38, -3.4028e+38,  3.1400e+00])

In [126]:
a = torch.randn(5)
torch.neg(a)

tensor([-0.1924, -0.7728, -1.0338,  0.5513,  0.4197])

In [128]:
eps = torch.finfo(torch.float32).eps
torch.nextafter(torch.tensor([1.0, 2.0]), torch.tensor([2.0, 1.0])) == torch.tensor([eps + 1, 2 - eps])

tensor([True, True])

In [129]:
t = torch.randn(5)
torch.positive(t)

tensor([ 2.4530, -1.2435,  1.1334,  1.3733, -2.0122])

In [130]:
a = torch.randn(4)
exp = torch.arange(1., 5.)
torch.pow(a, exp)

tensor([ 6.6342e-01,  4.1018e+00, -5.0053e-02,  9.8995e-06])

In [131]:
qx = torch.quantize_per_tensor(torch.rand(2, 2, 2, 2), 1.5, 3, torch.quint8)

In [132]:
torch.quantized_batch_norm(qx, torch.ones(2), torch.zeros(2), torch.rand(2), torch.rand(2), 0.00001, 0.2, 2)

tensor([[[[ 1.2000, -0.4000],
          [-0.4000, -0.4000]],

         [[-0.4000, -0.4000],
          [-0.4000, -0.4000]]],


        [[[-0.4000, -0.4000],
          [-0.4000, -0.4000]],

         [[-0.4000, -0.4000],
          [-0.4000, -0.4000]]]], size=(2, 2, 2, 2), dtype=torch.quint8,
       quantization_scheme=torch.per_tensor_affine, scale=0.2, zero_point=2)

In [133]:
qx = torch.quantize_per_tensor(torch.rand(2, 2), 1.5, 3, torch.quint8)
torch.quantized_max_pool1d(qx, [2])

tensor([[0.0000],
        [1.5000]], size=(2, 1), dtype=torch.quint8,
       quantization_scheme=torch.per_tensor_affine, scale=1.5, zero_point=3)

In [134]:
qx = torch.quantize_per_tensor(torch.rand(2, 2, 2, 2), 1.5, 3, torch.quint8)
torch.quantized_max_pool2d(qx, [2, 2])

tensor([[[[0.0000]],

         [[0.0000]]],


        [[[1.5000]],

         [[1.5000]]]], size=(2, 2, 1, 1), dtype=torch.quint8,
       quantization_scheme=torch.per_tensor_affine, scale=1.5, zero_point=3)

In [135]:
a = torch.tensor([[2.142, -3.142], [6.283, -6.283], [1.570, -1.570]])
torch.rad2deg(a)

tensor([[ 122.7276, -180.0233],
        [ 359.9894, -359.9894],
        [  89.9544,  -89.9544]])

In [138]:
x = torch.randn(4, dtype=torch.cfloat)
x.real

tensor([-0.4536,  0.6000, -1.5086,  0.0066])

In [139]:
a = torch.randn(4)
torch.reciprocal(a)

tensor([ 0.5438,  2.5720, -0.8446, -7.4929])

In [140]:
torch.remainder(torch.tensor([1, 2, 3, 4, 5]), -1.5)

tensor([-0.5000, -1.0000,  0.0000, -0.5000, -1.0000])

In [141]:
torch.round(torch.tensor((4.7, -2.3, 9.1, -7.7)))

tensor([ 5., -2.,  9., -8.])

In [142]:
a = torch.randn(4)
torch.rsqrt(a)

tensor([7.4311,    nan, 1.5761, 1.0360])

In [143]:
a = torch.tensor([0.7, -1.2, 0., 2.3])
torch.sign(a)

tensor([ 1., -1.,  0.,  1.])

In [144]:
t = torch.tensor([3+4j, 7-24j, 0, 1+2j])
t.sgn()

tensor([0.6000+0.8000j, 0.2800-0.9600j, 0.0000+0.0000j, 0.4472+0.8944j])

In [145]:
a = torch.tensor([0.7, -1.2, 0., 2.3])
torch.signbit(a)

tensor([False,  True, False, False])

In [146]:
a = torch.randn(4)
torch.sin(a)

tensor([-0.9005, -0.9499,  0.4134, -0.3273])

In [147]:
torch.sinh(a)

tensor([-1.3707, -1.6072,  0.4392, -0.3396])

In [148]:
torch.sqrt(a)

tensor([   nan,    nan, 0.6528,    nan])

In [149]:
torch.square(a)

tensor([1.2563, 1.5695, 0.1817, 0.1112])

In [150]:
a = torch.tensor((1, 2))
b = torch.tensor((0, 1))
torch.sub(a, b, alpha=2)

tensor([1, 0])

In [151]:
a = torch.randn(4)
torch.tan(a)

tensor([0.1240, 0.7224, 0.2797, 0.3237])

In [152]:
torch.tanh(a)

tensor([0.1227, 0.5550, 0.2661, 0.3032])

In [153]:
torch.trunc(a)

tensor([0., 0., 0., 0.])

In [154]:
a = torch.randn(4, 4)
torch.argmax(a)

tensor(2)

In [155]:
torch.argmin(a, dim=1, keepdim=True)

tensor([[1],
        [3],
        [0],
        [1]])

In [156]:
torch.amax(a, 1)

tensor([1.7224, 0.9255, 1.2508, 1.0391])

In [157]:
torch.amin(a, 1)

tensor([-1.4795,  0.0556, -0.6167, -0.9680])

In [159]:
a = torch.rand(4, 2).bool()
print(torch.all(a, dim=1))
torch.all(a, dim=0)

tensor([True, True, True, True])


tensor([True, True])

In [161]:
a = torch.randn(4, 2) < 0
print(torch.any(a, 1))
torch.any(a, 0)

tensor([False,  True, False,  True])


tensor([True, True])

In [163]:
a = torch.randn(4, 4)
torch.max(a, 1)

torch.return_types.max(
values=tensor([1.3026, 2.1735, 0.6999, 1.6141]),
indices=tensor([2, 0, 1, 0]))

In [165]:
torch.min(a)

tensor(-1.5776)

In [168]:
x = torch.randn(4)
y = torch.randn(4)
print(torch.dist(x, y, 3.5))
print(torch.dist(x, y, 3))
print(torch.dist(x, y, 0))
print(torch.dist(x, y, 1))

tensor(2.3411)
tensor(2.4195)
tensor(4.)
tensor(5.1880)


In [169]:
a = torch.randn(3, 3)
torch.logsumexp(a, 1)

tensor([2.6299, 1.1904, 1.9844])

In [170]:
a = torch.randn(4, 4)
torch.mean(a, 1, True)

tensor([[-0.1707],
        [ 0.4220],
        [-0.1654],
        [-0.1286]])

In [175]:
a = torch.randn(1, 3)
torch.median(a)

tensor(0.2316)

In [177]:
a = torch.tensor([1, float("nan"), 3, 2])
a.nanmedian()

tensor(2.)

In [182]:
a = torch.randn(40, 4)
torch.mode(a, 0)

torch.return_types.mode(
values=tensor([-2.2872, -2.9035, -2.5013, -1.7337]),
indices=tensor([10, 17, 31, 38]))

In [183]:
a = torch.arange(9, dtype=torch.float) - 4
b = a.reshape((3, 3))
torch.norm(b)

tensor(7.7460)

In [184]:
a = torch.tensor([1., 2., float('nan'), 4.])
torch.nansum(a)

tensor(7.)

In [185]:
a = torch.randn(1, 3)
torch.prod(a)

tensor(-6.1473)

In [186]:
a = torch.randn(2, 3)
q = torch.tensor([0.25, 0.5, 0.75])
torch.quantile(a, q, dim=1, keepdim=True)

tensor([[[-1.1005],
         [-0.5623]],

        [[-0.2219],
         [-0.2692]],

        [[ 0.4798],
         [-0.1138]]])

In [187]:
t = torch.tensor([float('nan'), 1, 2])
print(t.quantile(0.5))
t.nanquantile(0.5)

tensor(nan)


tensor(1.5000)

In [189]:
a = torch.tensor([[-0.8166, -1.3802, -0.3560]])
torch.std(a)

tensor(0.5130)

In [190]:
torch.std_mean(a)

(tensor(0.5130), tensor(-0.8509))

In [191]:
a = torch.randn(1, 3)
torch.sum(a)

tensor(0.1290)

In [192]:
torch.unique(torch.tensor([1, 3, 2, 3]))

tensor([1, 2, 3])

In [193]:
x = torch.tensor([1, 1, 2, 2, 3, 1, 1, 2])
output, counts = torch.unique_consecutive(x, return_counts=True)
print(output)
print(counts)

tensor([1, 2, 3, 1, 2])
tensor([2, 2, 1, 2, 1])


In [195]:
a = torch.tensor([[-0.8166, -1.3802, -0.3560]])
torch.var(a)

tensor(0.2631)

In [196]:
torch.var_mean(a)

(tensor(0.2631), tensor(-0.8509))

In [197]:
x = torch.zeros(3, 3)
x[torch.randn(3, 3) > 0.5] = 1
print(torch.count_nonzero(x))
torch.count_nonzero(x, dim=0)

tensor(4)


tensor([1, 2, 1])

In [198]:
torch.allclose(torch.tensor([10000., 1e-07]), torch.tensor([10000.1, 1e-08]))

False

In [199]:
a = torch.randn(4, 4)
torch.argsort(a, dim=1)

tensor([[0, 1, 2, 3],
        [3, 2, 1, 0],
        [1, 0, 2, 3],
        [0, 3, 2, 1]])

In [200]:
torch.eq(torch.tensor([[1, 2], [3, 4]]), torch.tensor([[1, 1], [4, 4]]))

tensor([[ True, False],
        [False,  True]])

In [201]:
torch.equal(torch.tensor([1, 2]), torch.tensor([1, 2]))

True

In [202]:
torch.ge(torch.tensor([[1, 2], [3, 4]]), torch.tensor([[1, 1], [4, 4]]))

tensor([[ True,  True],
        [False,  True]])

In [203]:
torch.gt(torch.tensor([[1, 2], [3, 4]]), torch.tensor([[1, 1], [4, 4]]))

tensor([[False,  True],
        [False, False]])

In [204]:
torch.isclose(torch.tensor((1., 2, 3)), torch.tensor((1 + 1e-10, 3, 4)))

tensor([ True, False, False])

In [205]:
torch.isfinite(torch.tensor([1, float('inf'), 2, float('inf'), float("nan")]))

tensor([ True, False,  True, False, False])

In [207]:
torch.isinf(torch.tensor([1, float('inf'), 2, float('inf'), float("nan")]))

tensor([False,  True, False,  True, False])

In [208]:
a = torch.tensor([-float("inf"), float('inf'), 1.2])
torch.isposinf(a)

tensor([False,  True, False])

In [209]:
a = torch.tensor([-float("inf"), float('inf'), 1.2])
torch.isneginf(a)

tensor([ True, False, False])

In [211]:
torch.isnan(torch.tensor([1, float('nan'), 2]))

tensor([False,  True, False])

In [212]:
torch.isreal(torch.tensor([1, 1 + 1j, 2+0j]))

tensor([ True, False,  True])

In [213]:
x = torch.arange(1., 6.)
print(torch.kthvalue(x, 4))
x = torch.arange(1., 7.).resize_(2, 3)
torch.kthvalue(x, 2, 0, True)

torch.return_types.kthvalue(
values=tensor(4.),
indices=tensor(3))


torch.return_types.kthvalue(
values=tensor([[4., 5., 6.]]),
indices=tensor([[1, 1, 1]]))

In [214]:
torch.le(torch.tensor([[1, 2], [3, 4]]), torch.tensor([[1, 1], [4, 4]]))

tensor([[ True, False],
        [ True,  True]])

In [215]:
torch.lt(torch.tensor([[1, 2], [3, 4]]), torch.tensor([[1, 1], [4, 4]]))

tensor([[False, False],
        [ True, False]])

In [216]:
a = torch.tensor((1, 2, -1))
b = torch.tensor((3, 0, 4))
torch.maximum(a, b)

tensor([3, 2, 4])

In [217]:
torch.minimum(a, b)

tensor([ 1,  0, -1])

In [1]:
import torch
a = torch.tensor([9.7, float('nan'), 3.1, float('nan')])
b = torch.tensor([-2.2, 0.5, float('nan'), float('nan')])
torch.fmax(a, b)

tensor([9.7000, 0.5000, 3.1000,    nan])

In [2]:
torch.fmin(a, b)

tensor([-2.2000,  0.5000,  3.1000,     nan])

In [3]:
torch.ne(torch.tensor([[1, 2], [3, 4]]), torch.tensor([[1, 1], [4, 4]]))

tensor([[False,  True],
        [ True, False]])

In [4]:
x = torch.randn(3, 4)
sorteds, indices = torch.sort(x)
sorteds

tensor([[ 0.0434,  0.2138,  0.3294,  2.0464],
        [-1.3701,  0.1621,  0.8104,  0.8467],
        [-1.8470,  0.2770,  0.6345,  1.8829]])

In [5]:
indices

tensor([[0, 1, 2, 3],
        [0, 3, 2, 1],
        [1, 0, 3, 2]])

In [7]:
a = torch.arange(1., 6.)
torch.topk(x, 3)

torch.return_types.topk(
values=tensor([[2.0464, 0.3294, 0.2138],
        [0.8467, 0.8104, 0.1621],
        [1.8829, 0.6345, 0.2770]]),
indices=tensor([[3, 2, 1],
        [1, 2, 3],
        [2, 3, 0]]))

In [8]:
t = torch.randn(3, 4)
torch.msort(t)

tensor([[-2.1737, -1.4692, -0.3065, -0.2245],
        [-1.2537,  0.8304,  0.1542,  0.0803],
        [-0.7205,  1.4559,  0.2869,  0.0863]])

In [9]:
x = torch.randn(2)
torch.atleast_1d(x)

tensor([-0.5562, -1.4164])

In [10]:
x = torch.randn(2, 2)
torch.atleast_2d(x)

tensor([[ 0.7074,  0.0748],
        [-0.0249, -1.1326]])

In [11]:
x = torch.randn(1, 1, 1)
torch.atleast_3d(x)

tensor([[[-1.3822]]])

In [14]:
input = torch.randint(0, 8, (5,), dtype=torch.int64)
weights = torch.linspace(0, 1, steps=5)
print(torch.bincount(input))
print(torch.bincount(input, weights=weights))

tensor([1, 0, 1, 0, 1, 0, 2])
tensor([0.2500, 0.0000, 0.5000, 0.0000, 0.7500, 0.0000, 1.0000])


In [15]:
A = torch.tensor([[0, 1], [1, 0]])
B = torch.tensor([[3, 4, 5], [6, 7, 8]])
C = torch.tensor(7)
D = torch.tensor([1, 2, 3])
E = torch.tensor([[4], [5], [6]])
torch.block_diag(A, B, C, D, E)

tensor([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 3, 4, 5, 0, 0, 0, 0, 0],
        [0, 0, 6, 7, 8, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 7, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 2, 3, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 4],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 5],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 6]])

In [17]:
x = torch.arange(3).view(1, 3)
y = torch.arange(2).view(2, 1)
x

tensor([[0, 1, 2]])

In [20]:
a, b = torch.broadcast_tensors(x, y)
print(a.shape)
print(a)

torch.Size([2, 3])
tensor([[0, 1, 2],
        [0, 1, 2]])


In [21]:
x = torch.tensor([1, 2, 3])
torch.broadcast_to(x, (3, 3))

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [22]:
torch.broadcast_shapes((2, ), (3, 1), (1, 1, 1))

torch.Size([1, 3, 2])

In [23]:
boundaries = torch.tensor([1, 3, 5, 7, 9])
v = torch.tensor([[3, 6, 9], [3, 6, 9]])
torch.bucketize(v, boundaries)

tensor([[1, 3, 4],
        [1, 3, 4]])

In [24]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5])
torch.cartesian_prod(a, b)

tensor([[1, 4],
        [1, 5],
        [2, 4],
        [2, 5],
        [3, 4],
        [3, 5]])

In [25]:
a = torch.tensor([[0.9041, 0.0196], [-0.3108, -2.4423], [-0.4821, 1.059]])
b = torch.tensor([[-2.1763, -0.4713], [-0.6986, 1.3702]])
torch.cdist(a, b, p=2)

tensor([[3.1193, 2.0959],
        [2.7138, 3.8322],
        [2.2830, 0.3791]])

In [26]:
a = [1, 2, 3]
tensor_a = torch.tensor(a)
torch.combinations(tensor_a)

tensor([[1, 2],
        [1, 3],
        [2, 3]])

In [28]:
torch.combinations(tensor_a, with_replacement=True)

tensor([[1, 1],
        [1, 2],
        [1, 3],
        [2, 2],
        [2, 3],
        [3, 3]])

In [31]:
import numpy as np
x = torch.tensor([[0, 2], [1, 1], [2, 0]]).T
np.cov(x)

array([[ 1., -1.],
       [-1.,  1.]])

In [32]:
a = torch.randn(4, 3)
b = torch.randn(4, 3)
torch.cross(a, b, dim=1)

tensor([[ 1.4054,  1.0286,  0.1101],
        [ 0.7175,  2.7195, -0.2627],
        [-0.8571,  1.1880,  0.5908],
        [ 0.1025,  2.5105,  0.1910]])

In [33]:
a = torch.randn(10)
torch.cummax(a, dim=0)

torch.return_types.cummax(
values=tensor([1.6569, 1.6569, 1.6569, 1.6569, 1.6569, 1.6569, 1.6569, 1.6569, 1.6569,
        1.6569]),
indices=tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

In [34]:
torch.cummin(a, dim=0)

torch.return_types.cummin(
values=tensor([ 1.6569, -0.5561, -0.5561, -0.5561, -1.4546, -1.4546, -1.4546, -1.4546,
        -1.4546, -1.4546]),
indices=tensor([0, 1, 1, 1, 4, 4, 4, 4, 4, 4]))

In [35]:
a = torch.randn(10)
torch.cumprod(a, dim=0)

tensor([-0.6862, -0.0682,  0.1377,  0.1388, -0.1936, -0.1906, -0.1116,  0.1558,
        -0.1744, -0.2486])

In [36]:
torch.cumsum(a, dim=0)

tensor([-0.6862, -0.5867, -2.6044, -1.5959, -2.9901, -2.0057, -1.4199, -2.8152,
        -3.9349, -2.5095])

In [37]:
a = torch.randn(3)
torch.diag(a, 1)

tensor([[ 0.0000, -0.0167,  0.0000,  0.0000],
        [ 0.0000,  0.0000, -0.3563,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.6786],
        [ 0.0000,  0.0000,  0.0000,  0.0000]])

In [40]:
x = torch.randn(2, 3)
torch.diag_embed(a)

tensor([[-0.0167,  0.0000,  0.0000],
        [ 0.0000, -0.3563,  0.0000],
        [ 0.0000,  0.0000,  0.6786]])

In [41]:
a = torch.randn(2, 2)
torch.diagflat(a)

tensor([[ 0.7726,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  1.7843,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.4617,  0.0000],
        [ 0.0000,  0.0000,  0.0000, -0.9981]])

In [42]:
a = torch.randn(3, 3)
torch.diagonal(a, 0)

tensor([-0.5105,  0.8013, -0.3277])

In [43]:
torch.diagonal(a, 1)

tensor([ 0.4775, -0.1951])

In [44]:
a = torch.tensor([1, 3, 2])
torch.diff(a)

tensor([ 2, -1])

In [45]:
As = torch.randn(3, 2, 5)
Bs = torch.randn(3, 5, 4)
torch.einsum('bij,bjk->bik', As, Bs)

tensor([[[-3.4381,  0.2515, -1.7514,  4.6362],
         [-1.5097,  2.5956, -2.8419,  5.3005]],

        [[ 4.3741,  0.3540,  2.9176,  1.7029],
         [-0.4122, -0.9717,  2.1088,  1.1524]],

        [[-0.7833,  0.6573,  1.3387,  0.1599],
         [-3.1419, -1.5508,  1.5325,  0.3336]]])

In [46]:
t = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
torch.flatten(t)

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
x = torch.arange(8).view(2, 2, 2)
torch.flip(x, [0, 1])

tensor([[[6, 7],
         [4, 5]],

        [[2, 3],
         [0, 1]]])

In [48]:
x = torch.arange(4).view(2, 2)
torch.fliplr(x)

tensor([[1, 0],
        [3, 2]])

In [49]:
x = torch.arange(4).view(2, 2)
torch.flipud(x)

tensor([[2, 3],
        [0, 1]])

In [50]:
mat1 = torch.eye(2)
mat2 = torch.ones(2, 2)
torch.kron(mat1, mat2)

tensor([[1., 1., 0., 0.],
        [1., 1., 0., 0.],
        [0., 0., 1., 1.],
        [0., 0., 1., 1.]])

In [51]:
x = torch.arange(8).view(2, 2, 2)
torch.rot90(x, 1, [1, 2])

tensor([[[1, 3],
         [0, 2]],

        [[5, 7],
         [4, 6]]])

In [52]:
a = torch.tensor([5, 10, 15])
b = torch.tensor([3, 4, 5])
torch.gcd(a, b)

tensor([1, 2, 5])

In [53]:
torch.histc(torch.tensor([1., 2., 1.]), bins=4, min=0, max=3)

tensor([0., 2., 1., 0.])

In [57]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
grid_x, grid_y = torch.meshgrid(x, y)
print(grid_x)
print(grid_y)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])
tensor([[4, 5, 6],
        [4, 5, 6],
        [4, 5, 6]])


In [58]:
a = torch.tensor([5, 10, 15])
b = torch.tensor([3, 4, 5])
torch.lcm(a, b)

tensor([15, 20, 15])

In [59]:
a = torch.randn(10)
torch.logcumsumexp(a, dim=0)

tensor([-1.0409,  0.5678,  0.9777,  1.6832,  1.9253,  2.0559,  2.0815,  2.1126,
         2.1699,  2.3675])

In [60]:
t = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
torch.ravel(t)

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [61]:
x = torch.ones(3, 3)
x[1].fill_(2)
x[2].fill_(3)
torch.renorm(x, 1, 0, 5)

tensor([[1.0000, 1.0000, 1.0000],
        [1.6667, 1.6667, 1.6667],
        [1.6667, 1.6667, 1.6667]])

In [62]:
x = torch.tensor([1, 2, 3])
x.repeat_interleave(2)

tensor([1, 1, 2, 2, 3, 3])

In [63]:
x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8]).view(4, 2)
torch.roll(x, 1, 0)

tensor([[7, 8],
        [1, 2],
        [3, 4],
        [5, 6]])

In [64]:
sorted_sequence = torch.tensor([[1, 3, 5, 7, 9], [2, 4, 6, 8, 10]])
values = torch.tensor([[3, 6, 9], [3, 6, 9]])
torch.searchsorted(sorted_sequence, values)

tensor([[1, 3, 4],
        [1, 2, 4]])

In [65]:
a = torch.randn(3, 4, 5)
b = torch.randn(4, 5, 6)
torch.tensordot(a, b, dims=2)

tensor([[ 3.3254, -7.4709,  7.5069, -3.4747, -3.8236,  1.4298],
        [-0.9867, -6.1078,  3.7404, -0.1959, -3.9522, -0.9399],
        [-3.6735,  0.7114, -3.4146, -1.4694,  1.5264, -3.3220]])

In [66]:
x = torch.arange(1., 10.).view(3, 3)
torch.trace(x)

tensor(15.)

In [67]:
a = torch.randn(3, 3)
torch.tril(a)

tensor([[-0.2464,  0.0000,  0.0000],
        [-0.3507,  1.2797,  0.0000],
        [ 0.5525, -0.8117, -0.1058]])

In [68]:
a = torch.tril_indices(3, 3)
a

tensor([[0, 1, 1, 2, 2, 2],
        [0, 0, 1, 0, 1, 2]])

In [69]:
a = torch.randn(3, 3)
torch.triu(a)

tensor([[ 1.6915, -1.9579,  0.7358],
        [ 0.0000,  2.0335, -0.2863],
        [ 0.0000,  0.0000, -0.7326]])

In [70]:
torch.triu_indices(3, 3)

tensor([[0, 0, 0, 1, 1, 2],
        [0, 1, 2, 1, 2, 2]])

In [71]:
x = torch.tensor([1, 2, 3, 5])
torch.vander(x)

tensor([[  1,   1,   1,   1],
        [  8,   4,   2,   1],
        [ 27,   9,   3,   1],
        [125,  25,   5,   1]])

In [72]:
x = torch.randn(4, dtype=torch.cfloat)
print(x)
torch.view_as_real(x)

tensor([ 0.0277+0.2569j, -0.5313+0.3789j,  0.2789+0.8182j,  0.6531-1.0143j])


tensor([[ 0.0277,  0.2569],
        [-0.5313,  0.3789],
        [ 0.2789,  0.8182],
        [ 0.6531, -1.0143]])

In [73]:
x = torch.randn(4, 2)
torch.view_as_complex(x)

tensor([1.1835-0.0897j, 0.0741+2.8608j, 1.6591+1.0535j, 1.1624+0.7777j])

In [77]:
M = torch.randn(3, 5)
batch1 = torch.randn(10, 3, 4)
batch2 = torch.randn(10, 4, 5)
torch.addbmm(M, batch1, batch2)

tensor([[ 1.0740,  1.1060,  1.0193,  1.3101, -3.1052],
        [-6.3311,  4.9983,  8.5681,  6.7977, -4.2746],
        [-4.0346, -3.8023,  2.6066,  2.5656, -5.2913]])

In [78]:
M = torch.randn(2, 3)
mat1 = torch.randn(2, 3)
mat2 = torch.randn(3, 3)
torch.addmm(M, mat1, mat2)

tensor([[2.9484, 0.4555, 1.6546],
        [2.1927, 0.7718, 0.8449]])

In [80]:
M = torch.randn(2)
mat = torch.randn(2, 3)
vec = torch.randn(3)
torch.addmv(M, mat, vec)

tensor([-1.4525, -0.1440])

In [81]:
vec1 = torch.arange(1., 4.)
vec2 = torch.arange(1., 3.)
M = torch.zeros(3, 2)
torch.addr(M, vec1, vec2)

tensor([[1., 2.],
        [2., 4.],
        [3., 6.]])

In [82]:
M = torch.randn(10, 3, 5)
batch1 = torch.randn(10, 3, 4)
batch2 = torch.randn(10, 4, 5)
torch.baddbmm(M, batch1, batch2).shape

torch.Size([10, 3, 5])

In [83]:
inputs = torch.randn(10, 3, 4)
mat2 = torch.randn(10, 4, 5)
res = torch.bmm(inputs, mat2)
res.size()

torch.Size([10, 3, 5])

In [86]:
a = torch.randn(3, 3)
a = a @ a.T + 1e-3
l = torch.cholesky(a)
print(a)
print(l)
print(l @ l.T)

tensor([[1.5882, 1.3652, 0.6393],
        [1.3652, 2.8394, 3.1156],
        [0.6393, 3.1156, 4.2145]])
tensor([[1.2602, 0.0000, 0.0000],
        [1.0833, 1.2907, 0.0000],
        [0.5073, 1.9882, 0.0669]])
tensor([[1.5882, 1.3652, 0.6393],
        [1.3652, 2.8394, 3.1156],
        [0.6393, 3.1156, 4.2145]])


<ipython-input-86-86c836102cbe>:3: UserWarning: torch.cholesky is deprecated in favor of torch.linalg.cholesky and will be removed in a future PyTorch release.
L = torch.cholesky(A)
should be replaced with
L = torch.linalg.cholesky(A)
and
U = torch.cholesky(A, upper=True)
should be replaced with
U = torch.linalg.cholesky(A.transpose(-2, -1).conj()).transpose(-2, -1).conj() (Triggered internally at  ..\aten\src\ATen\native\BatchLinearAlgebra.cpp:1284.)
  l = torch.cholesky(a)


In [87]:
a = torch.randn(3, 3)
a = torch.mm(a, a.t()) + 1e-05 * torch.eye(3)
u = torch.linalg.cholesky(a)
print(a)
print(torch.cholesky_inverse(u))
a.inverse()

tensor([[ 2.1644,  1.1865, -0.5374],
        [ 1.1865,  0.9917, -0.2912],
        [-0.5374, -0.2912,  0.1406]])
tensor([[ 10.2936,  -1.9551,  35.2830],
        [ -1.9551,   2.9440,  -1.3746],
        [ 35.2830,  -1.3746, 139.0796]])


tensor([[ 10.2936,  -1.9551,  35.2830],
        [ -1.9551,   2.9440,  -1.3746],
        [ 35.2830,  -1.3746, 139.0796]])

In [89]:
a = torch.randn(3, 3)
a = torch.mm(a, a.t())
u = torch.linalg.cholesky(a)
print(a)
b = torch.randn(3, 2)
print(b)
print(torch.cholesky_solve(b, u))
torch.mm(a.inverse(), b)

tensor([[ 0.6139, -0.6841, -0.9582],
        [-0.6841,  2.4637,  0.9090],
        [-0.9582,  0.9090,  2.4760]])
tensor([[-0.8432,  0.9736],
        [ 0.0526,  0.4349],
        [ 0.9826,  0.6991]])
tensor([[-2.6717,  6.6503],
        [-0.5616,  1.1213],
        [-0.4309,  2.4443]])


tensor([[-2.6717,  6.6503],
        [-0.5616,  1.1213],
        [-0.4309,  2.4443]])

In [90]:
torch.dot(torch.tensor([2, 3]), torch.tensor([2, 1]))

tensor(7)

In [91]:
a = torch.diag(torch.tensor([1, 2, 3], dtype=torch.double))
e, v = torch.eig(a, eigenvectors=True)
print(e)
print(v)

tensor([[1., 0.],
        [2., 0.],
        [3., 0.]], dtype=torch.float64)
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], dtype=torch.float64)


<ipython-input-91-4997ffbce4c9>:2: UserWarning: torch.eig is deprecated in favor of torch.linalg.eig and will be removed in a future PyTorch release.
torch.linalg.eig returns complex tensors of dtype cfloat or cdouble rather than real tensors mimicking complex tensors.
L, _ = torch.eig(A)
should be replaced with
L_complex = torch.linalg.eigvals(A)
and
L, V = torch.eig(A, eigenvectors=True)
should be replaced with
L_complex, V_complex = torch.linalg.eig(A) (Triggered internally at  ..\aten\src\ATen\native\BatchLinearAlgebra.cpp:2897.)
  e, v = torch.eig(a, eigenvectors=True)


In [92]:
a = torch.randn(2, 3)
b = torch.randn(2, 4, 3)
torch.inner(a, b)

tensor([[[ 0.3234,  0.2616, -1.5652,  1.0240],
         [ 2.1822, -0.0609, -0.6796,  0.0283]],

        [[-0.8112,  1.2743, -3.0530, -0.0320],
         [ 2.9220,  1.2233, -0.1388,  1.3860]]])

In [2]:
import torch
A = torch.randn(3, 3)
print(torch.det(A))
torch.logdet(A)


tensor(3.4994)


tensor(1.2526)

In [3]:
A = torch.tensor([[1., 1, 1], [2, 3, 4], [3, 4, 2], [4, 2, 5], [5, 4, 3]])
B = torch.tensor([[-10., -3], [12, 14], [14, 12], [16, 16], [18, 16]])
X, _ = torch.lstsq(B, A)
X

<ipython-input-3-3707cf384f22>:3: UserWarning: torch.lstsq is deprecated in favor of torch.linalg.lstsq and will be removed in a future PyTorch release.
torch.linalg.lstsq has reversed arguments and does not return the QR decomposition in the returned tuple (although it returns other information about the problem).
To get the qr decomposition consider using torch.linalg.qr.
The returned solution in torch.lstsq stored the residuals of the solution in the last m - n columns of the returned value whenever m > n. In torch.linalg.lstsq, the residuals in the field 'residuals' of the returned named tuple.
The unpacking of the solution, as in
X, _ = torch.lstsq(B, A).solution[:A.size(1)]
should be replaced with
X = torch.linalg.lstsq(A, B).solution (Triggered internally at  ..\aten\src\ATen\LegacyTHFunctionsCPU.cpp:389.)
  X, _ = torch.lstsq(B, A)


tensor([[ 2.0588,  0.9167],
        [ 1.0784,  1.2500],
        [ 0.9216,  1.9167],
        [11.8328,  5.5663],
        [ 7.9202,  4.5202]])

In [5]:
A = torch.randn([2, 3, 3])
A_LU, pivots = torch.lu(A)
print(A_LU)
print(pivots)

tensor([[[ 2.2836,  0.0796, -0.2974],
         [-0.1618, -1.4068,  0.6955],
         [-0.0404,  0.5324,  0.4007]],

        [[-1.3238,  1.2338,  1.3635],
         [-0.1920,  0.8411, -0.2419],
         [-0.3300,  0.7382, -0.0719]]])
tensor([[2, 2, 3],
        [2, 3, 3]], dtype=torch.int32)


In [7]:
A = torch.randn(2, 3, 3)
b = torch.randn(2, 3, 1)
A_LU = torch.lu(A)
x = torch.lu_solve(b, *A_LU)
torch.norm(torch.bmm(A, x) - b)

tensor(4.6457e-07)

In [8]:
A = torch.randn(2, 3, 3)
A_LU, pivots = A.lu()
P, A_L, A_U = torch.lu_unpack(A_LU, pivots)
A_ = torch.bmm(P, torch.bmm(A_L, A_U))
A = torch.randn(2, 3, 2)
A_LU, pivots = A.lu()
P, A_L, A_U = torch.lu_unpack(A_LU, pivots)
print(P)
print(A_L)
print(A_U)
A_ = torch.bmm(P, torch.bmm(A_L, A_U))
torch.norm(A_ - A)

tensor([[[0., 1., 0.],
         [0., 0., 1.],
         [1., 0., 0.]],

        [[0., 1., 0.],
         [0., 0., 1.],
         [1., 0., 0.]]])
tensor([[[ 1.0000,  0.0000],
         [ 0.1516,  1.0000],
         [ 0.7434,  0.6133]],

        [[ 1.0000,  0.0000],
         [-0.0315,  1.0000],
         [ 0.1857,  0.2281]]])
tensor([[[-1.8939,  1.4018],
         [ 0.0000, -0.7425]],

        [[-1.0344, -0.2556],
         [ 0.0000, -1.3223]]])


tensor(6.6640e-08)

In [9]:
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(10, 4, 5)
torch.matmul(tensor1, tensor2).size()

torch.Size([10, 3, 5])

In [10]:
a = torch.eye(10)
torch.matrix_rank(a)

<ipython-input-10-df604527f356>:2: UserWarning: torch.matrix_rank is deprecated in favor of torch.linalg.matrix_rankand will be removed in a future PyTorch release. The parameter 'symmetric' was renamed in torch.linalg.matrix_rank to 'hermitian'. (Triggered internally at  ..\aten\src\ATen\native\LinearAlgebra.cpp:441.)
  torch.matrix_rank(a)


tensor(10)

In [11]:
mat1 = torch.randn(2, 3)
mat2 = torch.randn(3, 3)
torch.mm(mat1, mat2)

tensor([[ 1.3681,  0.3892, -1.3607],
        [-2.1028, -0.0811,  1.1854]])

In [12]:
mat = torch.randn(2, 3)
vec = torch.randn(3)
torch.mv(mat, vec)

tensor([3.5842, 0.6073])

In [14]:
v1 = torch.arange(1., 5.)
v2 = torch.arange(1., 4.)
torch.outer(v1, v2)

tensor([[ 1.,  2.,  3.],
        [ 2.,  4.,  6.],
        [ 3.,  6.,  9.],
        [ 4.,  8., 12.]])

In [17]:
A = torch.randn(2, 2).triu()
b = torch.randn(2,3)
torch.triangular_solve(b, A)

torch.return_types.triangular_solve(
solution=tensor([[ 3.0443,  4.5957, -0.2567],
        [-2.5510, -0.2154, -1.1702]]),
cloned_coefficient=tensor([[ 0.3227,  0.0604],
        [ 0.0000, -0.4879]]))

In [18]:
a = torch.tensor((1 + 2j, 3 - 1j))
b = torch.tensor((2 + 1j, 4 - 0j))
torch.vdot(a, b)

tensor(16.+1.j)

In [19]:
torch.result_type(torch.tensor([1, 2], dtype=torch.int), 1.0)

torch.float32

In [21]:
torch.can_cast(torch.double, torch.float)

True

In [22]:
torch.promote_types(torch.int32, torch.float32)

torch.float32

In [23]:
import torch.nn as nn
import torch.nn.functional as F
class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(1, 20, 5)
        self.conv2 = nn.Conv2d(20, 20, 5)
    def forward(self, x):
        x = F.relu(self.conv1(self.x))
        return F.relu(self.conv2(x))

In [24]:
model = nn.Sequential(
    nn.Conv2d(1, 20, 5),
    nn.ReLU(),
    nn.Conv2d(20, 64, 5),
    nn.ReLU()
)

In [26]:
class MyModule(nn.Module):
    def __init__(self):
        super(MyModule, self).__init__()
        self.linears = nn.ModuleList([nn.Linear(10, 10) for i in range(10)])
    def forward(self, x):
        for i, l in enumerate(self.linears):
            x = self.linears[i // 2](x) + l(x)
        return x

In [27]:
class MyModule(nn.Module):
    def __init__(self):
        super(MyModule, self).__init__()
        self.choices = nn.ModuleDict({"conv":nn.Conv2d(10, 10, 3), "pool":nn.MaxPool2d(3)})
        self.activations = nn.ModuleDict([
            ["lrelu", nn.LeakyReLU()],
            ["prelu", nn.PReLU()]
        ])
        def forward(self, x, choice, act):
            x = self.choices[choice](x)
            x = self.activations[act](x)
            return x

In [29]:
class MyModule(nn.Module):
    def __init__(self):
        super(MyModule, self).__init__()
        self.params = nn.ParameterList([nn.Parameter(torch.randn(10, 10)) for i in range(10)])
    def forward(self, x):
        for i, p in enumerate(self.params):
            x = self.params[i // 2].mm(x) + p.mm(x)
        return x

In [31]:
class MyModule(nn.Module):
    def __init__(self):
        super().__init__()
        self.params = nn.ParameterDict({"left":nn.ParameterDict(torch.randn(5, 10)), 
                                        "right":nn.Parameter(torch.randn(5, 10))})
    def forward(self, x, choice):
        x = self.params[choice].mm(x)
        return x

In [32]:
m = nn.Conv1d(16, 33, 3, stride=2)
inputs = torch.randn(20, 16, 50)
output = m(inputs)

In [33]:
output.shape

torch.Size([20, 33, 24])

In [34]:
m = nn.Conv2d(16, 33, 3, stride=2)
m = nn.Conv2d(16, 33, (3, 5), stride=(2, 1), padding=(4, 2), dilation=(3, 1))
inputs = torch.randn(20, 16, 50, 100)
m(inputs).shape

torch.Size([20, 33, 26, 100])

In [35]:
m = nn.Conv3d(16, 33, (3, 5, 2), stride=(2, 1, 1), padding=(4, 2, 0))
inputs = torch.randn(20, 16, 10, 80, 100)
m(inputs).shape

torch.Size([20, 33, 8, 80, 99])

In [36]:
downsample = nn.Conv2d(16, 16, 3, stride=2, padding=1)
upsample = nn.ConvTranspose2d(16, 16, 3, stride=2, padding=1)
imports = torch.randn(1, 16, 12, 12)
print(downsample(imports).shape)
upsample(imports).shape

torch.Size([1, 16, 6, 6])


torch.Size([1, 16, 23, 23])

In [37]:
m = nn.ConvTranspose3d(16, 33, (3, 5, 2), stride=(2, 1, 1), padding=(0, 4, 2))
inputs = torch.randn(20, 16, 10, 50, 100)
m(inputs).shape

torch.Size([20, 33, 21, 46, 97])

In [42]:
unfold = nn.Unfold(kernel_size=(2, 3))
input = torch.randn(2, 6, 3, 4)
output = unfold(input)
output.size()

torch.Size([2, 36, 4])

In [43]:
fold = nn.Fold(output_size=(4, 5), kernel_size=(2, 2))
inputs = torch.randn(1, 3 * 2 * 2, 12)
fold(inputs).shape

torch.Size([1, 3, 4, 5])

In [45]:
m = nn.MaxPool1d(3, stride=2)
inputs = torch.randn(20, 16, 50)
m(inputs).shape

torch.Size([20, 16, 24])

In [46]:
m = nn.MaxPool2d((3, 2), stride=2)
inputs = torch.randn(20, 16, 50, 32)
m(inputs).shape

torch.Size([20, 16, 24, 16])

In [48]:
m = nn.MaxPool3d((3, 2, 2), stride=(2, 1, 2))
inputs = torch.randn(20, 16, 50, 44, 31)
m(inputs).shape

torch.Size([20, 16, 24, 43, 15])

In [49]:
pool = nn.MaxPool1d(2, stride=2, return_indices=True)
unpool = nn.MaxUnpool1d(2, stride=2)
inputs = torch.tensor([[[1., 2, 3, 4, 5, 6, 7, 8]]])
output, indices = pool(inputs)
unpool(output, indices)

tensor([[[0., 2., 0., 4., 0., 6., 0., 8.]]])

In [51]:
pool = nn.MaxPool2d(2, stride=2, return_indices=True)
unpool = nn.MaxUnpool2d(2, stride=2)
inputs = torch.tensor([[[[1., 2., 3., 4.], [5., 6., 7., 8.], [9., 10., 11., 12.], [13., 14., 15., 16.]]]])
output, indices = pool(input)
unpool(output, indices).shape

torch.Size([2, 6, 2, 4])

In [52]:
pool = nn.MaxPool3d(3, stride=2, return_indices=True)
unpool = nn.MaxUnpool3d(3, stride=2)
output, indices = pool(torch.randn(20, 16, 51, 33, 15))
unpool(output, indices).shape

torch.Size([20, 16, 51, 33, 15])

In [53]:
m = nn.AvgPool1d(3, stride=2)
m(torch.tensor([[[1., 2, 3, 4, 5, 6, 7]]]))

tensor([[[2., 4., 6.]]])

In [55]:
m = nn.AvgPool2d(3, stride=2)
m = nn.AvgPool2d((3, 2), stride=(2, 1))
m(torch.randn(20, 16, 50, 32)).shape

torch.Size([20, 16, 24, 31])

In [56]:
m = nn.AvgPool3d((3, 2, 2), stride=(2, 1, 2))
inputs = torch.randn(20, 16, 50, 44, 31)
output = m(inputs)
output.shape

torch.Size([20, 16, 24, 43, 15])

In [57]:
m = nn.FractionalMaxPool2d(3, output_ratio=(0.5, 0.5))
input = torch.randn(20, 16, 50, 32)
m(input).shape

torch.Size([20, 16, 25, 16])

In [58]:
m = nn.FractionalMaxPool3d(3, output_ratio=(0.5, 0.5, 0.5))
input = torch.randn(20, 16, 50, 32, 16)
m(input).shape

torch.Size([20, 16, 25, 16, 8])

In [59]:
m = nn.LPPool1d(2, 3, stride=2)
inputs = torch.randn(20, 16, 50)
m(inputs).shape

torch.Size([20, 16, 24])

In [60]:
m = nn.LPPool2d(2, 3, stride=2)
m = nn.LPPool2d(1.2, (3, 2), stride=(2, 1))
inputs = torch.randn(20, 16, 50, 32)
m(inputs).shape

torch.Size([20, 16, 24, 31])

In [61]:
m = nn.AdaptiveMaxPool1d(5)
inputs = torch.randn(1, 64, 8)
m(inputs).shape

torch.Size([1, 64, 5])

In [62]:
m = nn.AdaptiveMaxPool2d((5, 7))
inputs = torch.randn(1, 64, 8, 9)
m(inputs).shape

torch.Size([1, 64, 5, 7])

In [64]:
m = nn.AdaptiveMaxPool3d((5, 7, 9))
inputs = torch.randn(1, 64, 8, 9, 10)
m(inputs).shape

torch.Size([1, 64, 5, 7, 9])

In [65]:
m = nn.AdaptiveAvgPool1d(5)
inputs = torch.randn(1, 64, 8)
m(inputs).shape

torch.Size([1, 64, 5])

In [66]:
m = nn.AdaptiveAvgPool2d((5, 7))
inputs = torch.randn(1, 64, 8, 9)
m(inputs).shape

torch.Size([1, 64, 5, 7])

In [67]:
m = nn.AdaptiveAvgPool3d((5, 7, 9))
inputs = torch.randn(1, 64, 8, 9, 10)
m(inputs).shape

torch.Size([1, 64, 5, 7, 9])

In [68]:
m = nn.ReflectionPad1d(2)
inputs = torch.arange(8, dtype=torch.float).reshape(1, 2, 4)
m(inputs)

tensor([[[2., 1., 0., 1., 2., 3., 2., 1.],
         [6., 5., 4., 5., 6., 7., 6., 5.]]])

In [69]:
m = nn.ReflectionPad2d(2)
inputs = torch.arange(9, dtype=torch.float).reshape(1, 1, 3, 3)
m(inputs).shape

torch.Size([1, 1, 7, 7])

In [71]:
m = nn.ReplicationPad1d(2)
inputs = torch.arange(8, dtype=torch.float).reshape(1, 2, 4)
m(inputs)

tensor([[[0., 0., 0., 1., 2., 3., 3., 3.],
         [4., 4., 4., 5., 6., 7., 7., 7.]]])

In [73]:
m = nn.ReplicationPad2d((1, 1, 2, 0))
inputs = torch.arange(9, dtype=torch.float).reshape(1, 1, 3, 3)
m(inputs)

tensor([[[[0., 0., 1., 2., 2.],
          [0., 0., 1., 2., 2.],
          [0., 0., 1., 2., 2.],
          [3., 3., 4., 5., 5.],
          [6., 6., 7., 8., 8.]]]])

In [75]:
m = nn.ReplicationPad3d(3)
inputs = torch.randn(16, 3, 8, 320, 480)
m(inputs).shape

torch.Size([16, 3, 14, 326, 486])

In [76]:
m = nn.ZeroPad2d(2)
inputs = torch.randn(1, 1, 3, 3)
m(inputs).shape

torch.Size([1, 1, 7, 7])

In [77]:
m = nn.ConstantPad1d(2, 3.5)
inputs = torch.randn(1, 2, 4)
m(inputs)

tensor([[[ 3.5000,  3.5000,  0.3589, -0.1483,  0.6900, -1.2621,  3.5000,
           3.5000],
         [ 3.5000,  3.5000, -0.3293,  0.0299, -0.0558, -0.9512,  3.5000,
           3.5000]]])

In [81]:
m = nn.ConstantPad2d((3, 0, 2, 1), 3.5)
inputs = torch.randn(1, 2, 2)
m(inputs)

tensor([[[ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
         [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
         [ 3.5000,  3.5000,  3.5000,  0.1652, -0.6606],
         [ 3.5000,  3.5000,  3.5000, -0.5096,  0.2373],
         [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000]]])

In [82]:
m = nn.ConstantPad3d(3, 3.5)
inputs = torch.randn(16, 3, 10, 20, 30)
m(inputs).shape

torch.Size([16, 3, 16, 26, 36])

In [84]:
m = nn.ELU()
inputs = torch.randn(2)
m(inputs)

tensor([-0.1375,  0.1691])

In [85]:
m = nn.Hardshrink()
input = torch.randn(2)
m(input)

tensor([ 0.5280, -1.4910])

In [86]:
m = nn.Hardsigmoid()
inputs = torch.randn(2)
m(inputs)

tensor([0.4791, 0.4177])

In [87]:
m = nn.Hardtanh(-2, 2)
inputs = torch.randn(2)
m(inputs)

tensor([-0.2508,  1.8700])

In [88]:
m = nn.Hardswish()
inputs = torch.randn(2)
m(inputs)

tensor([-0.2669, -0.1060])

In [90]:
m = nn.LeakyReLU(0.1)
inputs = torch.randn(2)
m(inputs)

tensor([ 0.6447, -0.1860])

In [91]:
m = nn.LogSigmoid()
inputs = torch.randn(2)
m(inputs)

tensor([-2.1207, -1.6190])

In [92]:
m = nn.PReLU()
inputs = torch.randn(2)
m(inputs)

tensor([-0.3178, -0.0081], grad_fn=<PreluBackward>)

In [93]:
m = nn.ReLU()
inputs = torch.randn(2)
m(inputs)

tensor([1.1494, 0.0050])

In [94]:
m = nn.ReLU6()
inputs = torch.randn(2)
m(inputs)

tensor([0.0000, 0.4635])

In [98]:
m = nn.RReLU(0.1, 0.3)
inputs = torch.randn(2)
m(inputs)

tensor([-0.2478, -0.1477])

In [99]:
m = nn.SELU()
inputs = torch.randn(2)
m(inputs)

tensor([-1.5427, -0.0530])

In [101]:
m = nn.CELU()
m(inputs)

tensor([-0.8775, -0.0301])

In [102]:
m = nn.GELU()
inputs = torch.randn(2)
m(inputs)

tensor([ 1.8233, -0.0870])

In [103]:
m = nn.Sigmoid()
inputs = torch.randn(2)
m(inputs)

tensor([0.9031, 0.8327])

In [104]:
m = nn.SiLU()
inputs = torch.randn(2)
m(inputs)

tensor([-0.2669,  0.3330])

In [105]:
m = nn.Mish()
m(inputs)

tensor([-0.3017,  0.4013])

In [107]:
m = nn.Softplus()
m(inputs)

tensor([0.3204, 0.9924])

In [108]:
m = nn.Softshrink()
m(inputs)

tensor([-0.4738,  0.0292])

In [109]:
m = nn.Softsign()
inputs = torch.randn(2)
m(inputs)

tensor([-0.1489,  0.6529])

In [111]:
m = nn.Tanh()
m(inputs)

tensor([-0.1733,  0.9546])

In [112]:
m = nn.Tanhshrink()
inputs = torch.randn(2)
m(inputs)

tensor([-0.0245,  0.4748])

In [113]:
m = nn.Threshold(0.1, 20)
m(inputs)

tensor([20.0000,  1.3485])

In [114]:
m = nn.GLU()
m(inputs)

tensor([-0.3405])

In [115]:
m = nn.Softmin()
m(inputs)

<ipython-input-115-0a067ed384ef>:2: UserWarning: Implicit dimension choice for softmin has been deprecated. Change the call to include dim=X as an argument.
  m(inputs)


tensor([0.8554, 0.1446])

In [118]:
m = nn.Softmax(dim=1)
input = torch.randn(2, 3)
output = m(input)
output

tensor([[0.3163, 0.4812, 0.2025],
        [0.5772, 0.2090, 0.2138]])

In [119]:
m = nn.Softmax2d()
inputs = torch.randn(2, 3, 12, 13)
output = m(inputs)

In [120]:
m = nn.LogSoftmax()
inputs = torch.randn(2, 3)
output = m(inputs)

<ipython-input-120-ebee4868ad3c>:3: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  output = m(inputs)


In [122]:
m = nn.BatchNorm1d(100)
input = torch.randn(20, 100)
output = m(input)

In [123]:
m = nn.BatchNorm2d(100)
inputs = torch.randn(20, 100, 35, 45)
output = m(inputs)

In [125]:
m = nn.BatchNorm3d(100)
inputs = torch.randn(20, 100, 35, 45, 10)
output = m(inputs)

In [126]:
inputs = torch.randn(20, 6, 10, 10)
m = nn.GroupNorm(1, 6)
output = m(inputs)

In [127]:
m = nn.InstanceNorm1d(100)
inputs = torch.randn(20, 100, 40)
output = m(inputs)

In [128]:
m = nn.InstanceNorm2d(100)
inputs = torch.randn(20, 100, 35, 45)
output = m(inputs)

In [129]:
m = nn.InstanceNorm3d(100, affine=True)
inputs =torch.randn(20, 100, 35, 45, 10)
output = m(inputs)

In [130]:
N, C, H, W = 20, 5, 10, 10
inputs = torch.randn(N, C, H, W)
layer_norm = nn.LayerNorm([C, H, W])
output = layer_norm(inputs)

In [131]:
lrn = nn.LocalResponseNorm(2)
signal_2d = torch.randn(32, 5, 24, 24)
signal_4d = torch.randn(16, 5, 7, 7, 7, 7)
output_2d = lrn(signal_2d)
output_4d = lrn(signal_4d)

In [133]:
rnn = nn.RNN(10, 20, 2)
input = torch.randn(5, 3, 10)
h0 = torch.randn(2, 3, 20)
output, hn = rnn(input, h0)
print(output.shape)
print(hn.shape)

torch.Size([5, 3, 20])
torch.Size([2, 3, 20])


In [134]:
rnn = nn.LSTM(10, 20, 2)
inputs = torch.randn(5, 3, 10)
h0 = torch.randn(2, 3, 20)
c0 = torch.randn(2, 3, 20)
output, (hn, cn) = rnn(input, (h0, c0))

In [135]:
rnn = nn.GRU(10, 20, 2)
inputs = torch.randn(5, 3, 10)
h0 = torch.randn(2, 3, 20)
output, hn = rnn(inputs, h0)

In [136]:
rnn = nn.RNNCell(10, 20)
input = torch.randn(6, 3, 10)
hx = torch.randn(3, 20)
output = []
for i in range(6):
    hx = rnn(input[i], hx)
    output.append(hx)

In [137]:
rnn = nn.LSTMCell(10, 20)
input = torch.randn(2, 3, 10)
hx = torch.randn(3, 20)
cx = torch.randn(3, 20)
output = []
for i in range(input.size()[0]):
    hx, cx = rnn(input[i], (hx, cx))
    output.append(hx)
output = torch.stack(output, dim=0)

In [138]:
rnn = nn.GRUCell(10, 20)
input = torch.randn(6, 3, 10)
hx = torch.randn(3, 20)
output = []
for i in range(6):
    hx = rnn(input[i], hx)
    output.append(hx)

In [139]:
transformer_model = nn.Transformer(nhead=16, num_encoder_layers=12)
src = torch.rand((10, 32, 512))
tgt = torch.rand((20, 32, 512))
out = transformer_model(src, tgt)

In [140]:
encoder_layer = nn.TransformerEncoderLayer(d_model=512, nhead=8)
transformer_encoder  = nn.TransformerEncoder(encoder_layer, num_layers=6)
src = torch.rand(10, 32, 512)
out = transformer_encoder(src)

In [143]:
decoder_layer = nn.TransformerDecoderLayer(d_model=512, nhead=8)
transformer_decoder = nn.TransformerDecoder(decoder_layer, num_layers=6)
memory = torch.rand(10, 32, 512)
tgt = torch.rand(20, 32, 512)
out = transformer_decoder(tgt, memory)

In [144]:
m = nn.Identity(54, unused_argument1 = 0.1, unused_argument2=False)
inputs = torch.randn(128, 20)
output = m(inputs)
print(output.size())

torch.Size([128, 20])


In [146]:
m = nn.Linear(20, 30)
inputs = torch.randn(128, 20)
outputs = m(inputs)
outputs.size()

torch.Size([128, 30])

In [147]:
m = nn.Bilinear(20, 30, 40)
input1 = torch.randn(128, 20)
input2 = torch.randn(128, 30)
output = m(input1, input2)
print(output.size())

torch.Size([128, 40])


In [148]:
m = nn.Dropout(p=0.2)
inputs =torch.randn(20, 16)
output = m(inputs)

In [149]:
m = nn.Dropout2d(p=0.2)
inputs = torch.randn(20, 16, 32, 32)
output = m(inputs)

In [150]:
m = nn.AlphaDropout(p=0.2)
inputs = torch.randn(20, 16)
output = m(inputs)

In [151]:
m = nn.FeatureAlphaDropout(p=0.2)
input = torch.randn(20, 16, 4, 32, 32)
output = m(input)

In [153]:
embedding = nn.Embedding(10, 3)
inputs = torch.LongTensor([[0, 2, 0, 5]])
embedding(inputs)

tensor([[[ 0.2647,  1.0165, -0.2257],
         [ 1.2145,  0.4501,  0.7898],
         [ 0.2647,  1.0165, -0.2257],
         [-0.8150, -0.7290,  0.1405]]], grad_fn=<EmbeddingBackward>)

In [154]:
embedding_sum = nn.EmbeddingBag(10, 3, mode="sum")
inputs = torch.tensor([1, 2, 4, 5, 4, 3, 2, 9], dtype=torch.long)
offsets = torch.tensor([0, 4], dtype=torch.long)
embedding_sum(inputs, offsets)

tensor([[-1.0896, -1.9020,  4.5266],
        [ 0.6084, -3.0246,  4.9148]], grad_fn=<EmbeddingBagBackward>)

In [156]:
input1 = torch.randn(100, 128)
input2 = torch.randn(100, 128)
cos = nn.CosineSimilarity(dim=1, eps=1e-6)
output = cos(input1, input2)

In [157]:
pdist = nn.PairwiseDistance(p = 2)
input1 = torch.randn(100, 128)
input2 = torch.randn(100, 128)
output = pdist(input1, input2)

In [159]:
loss = nn.L1Loss()
inputs = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5)
output = loss(inputs, target)
output.backward()

In [160]:
loss = nn.MSELoss()
inputs = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5)
output = loss(inputs, target)
output.backward()

In [162]:
loss = nn.CrossEntropyLoss()
inputs = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)
output = loss(inputs, target)
output.backward()

In [167]:
T = 50
C = 20
N = 16
S = 30
S_min = 10
inputs = torch.randn(T, N, C).log_softmax(2).detach().requires_grad_()
target = torch.randint(low=1, high=C, size=(N, S))
input_lengths = torch.full(size=(N, ), fill_value=T, dtype=torch.long)
target_lengths = torch.randint(low=S_min, high=S, size=(N,), dtype=torch.long)
ctc_loss = nn.CTCLoss()
loss = ctc_loss(inputs, target, input_lengths, target_lengths)
loss.backward()

In [171]:
m = nn.LogSoftmax(dim=1)
loss = nn.NLLLoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.tensor([1, 0, 4])
output = loss(m(input), target)
output.backward()

In [172]:
loss = nn.PoissonNLLLoss()
log_input = torch.randn(5, 2, requires_grad=True)
target = torch.randn(5, 2)
output = loss(log_input, target)
output.backward()

In [173]:
loss = nn.GaussianNLLLoss()
inputs = torch.randn(5, 2, requires_grad=True)
target = torch.randn(5, 2)
var = torch.ones(5, 2, requires_grad=True)
output = loss(inputs, target, var)
output.backward()

In [174]:
kl_loss = nn.KLDivLoss(reduction="batchmean")
inputs = F.log_softmax(torch.randn(3, 5, requires_grad=True))
target = F.softmax(torch.rand(3, 5))
output = kl_loss(inputs, target)
output.backward()

<ipython-input-174-1cd8a934e2bc>:2: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  inputs = F.log_softmax(torch.randn(3, 5, requires_grad=True))
<ipython-input-174-1cd8a934e2bc>:3: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  target = F.softmax(torch.rand(3, 5))


In [176]:
m = nn.Sigmoid()
loss = nn.BCELoss()
input = torch.randn(3, requires_grad=True)
target = torch.empty(3).random_(2)
output = loss(m(input), target)
output.backward()

In [177]:
loss = nn.BCEWithLogitsLoss()
inputs = torch.randn(3, requires_grad=True)
target = torch.empty(3).random_(2)
output = loss(inputs, target)
output.backward()

In [178]:
loss = nn.MarginRankingLoss()
input1 = torch.randn(3, requires_grad=True)
input2 = torch.randn(3, requires_grad=True)
target = torch.randn(3).sign()
output = loss(input1, input2, target)
output.backward()

In [179]:
loss = nn.MultiLabelMarginLoss()
x = torch.FloatTensor([[0.1, 0.2, 0.4, 0.8]])
y = torch.LongTensor([[3, 0, -1, 1]])
loss(x, y)

tensor(0.8500)

In [180]:
loss = nn.MultiMarginLoss()
x = torch.tensor([[0.1, 0.2, 0.4, 0.8]])
y = torch.tensor([3])
loss(x, y)

tensor(0.3250)

In [181]:
triplet_loss = nn.TripletMarginLoss(margin=1.0, p=2)
anchor = torch.randn(100, 128, requires_grad=True)
positive = torch.randn(100, 128, requires_grad=True)
negative = torch.randn(100, 128, requires_grad=True)
output = triplet_loss(anchor, positive, negative)
output.backward()

In [183]:
embedding = nn.Embedding(1000, 128)
anchor_ids = torch.randint(0, 1000, (1, ))
positive_ids = torch.randint(0, 1000, (1, ))
negative_ids = torch.randint(0, 1000, (1, ))
anchor = embedding(anchor_ids)
positive = embedding(positive_ids)
negative = embedding(negative_ids)
triplet_loss = nn.TripletMarginWithDistanceLoss(distance_function=nn.PairwiseDistance())
output = triplet_loss(anchor, positive, negative)
output.backward()

In [184]:
pixel_shuffle = nn.PixelShuffle(3)
inputs = torch.randn(1, 9, 4, 4)
output = pixel_shuffle(inputs)
print(output.size())

torch.Size([1, 1, 12, 12])


In [187]:
pixel_unshuffle = nn.PixelUnshuffle(3)
inputs = torch.randn(1, 1, 12, 12)
output = pixel_unshuffle(inputs)
print(output.size())

torch.Size([1, 9, 4, 4])


In [188]:
inputs = torch.arange(1, 5, dtype=torch.float32).view(1, 1, 2, 2)
m = nn.Upsample(scale_factor=2, mode="nearest")
m(inputs)

tensor([[[[1., 1., 2., 2.],
          [1., 1., 2., 2.],
          [3., 3., 4., 4.],
          [3., 3., 4., 4.]]]])

In [189]:
m = nn.Upsample(scale_factor=2, mode="bilinear")
m(inputs)

C:\Users\jatin\anaconda3\lib\site-packages\torch\nn\functional.py:3609: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn(


tensor([[[[1.0000, 1.2500, 1.7500, 2.0000],
          [1.5000, 1.7500, 2.2500, 2.5000],
          [2.5000, 2.7500, 3.2500, 3.5000],
          [3.0000, 3.2500, 3.7500, 4.0000]]]])

In [190]:
inputs = torch.arange(1, 5, dtype=torch.float32).view(1, 1, 2, 2)
m = nn.UpsamplingNearest2d(scale_factor=2)
m(inputs)

tensor([[[[1., 1., 2., 2.],
          [1., 1., 2., 2.],
          [3., 3., 4., 4.],
          [3., 3., 4., 4.]]]])

In [193]:
m = nn.UpsamplingBilinear2d(scale_factor=2)
m(inputs)

tensor([[[[1.0000, 1.3333, 1.6667, 2.0000],
          [1.6667, 2.0000, 2.3333, 2.6667],
          [2.3333, 2.6667, 3.0000, 3.3333],
          [3.0000, 3.3333, 3.6667, 4.0000]]]])

In [194]:
channel_shuffle = nn.ChannelShuffle(2)
inputs = torch.randn(1, 4, 2, 2)
channel_shuffle(inputs)

tensor([[[[-0.5276, -0.1613],
          [-0.9327,  1.5449]],

         [[-0.8505, -1.2795],
          [ 0.3754,  0.4740]],

         [[-0.0779,  1.2348],
          [-0.4770,  0.4926]],

         [[-0.2319, -0.6507],
          [ 0.0496,  1.7974]]]])

In [195]:
net = torch.nn.DataParallel(model, device_ids=[0, 1, 2])
output = net(input_var)

NameError: name 'input_var' is not defined

In [3]:
import torch.nn.utils.prune as prune
import torch.nn as nn
import torch

In [198]:
m = prune.identity(nn.Linear(2, 3), "bias")
print(m.bias_mask)

tensor([1., 1., 1.])


In [199]:
m = prune.random_unstructured(nn.Linear(2, 3), "weight", amount=1)
torch.sum(m.weight_mask==0)

tensor(1)

In [200]:
m = prune.l1_unstructured(nn.Linear(2, 3), "weight", amount=0.2)
m.state_dict().keys()

odict_keys(['bias', 'weight_orig', 'weight_mask'])

In [201]:
m = prune.random_structured(nn.Linear(5, 3), "weight", amount=3, dim=1)
columns_pruned = int(sum(torch.sum(m.weight, dim=0) == 0))
print(columns_pruned)

3


In [203]:
m = prune.ln_structured(nn.Conv2d(5, 3, 2), "weight", amount=0.3, dim=1, n=float('-inf'))

In [9]:
m = prune.custom_from_mask(nn.Linear(5, 3), name="bias", mask=torch.tensor([0, 1, 0]))
print(m.bias_mask)

tensor([0., 1., 0.])


In [12]:
m = prune.random_unstructured(nn.Linear(5, 7), name="weight", amount=0.2)
m = prune.remove(m, name="weight")

In [13]:
m = nn.Linear(5, 7)
print(prune.is_pruned(m))
prune.random_unstructured(m, name="weight", amount=0.2)
print(prune.is_pruned(m))

False
True


In [22]:
import torch.nn.utils.parametrizations as s


In [24]:
snm = s.spectral_norm(nn.Linear(20, 40))
print(snm)
torch.linalg.matrix_norm(snm.weight, 2)

ParametrizedLinear(
  in_features=20, out_features=40, bias=True
  (parametrizations): ModuleDict(
    (weight): ParametrizationList(
      (0): _SpectralNorm()
    )
  )
)


tensor(1.2321, grad_fn=<CopyBackwards>)

In [26]:
import torch
import torch.nn as nn
import torch.nn.utils.parametrize as P
class Symmetric(nn.Module):
    def forward(self, X):
        return X.triu() + X.triu(1).T
    def right_inverse(self, A):
        return A.triu()
m = nn.Linear(5, 5)
P.register_parametrization(m, "weight", Symmetric())
print(torch.allclose(m.weight, m.weight.T))
A = torch.randn(5, 5)
A = A + A.T
m.weight = A
print(torch.allclose(m.weight, A))

True
True


In [28]:
with P.cached():
    print("yes")

yes


In [31]:
from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence
seq = torch.tensor([[1, 2, 0], [3, 0, 0], [4, 5, 6]])
lens = [2, 1, 3]
packed = pack_padded_sequence(seq, lens, batch_first=True, enforce_sorted=False)
print(packed)
seq_unpacked, lens_unpacked = pad_packed_sequence(packed, batch_first=True)
print(seq_unpacked)
lens_unpacked

PackedSequence(data=tensor([4, 1, 3, 5, 2, 6]), batch_sizes=tensor([3, 2, 1]), sorted_indices=tensor([2, 0, 1]), unsorted_indices=tensor([1, 2, 0]))
tensor([[1, 2, 0],
        [3, 0, 0],
        [4, 5, 6]])


tensor([2, 1, 3])

In [32]:
from torch.nn.utils.rnn import pad_sequence
a = torch.ones(25, 300)
b = torch.ones(22, 300)
c = torch.ones(15, 300)
pad_sequence([a, b, c]).size()

torch.Size([25, 3, 300])

In [33]:
from torch.nn.utils.rnn import pack_sequence
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5])
c = torch.tensor([6])
pack_sequence([a, b, c])

PackedSequence(data=tensor([1, 4, 6, 2, 5, 3]), batch_sizes=tensor([3, 2, 1]), sorted_indices=None, unsorted_indices=None)

In [34]:
inputs = torch.randn(32, 1, 5, 5)
m = nn.Flatten()
output = m(inputs)
output.size()

torch.Size([32, 25])

In [35]:
inputs = torch.randn(2, 50)
m = nn.Sequential(nn.Linear(50, 50), nn.Unflatten(1, (2, 5, 5)))
output = m(inputs)
output.size()

torch.Size([2, 2, 5, 5])

In [36]:
import torch.nn.functional as f

In [39]:
inputs= torch.randn(33, 16, 30)
filters = torch.randn(20, 16, 5)
f.conv1d(inputs, filters).size()

torch.Size([33, 20, 26])

In [42]:
filters = torch.randn(8, 4, 3, 3)
inputs = torch.randn(1, 4, 5, 5)
f.conv2d(inputs, filters, padding=1).size()

torch.Size([1, 8, 5, 5])

In [44]:
filters = torch.randn(33, 16, 3, 3, 3)
inputs = torch.randn(20, 16, 50, 10, 20)
f.conv3d(inputs, filters).size()

torch.Size([20, 33, 48, 8, 18])

In [46]:
inputs = torch.randn(20, 16, 50)
weights = torch.randn(16, 33, 5)
f.conv_transpose1d(inputs, weights).size()

torch.Size([20, 33, 54])

In [48]:
inputs = torch.randn(1, 4, 5, 5)
weights = torch.randn(4, 8, 3, 3)
f.conv_transpose2d(inputs, weights, padding=1).size()

torch.Size([1, 8, 5, 5])

In [50]:
inputs = torch.randn(20, 16, 50, 10, 20)
weights = torch.randn(16, 33, 3, 3, 3)
f.conv_transpose3d(inputs, weights).size()

torch.Size([20, 33, 52, 12, 22])

In [51]:
input = torch.tensor([[[1, 2, 3, 4, 5, 6, 7]]], dtype=torch.float32)
f.avg_pool1d(input, kernel_size=3, stride=2)

tensor([[[2., 4., 6.]]])

In [53]:
inputs = torch.randn(20, 16, 50, 32)
f.fractional_max_pool2d(inputs,3, output_size=(13, 12)).size()

torch.Size([20, 16, 13, 12])

In [54]:
inputs = torch.randn(20, 16, 50, 32, 16)
f.fractional_max_pool3d(inputs, 3, output_size=(13, 12, 11)).size()

torch.Size([20, 16, 13, 12, 11])

In [56]:
logits = torch.randn(20, 32)
f.gumbel_softmax(logits, tau=1, hard=False).size()

torch.Size([20, 32])

In [57]:
inputs = torch.tensor([[1, 2, 4, 5], [4, 3, 2, 9]])
embedding_matrix = torch.rand(10, 3)
f.embedding(inputs, embedding_matrix)

tensor([[[0.9998, 0.2908, 0.4848],
         [0.8990, 0.1109, 0.3556],
         [0.0149, 0.2224, 0.3519],
         [0.7622, 0.4135, 0.6075]],

        [[0.0149, 0.2224, 0.3519],
         [0.2178, 0.5643, 0.5607],
         [0.8990, 0.1109, 0.3556],
         [0.6854, 0.9136, 0.9725]]])

In [58]:
embedding_matrix = torch.rand(10, 3)
inputs = torch.tensor([1, 2, 3, 4, 5, 3, 2, 9])
offsets = torch.tensor([0, 4])
f.embedding_bag(inputs, embedding_matrix, offsets)

tensor([[0.5006, 0.7477, 0.3570],
        [0.3267, 0.4702, 0.5598]])

In [60]:
f.one_hot(torch.arange(0, 5) % 3, num_classes=5)

tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0]])

In [62]:
input1 = torch.randn(100, 128)
input2 = torch.randn(100, 128)
f.cosine_similarity(input1, input2).shape

torch.Size([100])

In [63]:
inputs = torch.randn(3, 2, requires_grad=True)
target = torch.randn(3, 2, requires_grad=False)
loss = f.binary_cross_entropy(torch.sigmoid(inputs), target)
loss.backward()

In [64]:
inputs = torch.randn(3, requires_grad=True)
target = torch.empty(3).random_(2)
loss = f.binary_cross_entropy_with_logits(inputs, target)
loss.backward()

In [65]:
inputs = torch.randn(3, 5, requires_grad=True)
target = torch.randint(5, (3, ), dtype=torch.int64)
loss = f.cross_entropy(inputs, target)
loss.backward()

In [67]:
log_probs = torch.randn(50, 16, 20).log_softmax(2).detach().requires_grad_()
targets = torch.randint(1, 20, (16, 30), dtype=torch.long)
input_lengths = torch.full((16, ), 50, dtype=torch.long)
target_lengths = torch.randint(10, 30, (16, ), dtype=torch.long)
loss = f.ctc_loss(log_probs, targets, input_lengths, target_lengths)
loss.backward()

In [71]:
inputs = torch.randn(3, 5, requires_grad=True)
target = torch.tensor([1, 0, 4])
output = f.nll_loss(f.log_softmax(inputs), target)
output.backward()

<ipython-input-71-3f88f15e86d6>:3: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  output = f.nll_loss(f.log_softmax(inputs), target)


In [72]:
inputs = torch.randn(1, 9, 4, 4)
output = f.pixel_shuffle(inputs, 3)
print(output.size())

torch.Size([1, 1, 12, 12])


In [73]:
inputs = torch.randn(1, 1, 12, 12)
output = f.pixel_unshuffle(inputs, 3)
print(output.shape)

torch.Size([1, 9, 4, 4])


In [74]:
t4d = torch.empty(3, 3, 4, 2)
p1d = (1, 1)
out = f.pad(t4d, p1d, "constant")
print(out.size())

torch.Size([3, 3, 4, 4])
