In [1]:
import tensorflow as tf
import numpy as np

In [2]:
T, F = True, False
tf.ragged.boolean_mask(data=[[1, 2, 3], [4, 5, 6], [7, 8, 9]], mask=[[T, F, T], [F, F, F], [T, F, F]]).to_list()

[[1, 3], [], [7]]

In [3]:
tf.ragged.constant([[1, 2], [3], [4, 5, 6]])

<tf.RaggedTensor [[1, 2], [3], [4, 5, 6]]>

In [4]:
tf.ragged.cross([tf.ragged.constant([['a'], ['b', 'c']]), tf.ragged.constant([['d'], ['e']]), 
                 tf.ragged.constant([['f'], ['g']])])

<tf.RaggedTensor [[b'a_X_d_X_f'], [b'b_X_e_X_g', b'c_X_e_X_g']]>

In [5]:
tf.ragged.cross_hashed([tf.ragged.constant([['a'], ['b', 'c']]), tf.ragged.constant([['d'], ['e']]), 
                 tf.ragged.constant([['f'], ['g']])])

<tf.RaggedTensor [[5684865645872741371], [1392610987527938559, 6629649657679214674]]>

In [7]:
rt = tf.ragged.constant([[1, 2, 3], [], [4]])
tf.ragged.map_flat_values(tf.ones_like, rt)

<tf.RaggedTensor [[1, 1, 1], [], [1]]>

In [8]:
tf.ragged.range([0, 5, 8], [3, 3, 12]).to_list()

[[0, 1, 2], [], [8, 9, 10, 11]]

In [10]:
print(tf.ragged.row_splits_to_segment_ids([0, 3, 3, 5, 6, 9]))

tf.Tensor([0 0 0 2 2 3 4 4 4], shape=(9,), dtype=int64)


In [11]:
print(tf.ragged.segment_ids_to_row_splits([0, 0, 0, 2, 2, 3, 4, 4, 4]))

tf.Tensor([0 3 3 5 6 9], shape=(6,), dtype=int64)


In [13]:
t1 = tf.ragged.constant([[1, 2], [3, 4, 5]])
t2 = tf.ragged.constant([[6], [7, 7, 8]])
print(tf.ragged.stack([t1, t2], axis=0))
print(tf.ragged.stack([t1, t2], axis=1))

<tf.RaggedTensor [[[1, 2], [3, 4, 5]],
 [[6], [7, 7, 8]]]>
<tf.RaggedTensor [[[1, 2], [6]],
 [[3, 4, 5], [7, 7, 8]]]>


In [14]:
data = ['a', 'b', 'c', 'd', 'e']
partitions = [3, 0, 2, 2, 3]
num_partitions = 5
tf.ragged.stack_dynamic_partitions(data, partitions, num_partitions)

<tf.RaggedTensor [[b'b'], [], [b'c', b'd'], [b'a', b'e'], []]>

In [15]:
g = tf.random.Generator.from_seed(123)
g.normal(shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.8673864 , -0.29899067, -0.9310337 ],
       [-1.5828488 ,  1.2481191 , -0.6770643 ]], dtype=float32)>

In [18]:
tf.random.categorical(tf.math.log([[0.5, 0.5]]), 5)

<tf.Tensor: shape=(1, 5), dtype=int64, numpy=array([[0, 1, 1, 0, 1]], dtype=int64)>

In [19]:
tf.random.create_rng_state(1234, "philox")

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1234,    0,    0], dtype=int64)>

In [23]:
tf.random.gamma([10], [0.5, 1.5]).numpy().shape

(10, 2)

In [24]:
tf.random.normal([2, 2], 0, 1, tf.float32, seed=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.8113182 ,  1.4845988 ],
       [ 0.06532937, -2.4427042 ]], dtype=float32)>

In [25]:
tf.random.poisson([5], [0.5, 1.5])

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[2., 2.],
       [0., 4.],
       [0., 2.],
       [1., 2.],
       [0., 1.]], dtype=float32)>

In [26]:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))

tf.Tensor([0.5380393], shape=(1,), dtype=float32)
tf.Tensor([0.3253647], shape=(1,), dtype=float32)


In [28]:
counts = [10., 20.]
probs = [0.8]
binomial_samples = tf.random.stateless_binomial(shape=[2], seed=[123, 456], counts=counts, probs=probs)
binomial_samples

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 16])>

In [29]:
samples = tf.random.stateless_categorical(tf.math.log([[0.5, 0.5]]), 5, seed=[7, 17])

In [30]:
samples = tf.random.stateless_gamma([10, 2], seed=[12, 34], alpha=[0.5, 1.5])

In [36]:
tf.random.stateless_normal(shape=[2, 2], seed=[2, 4])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.359035  ,  0.9027202 ],
       [-0.06132288,  0.16664371]], dtype=float32)>

In [41]:
samples = tf.random.stateless_poisson([10, 2], seed=[12, 34], lam=[5, 15])

In [42]:
tf.random.truncated_normal(shape=[2], mean=3, stddev=1, dtype=tf.float32)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.8121715, 3.7068176], dtype=float32)>

In [44]:
tf.random.uniform(shape=[2]).numpy()

array([0.6765541 , 0.31846166], dtype=float32)

In [46]:
master_seed = [1, 2]
replica_id = 3
replica_seed = tf.random.experimental.stateless_fold_in(master_seed, replica_id)
print(replica_seed.numpy())

[1105988140          3]


In [47]:
tf.random.stateless_normal(shape=[3], seed=replica_seed).numpy()

array([0.03197195, 0.8979765 , 0.13253039], dtype=float32)

In [48]:
seed = [1, 2]
new_seeds = tf.random.experimental.stateless_split(seed, num=3)

In [49]:
new_seeds

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1105988140, 1738052849],
       [-335576002,  370444179],
       [  10670227, -246211131]])>

In [58]:
tf.add(2, 3)

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [71]:
a = tf.constant([[[1,2., 3. ,4],
                 [5, 6, 7, 8.]],
                 [[1, 2, 3, 4],
                 [5, 6, 7, 8]]])
b = 0.2
args = a
arg = b
tf.raw_ops.AdjustContrastv2(images=a, contrast_factor=b)

<tf.Tensor: shape=(2, 2, 4), dtype=float32, numpy=
array([[[2.6, 3.6, 4.6, 5.6],
        [3.4, 4.4, 5.4, 6.4]],

       [[2.6, 3.6, 4.6, 5.6],
        [3.4, 4.4, 5.4, 6.4]]], dtype=float32)>

In [72]:
tf.raw_ops.AnonymousMemoryCache()

AnonymousMemoryCache(handle=<tf.Tensor: shape=(), dtype=resource, value=<Resource Tensor>>, deleter=<tf.Tensor: shape=(), dtype=variant, value=<[empty]>>)

In [11]:
import tensorflow as tf
import collections
a = collections.OrderedDict([
    ((0, 0, 0), 1),
    ((0, 0, 1), 2),
    ((0, 1, 0), 3),
    ((1, 0, 0), 4),
    ((1, 1, 0), 5),
    ((1, 1, 1), 6)
])
a = tf.sparse.SparseTensor(list(a.keys()), list(a.values()), dense_shape=[2, 2, 2])
b = collections.OrderedDict([
    ((0, 0, 0), 1),
    ((0, 0, 1), 3),
    ((0, 1, 0), 2),
    ((1, 0, 0), 4),
    ((1, 0, 1), 5),
    ((1, 1, 0), 5),
    ((1, 1, 1), 6),
    ((1, 1, 2), 7),
    ((1, 1, 3), 8)
])
b = tf.sparse.SparseTensor(list(b.keys()), list(b.values()), dense_shape=[2, 2, 4])
tf.sets.difference(a, b)

In [15]:
a = collections.OrderedDict([
    ((0, 0, 0), 1),
    ((0, 0, 1), 2),
    ((0, 1, 0), 3),
    ((1, 0, 0), 4),
    ((1, 1, 0), 5),
    ((1, 1, 1), 6)
])
a = tf.sparse.SparseTensor(list(a.keys()), list(a.values()), dense_shape=[2, 2, 2])
b = collections.OrderedDict([
    ((0, 0, 0), 1),
    ((1, 0, 0), 4),
    ((1, 1, 0), 5),
    ((1, 1, 1), 6),
    ((1, 1, 2), 7),
    ((1, 1, 3), 8)
])
b = tf.sparse.SparseTensor(list(b.keys()), list(b.values()), dense_shape=[2, 2, 4])
tf.sets.intersection(a, b)

In [17]:
tf.sets.size(a)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 1],
       [1, 2]])>

In [18]:
tf.sets.union(a, b)

In [20]:
x = tf.signal.fftshift([0., 1., 2., 3., 4., -5., -4., -3., -2., -1.])
x

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.], dtype=float32)>

In [21]:
audio = tf.random.normal([3, 9152])
frames = tf.signal.frame(audio, 512, 180)
print(frames.shape)
frames = tf.signal.frame(audio, 512, 180, pad_end=True)
frames.shape

(3, 49, 512)


TensorShape([3, 51, 512])

In [2]:
x = tf.signal.ifftshift([[0., 1., 2.], [3., 4., -4.], [-3., -2, -2.]])
x.numpy()

array([[ 4., -4.,  3.],
       [-2., -2., -3.],
       [ 1.,  2.,  0.]], dtype=float32)

In [5]:
@tf.function
def compare_round_trip():
    samples = 1000
    frame_length = 400
    halflen = frame_length // 2
    waveform = tf.random.normal(dtype=tf.float32, shape=[samples])
    waveform_pad = tf.pad(waveform, [[halflen, 0], ])
    mdct = tf.signal.mdct(waveform_pad, frame_length, pad_end=True, window_fn=tf.signal.vorbis_window)
    inverse_mdct = tf.signal.inverse_mdct(mdct, window_fn = tf.signal.vorbis_window)
    inverse_mdct = inverse_mdct[halflen: halflen + samples]
    return waveform, inverse_mdct
waveform, inverse_mdct = compare_round_trip()
np.allclose(waveform.numpy(), inverse_mdct.numpy(), rtol=1e-4, atol=1e-4)

True

In [6]:
frame_length = 400
frame_step = 160
waveform = tf.random.normal(dtype=tf.float32, shape=[1000])
stft = tf.signal.stft(waveform, frame_length, frame_step)
inverse_stft = tf.signal.inverse_stft(stft, frame_length, frame_step, 
                                      window_fn=tf.signal.inverse_stft_window_fn(frame_step))

In [7]:
stft

<tf.Tensor: shape=(4, 257), dtype=complex64, numpy=
array([[ -2.8446941  +0.j        ,   5.3732967  +1.7902546j ,
          1.1398463  -7.836358j  , ...,  -2.1922164  -5.0909967j ,
         -0.5662749 +11.075725j  ,   7.495332   +0.j        ],
       [ -7.8079243  +0.j        ,   6.7324414  -0.28440523j,
         -5.177349   +1.5616751j , ...,  -2.0817778 +12.072857j  ,
         20.032576   -9.07289j   , -27.01425    +0.j        ],
       [ -7.2388678  +0.j        ,   0.70787805 +4.753273j  ,
          3.2563577  +3.5734901j , ...,  13.32057   +15.141276j  ,
          0.57915413-19.72313j   , -14.363477   +0.j        ],
       [  0.07500219 +0.j        ,  -1.6847193  +0.7277355j ,
          1.8169441  +3.4809396j , ...,  -9.732126   +3.4250848j ,
          2.6644375  +6.021352j  ,   3.2287974  +0.j        ]],
      dtype=complex64)>

In [11]:
tf.signal.kaiser_bessel_derived_window(12)

<tf.Tensor: shape=(12,), dtype=float32, numpy=
array([0.00495747, 0.15976831, 0.5168664 , 0.8560661 , 0.98715454,
       0.9999877 , 0.9999877 , 0.98715454, 0.8560661 , 0.5168664 ,
       0.15976831, 0.00495747], dtype=float32)>

In [26]:
data2 = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])
tf.sparse.to_dense(data2)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 0]])>

In [22]:
data1 = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])
data3 = tf.sparse.add(data, data1)
tf.sparse.to_dense(data3)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[2, 0, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 0]])>

In [23]:
data = np.array([[10, 20, 30, 20], [11, 101, 11, 10001]], dtype=np.int64)
output = tf.sparse.bincount(data, axis=-1)
print(output)

SparseTensor(indices=tf.Tensor(
[[    0    10]
 [    0    20]
 [    0    30]
 [    1    11]
 [    1   101]
 [    1 10001]], shape=(6, 2), dtype=int64), values=tf.Tensor([1 2 1 2 1 1], shape=(6,), dtype=int64), dense_shape=tf.Tensor([    2 10002], shape=(2,), dtype=int64))


In [27]:
tf.sparse.concat(1, [data2, data1])

In [28]:
inp_0 = tf.constant([["a"], ["b"]])
inp_1 = tf.constant([["c"], ["d"]])
output = tf.sparse.cross([inp_0, inp_1], separator="_Y_")
output.values

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'a_Y_c', b'b_Y_d'], dtype=object)>

In [33]:
sp = tf.sparse.SparseTensor(indices=[[3, 4, 1]], values=[7,], dense_shape=[10, 10, 3])
tf.sparse.expand_dims(sp, axis=0).shape.as_list()

[1, 10, 10, 3]

In [35]:
tf.sparse.eye(5, 5).shape.as_list()

[5, 5]

In [39]:
a = tf.sparse.fill_empty_rows(data1, default_value=-1)
a

(<tensorflow.python.framework.sparse_tensor.SparseTensor at 0x2cb803dd070>,
 <tf.Tensor: shape=(3,), dtype=bool, numpy=array([False, False,  True])>)

In [40]:
sp = tf.sparse.from_dense([0, 0, 3, 0, 1])
sp.shape.as_list()

[5]

In [41]:
print(sp.indices.numpy())
print(sp.values.numpy())

[[2]
 [4]]
[3 1]


In [42]:
s = tf.sparse.from_dense([
    [1, 2, 0],
    [0, 4, 0],
    [1, 0, 0]
])
tf.sparse.to_dense(tf.sparse.map_values(tf.ones_like, s)).numpy()

array([[1, 1, 0],
       [0, 1, 0],
       [1, 0, 0]])

In [55]:
sp_zero = tf.sparse.SparseTensor([[0]], [0], [7])
sp_one = tf.sparse.SparseTensor([[1]], [1], [7])
res = tf.sparse.maximum(sp_zero, sp_one)
print(res.indices)
print(res.values)
print(res.dense_shape)

tf.Tensor(
[[0]
 [1]], shape=(2, 1), dtype=int64)
tf.Tensor([0 1], shape=(2,), dtype=int32)
tf.Tensor([7], shape=(1,), dtype=int64)


In [56]:
res = tf.sparse.minimum(sp_zero, sp_one)
print(res.indices)
print(res.values)
print(res.dense_shape)

tf.Tensor(
[[0]
 [1]], shape=(2, 1), dtype=int64)
tf.Tensor([0 0], shape=(2,), dtype=int32)
tf.Tensor([7], shape=(1,), dtype=int64)


In [57]:
x = tf.sparse.SparseTensor([[0, 0], [0, 2], [1, 1]], [1, 2, 3], [2, 3])
print(tf.sparse.reduce_max(x))
print(tf.sparse.reduce_max(x, 0))
print(tf.sparse.reduce_max(x, 1))
print(tf.sparse.reduce_max(x, 1, keepdims=True))
print(tf.sparse.reduce_max(x, [0, 1]))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 3 2], shape=(3,), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)
tf.Tensor(
[[2]
 [3]], shape=(2, 1), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [58]:
x = tf.sparse.SparseTensor([[0, 0], [0, 2], [1, 1]], [1, 1, 1], [2, 3])
print(tf.sparse.reduce_sum(x))
print(tf.sparse.reduce_sum(x, 0))
print(tf.sparse.reduce_sum(x, 1))
print(tf.sparse.reduce_sum(x, 1, keepdims=True))
print(tf.sparse.reduce_sum(x, [0, 1]))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([2 1], shape=(2,), dtype=int32)
tf.Tensor(
[[2]
 [1]], shape=(2, 1), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [62]:
c = tf.constant([[1, 2, 3, 4], [-1, -2, -3, -4], [5, 6, 7, 8]])
print(tf.sparse.segment_sum(c, tf.constant([0, 1]), tf.constant([0, 0])))
print(tf.sparse.segment_sum(c, tf.constant([0, 1]), tf.constant([0, 1])))
print(tf.sparse.segment_sum(c, tf.constant([0, 1]), tf.constant([0, 2]), num_segments=4))
print(tf.sparse.segment_sum(c, tf.constant([0, 1, 2]), tf.constant([0, 0, 1])))
print(tf.math.segment_sum(c, tf.constant([0, 0, 1])))

tf.Tensor([[0 0 0 0]], shape=(1, 4), dtype=int32)
tf.Tensor(
[[ 1  2  3  4]
 [-1 -2 -3 -4]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[ 1  2  3  4]
 [ 0  0  0  0]
 [-1 -2 -3 -4]
 [ 0  0  0  0]], shape=(4, 4), dtype=int32)
tf.Tensor(
[[0 0 0 0]
 [5 6 7 8]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[0 0 0 0]
 [5 6 7 8]], shape=(2, 4), dtype=int32)


In [64]:
indices = [[0, 2], [0, 4], [0, 5], [1, 0], [1, 1]]
values = [1, 2, 3, 4, 5]
t = tf.SparseTensor(indices=indices, values=values, dense_shape=[2, 7])
tf.sparse.to_dense(t)

<tf.Tensor: shape=(2, 7), dtype=int32, numpy=
array([[0, 0, 1, 0, 2, 3, 0],
       [4, 5, 0, 0, 0, 0, 0]])>

In [65]:
output = tf.sparse.split(sp_input=t, num_split=2, axis=1)
print(tf.sparse.to_dense(output[1]))
print(tf.sparse.to_dense(output[0]))

tf.Tensor(
[[2 3 0]
 [0 0 0]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[0 0 1 0]
 [4 5 0 0]], shape=(2, 4), dtype=int32)


In [66]:
output = tf.sparse.split(sp_input=t, num_split=2, axis=0)
print(tf.sparse.to_dense(output[1]))
print(tf.sparse.to_dense(output[0]))

tf.Tensor([[4 5 0 0 0 0 0]], shape=(1, 7), dtype=int32)
tf.Tensor([[0 0 1 0 2 3 0]], shape=(1, 7), dtype=int32)


In [67]:
output = tf.sparse.split(sp_input=t, num_split=2, axis=-1)
print(tf.sparse.to_dense(output[1]))
print(tf.sparse.to_dense(output[0]))

tf.Tensor(
[[2 3 0]
 [0 0 0]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[0 0 1 0]
 [4 5 0 0]], shape=(2, 4), dtype=int32)


In [68]:
sp_input = tf.SparseTensor(dense_shape=[3, 5], values=[7, 8, 9], indices=[[0, 1], [0, 3], [2, 0]])
tf.sparse.to_dense(sp_input).numpy()

array([[0, 7, 0, 8, 0],
       [0, 0, 0, 0, 0],
       [9, 0, 0, 0, 0]])

In [69]:
tf.strings.as_string([3.1415926, 2.71828], precision=2).numpy()

array([b'3.14', b'2.72'], dtype=object)

In [70]:
tf.strings.bytes_split('hello').numpy()

array([b'h', b'e', b'l', b'l', b'o'], dtype=object)

In [71]:
tensor_a = tf.range(2)
tensor_b = tf.range(1, 4, 2)
tf.strings.format("a: {}, b: {}, suffix", (tensor_a, tensor_b))

<tf.Tensor: shape=(), dtype=string, numpy=b'a: [0 1], b: [1 3], suffix'>

In [72]:
tf.strings.join([['abc', '123'], ['def', '456'], ['ghi', '789']]).numpy()

array([b'abcdefghi', b'123456789'], dtype=object)

In [73]:
strings = tf.constant(["Hello", "Tensorflow", "\u0001F642"])
tf.strings.length(strings).numpy()

array([ 5, 10,  5])

In [74]:
tf.strings.lower("CamelCase strigs and ALL CAPS")

<tf.Tensor: shape=(), dtype=string, numpy=b'camelcase strigs and all caps'>

In [75]:
tf.strings.ngrams(["A", "B", "C", "D"], 2).numpy()

array([b'A B', b'B C', b'C D'], dtype=object)

In [76]:
tf.strings.reduce_join([['abc', '123'], ['def', '456']]).numpy()

b'abc123def456'

In [77]:
tf.strings.regex_full_match(["TF lib", "lib TF"], ".*lib$")

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [78]:
tf.strings.regex_replace("Text with tags.<br /> <b>contains html</b>", "<[^>]+>", " ")

<tf.Tensor: shape=(), dtype=string, numpy=b'Text with tags.   contains html '>

In [79]:
tf.strings.split('Hello World').numpy()

array([b'Hello', b'World'], dtype=object)

In [81]:
tf.strings.strip(["\nTensorflow", "    The Python library   "]).numpy()

array([b'Tensorflow', b'The Python library'], dtype=object)

In [83]:
tf.strings.substr(["hello", "world"], 1, 2).numpy()

array([b'el', b'or'], dtype=object)

In [84]:
tf.strings.to_hash_bucket(["Hello", "tensorflow", "2.x"], 3)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 2, 1], dtype=int64)>

In [85]:
tf.strings.to_hash_bucket_fast(["hello", "Tensorflow", "2.x"], 3).numpy()

array([1, 0, 2], dtype=int64)

In [86]:
tf.strings.to_hash_bucket_strong(["hello", "TF"], 3, [1, 2]).numpy()

array([1, 0], dtype=int64)

In [2]:
tf.strings.to_number("1.55")

<tf.Tensor: shape=(), dtype=float32, numpy=1.55>

In [11]:
inputs = [s.encode('utf8') for s in (u"G\xf6\xf6dnight", u"\u0001f60a")]
tf.strings.unicode_decode(inputs, "UTF-8").to_list()

[[71, 246, 246, 100, 110, 105, 103, 104, 116], [1, 102, 54, 48, 97]]

In [4]:
result = tf.strings.unicode_decode_with_offsets(input, "utf-8")
print(result[0].to_list())
result[1].to_list()

[[71, 246, 246, 100, 110, 105, 103, 104, 116], [1, 102, 54, 48, 97]]


[[0, 1, 3, 5, 6, 7, 8, 9, 10], [0, 1, 2, 3, 4]]

In [7]:
input = tf.ragged.constant([[71, 246, 246, 100, 110, 105, 103, 104, 116], [128522]])
print(tf.strings.unicode_encode(input, "UTF-8"))

tf.Tensor([b'G\xc3\xb6\xc3\xb6dnight' b'\xf0\x9f\x98\x8a'], shape=(2,), dtype=string)


In [8]:
tf.strings.unicode_script([1, 31, 38])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 0])>

In [12]:
tf.strings.unicode_split(inputs, "UTF-8").to_list()

[[b'G', b'\xc3\xb6', b'\xc3\xb6', b'd', b'n', b'i', b'g', b'h', b't'],
 [b'\x01', b'f', b'6', b'0', b'a']]

In [13]:
result = tf.strings.unicode_split_with_offsets(inputs, "UTF-8")
print(result[0].to_list())
print(result[1].to_list())

[[b'G', b'\xc3\xb6', b'\xc3\xb6', b'd', b'n', b'i', b'g', b'h', b't'], [b'\x01', b'f', b'6', b'0', b'a']]
[[0, 1, 3, 5, 6, 7, 8, 9, 10], [0, 1, 2, 3, 4]]


In [14]:
tf.strings.unicode_transcode(["Hello", "tensorflow", "2.x"], "UTF-8", "UTF-16-BE")

<tf.Tensor: shape=(3,), dtype=string, numpy=
array([b'\x00H\x00e\x00l\x00l\x00o',
       b'\x00t\x00e\x00n\x00s\x00o\x00r\x00f\x00l\x00o\x00w',
       b'\x002\x00.\x00x'], dtype=object)>

In [17]:
inputs = [['Y', 'q', 'c'], ['Y', '6', '6'], ['p', 'G', 'a']]
output_array = tf.strings.unsorted_segment_join(inputs=inputs, segment_ids=[1, 0, 1], num_segments=2, separator=":")
output_array

<tf.Tensor: shape=(2, 3), dtype=string, numpy=
array([[b'Y', b'6', b'6'],
       [b'Y:p', b'q:G', b'c:a']], dtype=object)>

In [18]:
tf.strings.upper("CamelCase string and ALL CAPS")

<tf.Tensor: shape=(), dtype=string, numpy=b'CAMELCASE STRING AND ALL CAPS'>